- .travis.yml
- other/apidsl/toxav.in.h
- toxav/toxav.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/1)
> Apidsl fixes and start tracking test coverage

- .travis.yml
The logging code is rarely tested by users, so we use Travis to exercise it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/2)
> Enable toxcore logging when building on Travis.

- other/bootstrap_daemon/README.md
Update the manual to provide a command necessary to open <1024 ports for users on SysVinit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/11)
> Documentation: SysVInit workaround for <1024 ports

- toxcore/network.c
sodium_init returns 1 when the library was already initialised. Toxcore code
wasn't prepared to handle sodium errors, so it thought it was an allocation
error.
This error is still not handled correctly. If crypto fails to initialise, it
will think it's an allocation error. Fixing this requires too many code changes,
so must be done later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/32)
> Fix a bug I introduced that would make toxcore fail to initialise a second time

- .travis.yml
- auto_tests/tox_test.c
- other/apidsl/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/13)
> Enable, and report test status

- .travis.yml
- other/travis/hstox-after_script
- other/travis/hstox-install
- other/travis/hstox-script
- other/travis/toxcore-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/30)
> 2. Hstox test

- .travis.yml
- auto_tests/tox_test.c
- other/bootstrap_daemon/src/command_line_arguments.h
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/config.h
- other/fun/strkey.c
- other/travis/toxcore-script
- toxav/toxav.c
- toxcore/tox.c
- toxdns/toxdns.c
- toxencryptsave/toxencryptsave.c
Depends on #16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/20)
> 3. Travis astyle

- .travis.yml
- CMakeLists.txt
- other/pkgconfig/toxav.pc.in
- other/pkgconfig/toxcore.pc.in
- other/pkgconfig/toxdns.pc.in
- other/pkgconfig/toxencryptsave.pc.in
- other/travis/autotools-after_script
- other/travis/autotools-script
- other/travis/env-linux.sh
- other/travis/env.sh
- other/travis/hstox-after_script
- other/travis/hstox-install
- other/travis/hstox-script
- other/travis/toxcore-after_script
- other/travis/toxcore-install
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/31)
> 7. Travis envs

- configure.ac
- other/travis/autotools-script
If libsodium can't be found with AC_CHECK_LIB, try PKG_CHECK_MODULES. If that
also fails, abort configure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/38)
> Try searching for libsodium with pkg-config in ./configure.

- CMakeLists.txt
- other/travis/autotools-script
- other/travis/env-linux.sh
- other/travis/toxcore-install
- other/travis/toxcore-script
- testing/misc_tools.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/assoc.c
- toxcore/network.c
- toxcore/util.c
- This PR also adds a DEBUG cmake option that enables -DDEBUG.
- We also remove `-Wall`, because there are too many warnings, and nobody really
looks at them at the moment. We'll see about fixing them soon. We'll also want
to enable `-Werror` at some point.
- We also factor out `nproc` calls into the env scripts so we can use `sysctl` on OSX where `nproc` doesn't exist.
- Finally, this PR enables `-O3` to make sure toxcore still works correctly
under heavy compiler optimisations.
--
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/37)
> Add missing DHT_bootstrap to CMakeLists.txt.

- auto_tests/TCP_test.c
- auto_tests/assoc_test.c
- auto_tests/dht_test.c
- auto_tests/encryptsave_test.c
- auto_tests/onion_test.c
- auto_tests/tox_test.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/irc_syncbot.c
- testing/tox_shell.c
- toxav/audio.h
- toxav/group.h
- toxav/rtp.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/41)
> Fix warnings

- auto_tests/tox_test.c
- other/apidsl/tox.in.h
- testing/Messenger_test.c
- testing/irc_syncbot.c
- testing/nTox.c
- testing/tox_shell.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/48)
> Make friend message callback stateless

- other/apidsl/tox.in.h
- other/astyle/format-source
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/57)
> Make Friend User Status stateless

- other/apidsl/tox.in.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/58)
> Make Message received receipts stateless

- CMakeLists.txt
- other/astyle/format-source
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/49)
> Apidsl test

- auto_tests/tox_test.c
10x timeouts forces travis to kill our build without offering anything helpful
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/62)
> Reduce the timeout on travis to something much more reasonable

- auto_tests/assoc_test.c
Once every new moon, the assoc_test would fail because the key is 0. It
can be anything but 0 to succeed, so I made it 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/63)
> Initialise the id in assoc_test.

- auto_tests/toxav_many_test.c
OS X and Windows have small thread stacks by default. Allocating audio and video
frames (about 962KB total) on the stack overflows it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/65)
> Avoid large stack allocations on thread stacks.

- toxcore/tox.c
These functions simply return the constants. They are a stable ABI, so that if
constants change, the ABI of these functions won't. Code solely relying on these
functions will remain compatible with future values of those constants.
The functions are currently not exposed in tox.h, because this is pending a
change in apidsl to generate accessors for "const" values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/70)
> Expose constants as functions.

- auto_tests/TCP_test.c
- auto_tests/encryptsave_test.c
- auto_tests/onion_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/apidsl/tox.in.h
- testing/Messenger_test.c
- testing/av_test.c
- testing/nTox.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/friend_requests.c
- toxcore/friend_requests.h
- toxcore/group.c
- toxcore/group.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/tox.c
- toxcore/tox.h
Messenger is slightly twisty when it comes to sending connection status callbacks
It will very likely need at the very least a partial refactor to clean it up a
bit. Toxcore shouldn't need void *userdata as deep as is currently does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/60)
> Make friend requests stateless

- toxav/msi.c
- toxcore/Messenger.c
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/110)
> Comment intentional switch fallthroughs

- toxav/bwcontroller.c
1. This mutation is never observed outside the function.
2. If it were (it's not), it would be undefined behaviour, since the
packet data goes out of scope a few instructions after the callback
returns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/100)
> Remove the packet mutation in toxav's bwcontroller.

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/109)
> Separate ip_port packing from pack_nodes() and unpack_nodes()

- auto_tests/tox_test.c
- other/apidsl/tox.in.h
- testing/nTox.c
- testing/tox_shell.c
- testing/tox_sync.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/120)
> make the majority of the callbacks stateless and add some status to a testcase

- toxcore/DHT.c
See #78.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/132)
> Remove `else` directly after `return`.

- CMakeLists.txt
- auto_tests/tox_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/142)
> Fix for windows dynamic libraries.

- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/apidsl/tox.in.h
- other/apidsl/toxav.in.h
- other/toktok-rebase
- testing/av_test.c
- toxav/audio.c
- toxav/audio.h
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/msi.c
- toxav/msi.h
- toxav/rtp.c
- toxav/toxav.c
- toxav/toxav.h
- toxav/video.c
- toxav/video.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.h
- toxcore/util.h
See #40.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/130)
> Make ToxAV stateless

- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/148)
> Added UB comment r/t deleting a friend w/ active call

- CMakeLists.txt
- other/travis/toxcore-script
Enabling this flag will generate and use an LD version script. It
ensures that the dynamic libraries (libtoxcore.so, libtoxav.so) only
export the symbols that are defined in their public API (tox.h and
toxav.h, respectively).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/117)
> Add STRICT_ABI cmake flag to generate export lists.

- auto_tests/tox_test.c
- other/apidsl/tox.in.h
- testing/irc_syncbot.c
- testing/nTox.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/group.c
- toxcore/group.h
- toxcore/tox.c
- toxcore/tox.h
---
This change is NOT reviewable. Use Github reviews instead.
> Make group callbacks stateless

- CMakeLists.txt
`tox_options_[gs]et_ipv6_enabled` were missing from the version script
because the grep expression only accepted `[a-z_]`. Now it also accepts
digits in the function names.
---
This change is NOT reviewable. Use Github reviews instead.
> Fix strict-ld grep expressions to include digits.

- auto_tests/TCP_test.c
- toxcore/Messenger.c
- toxcore/TCP_server.c
- toxcore/TCP_server.h
We should aim to make as many structures module-private as possible.
> Make TCP_Server opaque.

- .travis.yml
Given that it fails about 80-90% of the time, it's not worth requiring
it to pass. Instead, we'll need to manually look at the osx build to see
in what way it failed.
> Allow the OSX build to fail on travis.

- toxav/video.h
`vbuf_raw` is always a `RingBuffer*` so there is no need to pretend it
could ever be anything else (as indicated by it being a pointer to
void).
> Replace `void*` with `RingBuffer*` to avoid conversions.

- auto_tests/TCP_test.c
- auto_tests/encryptsave_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/bootstrap_daemon/src/log.c
- testing/DHT_test.c
- toxav/msi.c
- toxcore/Messenger.c
- toxcore/network.c
- All global variables should be static unless they have an explicit
extern declaration in a header file.
- `to_compare` was not used in encryptsave and toxav tests.
- `break` in switch cases is not required directly after `return`,
`goto`, or a noreturn function like `abort`.
> Minor cleanups: unused vars, unreachable code, static globals.

- CMakeLists.txt
- other/astyle/format-source
- testing/av_test.c
- toxav/ring_buffer.c
OpenCV 3.1 doesn't define cvRound in C, only in C++. Thus, we now need
to compile av_test as C++ code.
> Work around bug in opencv3 headers.

- toxcore/friend_connection.c
- toxcore/friend_connection.h
These three objects and their callback IDs are always the same.
> Remove redundant callback objects.

- CMakeLists.txt
- other/version-sync
This will update tox.in.h only. Currently, you will still need to
manually update tox.h. An upcoming PR (#154) will update tox.h as
part of the build.
> Add version-sync script.

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/logger.c
- toxcore/logger.h
- toxcore/tox.c
We don't currently support callbacks without context object.
> Add the 'Tox' context object to the logger.

- other/apidsl/tox.in.h
- other/apidsl/toxav.in.h
- toxav/toxav.h
- toxcore/tox.h
- Fixed incorrect parameter names (documented name didn't match code
name).
- Removed `@return` from functions that return `void`.
- Make sure every parameter is documented. This required moving the
planes and strides documentation to the function docs.
> Minor documentation fixes.

- CMakeLists.txt
All tests must end in `_test` so we can use this convention to slightly
shorten the names in `auto_test` calls. This also enforces the
convention so future tests obey it.
> Remove the _test suffix in auto_test calls.

- CMakeLists.txt
- other/travis/toxcore-script
Some tests take 20 or more minutes to run before they timeout, this allows
to limit their runtime if needed.
> Add option to set test timeout

- CMakeLists.txt
- other/travis/env-linux.sh
- other/travis/env-osx.sh
- other/travis/env-windows.sh
- other/travis/toxcore-script
When cross-compiling to <target> from Linux, cmake might find native Linux
libconfig and decide to build tox-bootstrapd. If the target is Windows, this
will fail, as tox-bootstrapd can't be built for Windows in the first place. If
the target is Linux of some other architecture, then using host native
libconfig will fail too. Thus an option is needed to guard against this.
> Add option to build tox-bootstrapd

- toxcore/TCP_server.c
Not all platforms define `socklen_t` as `unsigned int`. E.g. Android
defines it as `int`.
> Use `socklen_t` instead of `unsigned int` in call to `accept`.

- CMakeLists.txt
- other/travis/toxcore-script
We use TRACE=ON (cmake flag) to enable LOG_TRACE. This way, a regular
build can enable DEBUG while not paying the price of TRACE. This is
particularly important for FFI bindings (especially Python), where
invoking callbacks can be an expensive operation.
> Set log level for DEBUG=ON to LOG_DEBUG.

- auto_tests/conference_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_one_test.c
In a next step, we will remove tests from each file to have a per-binary
split of tests. This will help identify which tests fail most often on
Travis CI.
In another future step, we will split the large one_test into several
auto tests, which will make testing quite a bit slower (adding about 10
seconds setup time to each), but hopefully a lot more stable ("Tox went
offline" should not happen as much anymore).
> Duplicate tox_test to 4 other files.

- CMakeLists.txt
- cmake/MacRpath.cmake
This makes deployment easier, as the install libpath is used to look up
dependent libraries.
> Install libraries with RPATH.

- CMakeLists.txt
- cmake/ApiDsl.cmake
- other/astyle/format-source
- other/travis/env-linux.sh
This ensures that on Travis, format_test will always be executed, or the
build fails.
> Error if format_test can't be executed.

- toxav/toxav_old.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/group.c
- toxcore/tox.c
This is to allow new group chats to coexist with old group chats. We do
not rename everything in group.[ch] to conference, yet, because it's not
currently necessary, and a general internal API overhaul is due at some
point anyway.
> Rename some internal "group chat" thing to "conference".

- toxcore/tox.api.h
- toxcore/tox.h
In the future, we may want to revisit this parameter, but right now, it
serves no purpose and only confuses tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/228)
> Remove unimplemented "time delta" parameter.

- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/212)
> Convert series of NET_PACKET_* defines into a typedef enum

- toxcore/network.h
Hex constants make it clearer that you can only use 2 nibbles (the two
digits of the number, displayed as two columns in the source code), i.e.
1 byte, for the packet kind. It also makes the bit representation easier
to see.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/245)
> Change packet kind enum to use hex constants.

- toxcore/tox.api.h
- toxcore/tox.h
`TOX_LOG_LEVEL_LOG_TRACE` => `TOX_LOG_LEVEL_TRACE`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/251)
> Rename log levels to remove the extra "LOG" prefix.

- auto_tests/conference_test.c
- auto_tests/encryptsave_test.c
- auto_tests/helpers.h
- auto_tests/messenger_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_one_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- testing/Messenger_test.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
Previously, all log messages generated by tox_new (which is quite a lot)
were dropped, because client code had no chance to register a logging
callback, yet. This change allows setting the log callback from the
beginning and removes the ability to unset it.
Since the log callback is forever special, since it can't be stateless,
we don't necessarily need to treat it uniformly (with `event`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/241)
> Move log callback to options.

- CMakeLists.txt
Also, disable -pedantic on C++, because it's not really useful there,
and causes a lot of warnings on `enum FOO { BAR, };` (comma at end of
enumerator list).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/255)
> Disable some gcc-specific warnings.

- auto_tests/TCP_test.c
- auto_tests/onion_test.c
- testing/hstox/methods.c
- toxcore/DHT.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/net_crypto.c
- toxcore/onion.c
- toxcore/onion_client.c
- toxcore/ping.c
`new_nonce` has been an alias for `random_nonce` for a while now. Having
two names for the same operation is confusing. `random_nonce` better
expresses the intent. The documentation for `new_nonce` talks about
guaranteeing that the nonce is different from previous ones, which is
incorrect, it's just quite likely to be different.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/248)
> Remove new_nonce function in favour of random_nonce.

- other/travis/env.sh
Travis seems to no longer set $TERM, which breaks opam. We now manually
set it to some hopefully sane value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/261)
> Work around Travis issue that causes build failures.

- testing/hstox/binary_decode.c
- testing/hstox/binary_encode.c
These are implemented in terms of decode/encode CipherText. They do the
exact same thing, since they are both simple length-prefixed byte arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/257)
> Add decode/encode PlainText test support.

- auto_tests/dht_test.c
- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/224)
> Add DHT_create_packet, an abstraction for DHT RPC packets

- CMakeLists.txt
This warning is triggered in `av_test.c`, where we have an open issue.
Silencing the warning locally would make the issue less visible. This
way, we will see the warning when we start removing the `-Wno-*` flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/265)
> Disable -Wunused-but-set-variable compiler warning flag.

- CMakeLists.txt
- other/astyle/format-source
- toxcore/crypto_core.api.h
This allows us to use apidsl features like namespaces to enforce a
naming standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/249)
> Use apidsl for the crypto_core API.

- testing/av_test.c
Now it compiles and takes arbitrary resolutions video for input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/260)
> Support arbitrary video resolutions in av_test

- toxcore/Messenger.c
cppcheck complains about being redundant or incorrcet. I'd rather be correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/274)
> Options in new_messenger() must never be null.

- auto_tests/tox_one_test.c
- toxcore/Messenger.c
Fixes #215.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/281)
> Made save format platform-independent

- testing/hstox/methods.c
`transformed` is leaking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/277)
> Fix a memory leak in hstox interface

- toxav/msi.c
- toxav/msi.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
Dereferencing `session` right after making sure that it's NULL is probably not a very good idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/276)
> Fix NULL pointer dereference in log calls

- toxav/groupav.c
[Clang's scan-build has identified two potential memory leaks in `groupav.c`](https://build.tox.chat/view/libtoxcore/job/libtoxcore-toktok_analyze_scan-build/21/clangScanBuildBugs/). Looks like there were cases when the `decode_audio_packet()` function would return without freeing the allocated memory, which is fixed by this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/275)
> Fix a memory leak in GroupAV

- CMakeLists.txt
* BUILD_NTOX for nTox
* BUILD_AV_TEST for the toxav test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/287)
> Add CMake knobs to suppress building tests

- auto_tests/dht_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/DHT_test.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/262)
> Add ability to disable UDP hole punching

- CMakeLists.txt
- other/travis/env.sh
Build it on Travis. It won't be built on the windows builds regardless
of having it enabled globally.
Fixes #292.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/303)
> Don't build nTox by default.

- toxencryptsave/toxencryptsave.h
~~Fixes a possible buffer overrun by `memcpy()` in `tox_is_data_encrypted()` when the `data` is less than `TOX_ENC_SAVE_MAGIC_LENGTH`. There was the very same buffer overrun present in `tox_get_salt()`, which I replaced with a call to `tox_is_data_encrypted()`. I have also added some extra checks on function inputs.~~
TES seems to be somewhat poorely written, for example, the same `tox_get_salt()` function doesn't check if `salt` has enough space to store the entire salt, nor does the documentation to `tox_get_salt()` mention anything about the salt being `TOX_PASS_SALT_LENGTH` in size. We should really consider reviewing the TES module and porting its interface to APIDSL.
~~This PR breaks API.~~
**Edited:** Fixes a possible buffer overrun by `memcpy()` in `tox_is_data_encrypted()` when …
> Clarify toxencryptsave documentation regarding buffer sizes

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/299)
> net_crypto give handle_data_packet_helper a better name

- libtoxcore.pc.in
- other/pkgconfig/toxcore.pc.in
I'm porting tuntox to work with TokTok c-toxcore and couldn't get it to link statically - dynamic linking works.
I'm not sure if the solution in this pull request is valid but it definitely makes the static linking work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/305)
> Fix static builds

- toxcore/Messenger.c
This only works on LP64. It may fail on Windows, which can be LLP64
(IL32P64).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/312)
> Conditionally enable non-portable assert on LP64.

- configure.ac
- other/travis/autotools-script
We also never really tested this, because we run make distcheck, which
does another configure with default flags instead of the ones we passed.
Fixes #317.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/318)
> Fix `--enable-logging` flag in autotools configure script.

- CMakeLists.txt
- auto_tests/version_test.c
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
When the version number has trailing zeros, a change of the first non-zero number means a break in API compatibility. eg. 0.0.1 to 0.0.2 means a break, 0.3.0 to 0.4.0 means a break, but 0.3.0 to 0.3.1 means not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/315)
> Fix version compatibility test.

- CMakeLists.txt
- auto_tests/encryptsave_test.c
- other/astyle/format-source
- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/310)
> Add apidsl file for toxencryptsave.

- CMakeLists.txt
- other/pkgconfig/libtoxav.pc.in
- other/pkgconfig/libtoxcore.pc.in
These were generated by the autotools build. Some clients may depend on
these files instead of the newer split pkg-config files. New clients
should be using the toxcore, toxav, toxencryptsave, and toxdns modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/322)
> Add compatibility pkg-config modules: libtoxcore, libtoxav.

- CMakeLists.txt
CMake lists are `;` separated and CMAKE_THREAD_LIBS_INIT contains
"-lpthread". This resulted in "-l-lpthread;-lrt" on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/325)
> Fix Libs line in toxcore.pc pkg-config file.

- CMakeLists.txt
- configure.ac
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/316)
> Release 0.1.0.

- auto_tests/toxav_many_test.c
Fixed race condition in the case when we already called toxav_kill but concurrent thread is actually still alive and is accessing its ToxAV instance. #278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/309)
> Fixed attempt to join detached threads (fixes toxav test crash)

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
#296 was storing local peer discovery option in DHT, when it should be local to friend connections, as friend connections are the only ones who use LAN discovery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/306)
> Add option to disable local peer discovery

- toxcore/tox.api.h
- toxcore/tox.h
Closes #327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/328)
> Drop the broken `TOX_VERSION_REQUIRE` macro.

- toxcore/tox.api.h
- toxcore/tox.h
We really want to get all clients off this struct. We won't actually
remove it until 0.2, but we're going to break ABI compatibility with this
in various 0.1.x releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/330)
> Strengthen the note about ABI compatibility in tox.h.

- auto_tests/file_saving_test.c
The test includes obtaining savedata from c-toxcore, writing it to a file, reading the file again and checking a value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/332)
> Add test for savedata.

- toxencryptsave/toxencryptsave.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/344)
> Remove unused get/set salt/key functions from toxencryptsave.

- toxcore/Messenger.c
Fixes #345.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/346)
> Avoid array out of bounds read in friend saving.

- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/353)
> Fix toxav use after free caused by premature MSI destruction

- CMakeLists.txt
The CMAKE_SOURCE_DIR variable points to the top-level directory of a (parent) project while we want to point to the top-level (source) directory of the lib. This change simplifies the integration as a third-party lib. We can use CMAKE_CURRENT_SOURCE_DIR or simply "nothing" ('.') to point to the directory where the CMakeLists.txt file resides.
**Note:**
I am unsure about [the tox-spectest line](https://github.com/TokTok/c-toxcore/blob/master/CMakeLists.txt#L362) and left it out for now -> should definitely live somwhere inside the build directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/361)
> Simplify integration as a third-party lib in cmake projects

- CMakeLists.txt
This was just for finding it in toktok-stack, which now uses
haskell-stack, and thus no longer has a .cabal-sandbox. We'll just assume
that the Makefile properly sets up the path such that tox-spectest is
available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/362)
> Remove .cabal-sandbox option from tox-spectest find line.

- other/travis/toxcore-linux-install
We really don't care about coveralls doing its call to the right server.
The worst that can happen is that someone MITMs our coverage analysis,
which we already don't care about much at this point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/377)
> Fix SSL verification in coveralls.

- INSTALL.md
- configure.ac
- other/Makefile.inc
closes #319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/324)
> Do not compile and install DHT_bootstrap if it was disabled in configure

- .gitignore
- CMakeLists.txt
- auto_tests/TCP_test.c
- auto_tests/conference_test.c
- auto_tests/dht_test.c
- auto_tests/network_test.c
- auto_tests/onion_test.c
- auto_tests/save_friend_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/log.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/av_test.c
- testing/irc_syncbot.c
- testing/misc_tools.c
- testing/tox_shell.c
- testing/tox_sync.c
- toxcore/TCP_server.c
- toxcore/network.c
- toxcore/tox.c
- toxcore/util.c
- CFLAG gnu99 was changed to c99.
- CXXFLAG c++98 was changed to c++11.
- CFLAG -pedantic-errors was added so that non-ISO C now throws errors.
- _XOPEN_SOURCE feature test macro added and set to 600 to expose SUSv3
and c99 definitions in modules that required them.
- Fixed tests (and bootstrap daemon logging) that were failing due to
the altered build flags.
- Avoid string suffix misinterpretation; explicit narrowing conversion.
- Misc. additions to .gitignore to make sure build artifacts don't wind
up in version control.
I didn't try running the tests, but everything seems to build just fine now. If someone could test for me, I'd really appreciate it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Portability fixes

- CMakeLists.txt
- cmake/ModulePackage.cmake
- other/travis/toxcore-script
This takes a few seconds but allows us to cover cases that aren't checked
often.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/380)
> Test a few cmake option combinations before the build.

- .gitignore
- CMakeLists.txt
- auto_tests/TCP_test.c
- auto_tests/conference_test.c
- auto_tests/dht_test.c
- auto_tests/network_test.c
- auto_tests/onion_test.c
- auto_tests/save_friend_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/log.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/av_test.c
- testing/irc_syncbot.c
- testing/misc_tools.c
- testing/tox_shell.c
- testing/tox_sync.c
- toxcore/TCP_server.c
- toxcore/network.c
- toxcore/tox.c
- toxcore/util.c
This reverts commit f3469070fe899e8e4fd88665386a55bad9f77cd8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/395)
> Revert "Portability fixes"

- toxcore/DHT.c
Previously, the `ipv6` variable was initialised to `-1`, but that value
was never read. Either it was set to 0 or 1, or the function would return
before it was read. Thus, I've changed it to uninitialised `bool is_ipv4`
(inverted semantics to avoid negative conditions `if (!is_ipv6)`).
The `pack_ip_port` function is a bit unfortunate, but I'm not rewriting
it until we have a binary writer (I'd be rewriting it twice).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/387)
> Eliminate dead return statement.

- toxcore/crypto_core_mem.c
Found through [cppcheck](https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/55/cppcheckResult/source.17/#35).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/404)
> Issue 404: semicolon not found

- CMakeLists.txt
We still have some non-standard C code in toxcore for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/403)
> Warn on -pedantic, don't error yet.

- toxcore/net_crypto.c
On x86 and x86_64, this change has no effect. On IA64, this fixes a
potential hardware exception. A function returned a partially initialised
value of aggregate type. The only caller of this function checks that the
value is valid before accessing it by testing the one definitely
initialised member. Therefore on x86 and derived architectures, there is
no uninitialised memory access. On IA64, with the regular calling
convention, the struct is allocated on the caller stack and passed as a
pointer, so there the uninitialised memory is also never accessed.
However, on calling conventions where one or more struct members past the
first byte are passed in registers or copied in memory, this call can
cause undefined behaviour.
Specifically, the value can contain a trap representation of the …
> Avoid accessing uninitialised memory in `net_crypto`.

- other/travis/autotools-linux-install
tar -jxf expects a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/410)
> Fix NaCl build: tar was called incorrectly.

- CMakeLists.txt
- cmake/ModulePackage.cmake
As mentioned in https://github.com/TokTok/c-toxcore/issues/359#issuecomment-270710463
the current CMake build does not generate version symlinks for library .so files.
This is because the version is not specified for library targets.
See
- https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html#prop_tgt:SOVERSION
- https://cmake.org/cmake/help/v3.0/prop_tgt/VERSION.html#prop_tgt:VERSION
~~I have used `VERSION` instead of `SOVERSION` as this seems to be
compatible with windows according to the docs linked above.~~ updated: changed this, see comments below.
I have compared installed files with autotools build vs. cmake:
autotools:
```
$ find . | sort
.
./bin
./include
./include/tox
./include/tox/toxav.h
./include/tox/toxdns.h
./include/tox/toxencryptsave.h
./include/tox/tox.h
./lib …
```
> CMake: Add soversion to library files to generate proper symlinks

- configure.ac
c-tocxocre will start using C99 code, so check if the compiler supports
it and abort in configure with an error if it does not.
closes #413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/414)
> Explicitly check if compiler supports C99

- toxcore/Messenger.c
Details in comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/391)
> Minor simplification in `file_seek` code.

- toxcore/Messenger.c
Previously, toxcore would send a kill control to the friend only if the
file control was valid. Determining which file transfer is used does not
depend on the specific file control. We can always kill it in that case.
Also, added some logging for file control logic, since there is no other
feedback on error (failure of the file control handler is swallowed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/390)
> Always kill invalid file transfers when receiving file controls.

- toxcore/TCP_connection.c
They aren't, but it's unclear whether it's structurally impossible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/392)
> Check that TCP connections aren't dropped in callbacks.

- CMakeLists.txt
- configure.ac
- testing/misc_tools.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/util.c
- toxcore/util.h
These are cheap asserts. I've also replaced the fprintf's with
`LOGGER_ERROR` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/381)
> Remove `TOX_DEBUG` and have asserts always enabled.

- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/409)
> Clarify that the pass key `new` function can fail.

- testing/irc_syncbot.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/424)
> Fixed the FreeBSD build failure due to the undefined MSG_NOSIGNAL.

- CMakeLists.txt
It's enabled by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/443)
> Make building `DHT_bootstrap` in cmake optional.

- circle.yml
Retrying all tests is more likely to result in a different set of tests
failing the second time. This change makes sure only the failed tests are
retried.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/448)
> Only retry failed tests on Circle CI instead of all.

- auto_tests/network_test.c
- testing/DHT_test.c
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/network.c
- toxcore/network.h
- toxcore/util.c
This partially implements #405, reworking ip_ntoa(), ID2String() and cmp_dht_entry() to avoid the use of the global static variables 'addresstext', 'IDString', 'cmp_public_key', and moving 'lastdump' into the Messenger struct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/432)
> Remove some static variables

- circle.yml
- toxcore/TCP_server.c
also include fix for #457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/459)
> Add Android build to CI.

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/434)
> Replace redundant packet type check in handler with assert.

- CMakeLists.txt
- configure.ac
- so.version
- toxcore/DHT.c
- toxcore/tox.api.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/460)
> Release v0.1.6.

- toxcore/DHT.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
I realised that in my previous (now merged) PR#432, I missed a couple of uses
of static variables. This fixes them. Both are entirely analogous to one which
was fixed by that PR in DHT.c, using a static variable to fix the base of
comparison used in a qsort. I've used the same solution. This involves some
unsightly code duplication, but I couldn't see a nice way around that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/471)
> Remove statics used in onion comparison functions.

- appveyor.yml
- cmake/Dependencies.cmake
The AppVeyor MSVC build is failing because it can't find pthreads library. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/479)
> Fix pthreads in AppVeyor build

- toxcore/DHT.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
Seems like this VLA was missed in https://github.com/TokTok/c-toxcore/pull/452.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/480)
> Use VLA macro

- CMakeLists.txt
- auto_tests/TCP_test.c
- auto_tests/crypto_test.c
- auto_tests/dht_test.c
- auto_tests/network_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/bootstrap_node_packets.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/dns3_test.c
- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/rtp.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/461)
> Replace part of network functions on platform-independent implementation

- CMakeLists.txt
- auto_tests/Makefile.inc
- auto_tests/tox_strncasecmp_test.c
- other/DHT_bootstrap.c
- testing/misc_tools.c
`strings.h` is not available on MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/481)
> Remove dependency on strings.h

- other/travis/env-linux.sh
- other/travis/env-osx.sh
- toxcore/tox.h
This fixes (at least I believe it does, need to wait for the Travis report for this PR) Travis builds succeeding despite tests failing.
Travis always succeeding has caused the following things to be unnoticed:
- Version string "0.1.5" not being updated to "0.1.6" when releasing 0.1.6 version (https://github.com/TokTok/c-toxcore/issues/474)
- Missing formatting in PR code (https://github.com/TokTok/c-toxcore/issues/494)
- Heap buffer overflow (https://github.com/TokTok/c-toxcore/issues/495)
Failing Travis build on the test failure is the desired behavior and it was the behavior we had until some commit unintentionally broke it (I suspect https://github.com/TokTok/c-toxcore/commit/f58dbe250329aad0ac2d54789359c162f43de311).
---
This change is [<img …
> Fix Travis always succeeding despite tests failing

- auto_tests/TCP_test.c
- auto_tests/conference_test.c
- auto_tests/dht_test.c
- auto_tests/helpers.h
- auto_tests/onion_test.c
- auto_tests/save_friend_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- other/DHT_bootstrap.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/av_test.c
- testing/dns3_test.c
- testing/misc_tools.c
- testing/nTox.c
- testing/tox_shell.c
- testing/tox_sync.c
Also fix a mistake with forgotten braces around parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/490)
> Move c_sleep to helpers.h and misc_tools.h

- toxcore/network.c
- toxcore/network.h
Thanks @nurupo for the report
From IRC:
> \<nurupo> Diadlo: are you here? there is an issue with the networking code
> \<nurupo> Diadlo: the "Unix API" one on this page. click on Details https://build.tox.chat/job/libtoxcore-toktok_analyze_scan-build/115/clangScanBuildBugs/
> \<nurupo> Diadlo: malloc(0) is undefined behaviour, so you should guard the malloc call with an if-statement checking for 0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/509)
> Fix network malloc(0) bug

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/491)
> Add crypto_memzero for temp buffer

- CMakeLists.txt
if bootstrapd option is enabled the binary should be
installed on `make install`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/504)
> CMake: install bootstrapd if it is built

- other/travis/toxcore-script
Fixes #411.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/524)
> Reduce ctest timeout to 2 minutes from 5 minutes.

- toxencryptsave/toxencryptsave.c
Fixes #503.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/530)
> Implement missing TES constant functions.

- toxcore/LAN_discovery.c
- toxcore/network.c
- toxcore/network.h
Found these missing includes while compiling on FreeBSD 11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/473)
> Added missing includes: <netinet/in.h> and <sys/socket.h>

- auto_tests/dht_test.c
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/512)
> Add test for DHT pack_nodes and unpack_nodes

- INSTALL.md
- docs/av_api.md
- other/bootstrap_daemon/README.md
[GitHub changed how their Markdown parser works](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown) in non-backwards-compatible way, breaking custom anchors and `#Headings` (it's now required to have a space after `#`).
There are lines with `#######` in https://github.com/TokTok/c-toxcore/blob/master/docs/updates/Symmetric-NAT-Transversal.md. Not sure if they were rendered to anything, but they are not being rendered right now, which seems fine to me, so I haven't done anything about them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/534)
> Fix markdown formatting

- toxcore/DHT.c
Currently, when we receive a response to a getnodes request, for each node in
the response we check if it could be added to the close list, and if so we send
the node a getnodes request; if it replies, we add it to the close list.
We do the same for each friends list, but for them we first check whether the
node is already on the friends list, and don't send a getnodes request if it
is.
This change adds a corresponding check for the close list, such that we only
send a getnodes request if the node can be added to the close list *and* is not
already on the close list.
The original behaviour could, and as far as I can see should be expected
typically to, lead to getnode loops resulting in lots of unnecessary traffic.
This can happen as follows: suppose A, B, and C are all close to each …
> Save bandwidth by avoiding superfluous Nodes Requests to peers already on the Close List

- auto_tests/file_saving_test.c
Beforehand, I used my personal style of variable names, short, cryptic, and
not really maintainable for anyone except me. This pull request fixes this.
Greetings,
pranomostro
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/546)
> Make variable names in file saving test less cryptic

- CMakeLists.txt
- auto_tests/Makefile.inc
- auto_tests/selfname_change_conference_test.c
The problem illustrated with this test is that the `tox_callback_conference_namelist_change()` is not invoked for A when A changes his name.
I assumed that this is also incorrect behaviour if the user is not connected to the network, but correct me if this is not the case.
I hope I haven't missed anything important.
Greetings,
pranomostro
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/468)
> Test for memberlist not changing after changing own name

- CMakeLists.txt
- other/bootstrap_daemon/src/Makefile.inc
- other/bootstrap_daemon/src/command_line_arguments.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/log.c
- other/bootstrap_daemon/src/log.h
- other/bootstrap_daemon/src/log_backend_stdout.c
- other/bootstrap_daemon/src/log_backend_stdout.h
- other/bootstrap_daemon/src/log_backend_syslog.c
- other/bootstrap_daemon/src/log_backend_syslog.h
- other/bootstrap_daemon/src/tox-bootstrapd.c
- `log_backend.h` defines an interface for logging back-ends, which `log_backend_[stdout|syslog].[h|c]` implement. These implementations are then put together into a `BACKENDS` array in `log.c`, which is indexed by the `LOG_BACKEND` enum. Haven't really done any such modular implementations in C before, so any corrections are welcome.
- Renamed
- `open_log()` --> `log_open()`
- `close_log()` --> `log_close()`
- `write_log()` --> `log_write()`
Should probably have been a separate commit/PR, but I happened to do the renaming and modularization at the same time, so there we go.
I meant to make logging modular from the beginning, but at the time of writing it I thought that maybe it's simpler to keep all logging backends relatively separate in `log.c` as there is so little code, instead of …
> Split daemon's logging backends in separate modules

- toxcore/DHT.c
- toxcore/DHT.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/498)
> DHT refactoring

- toxcore/net_crypto.c
All other code in this file does lock/call/unlock, except this one instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/557)
> Document inverted mutex lock/unlock.

- CMakeLists.txt
- auto_tests/Makefile.inc
- auto_tests/self_conference_title_change_test.c
When user A changes the title for a conference, the tox_callback_conference_title() is
called for everybody except A. This program tests this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/506)
> Add test case for title change

- toxcore/tox.c
[cppcheck complains](https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/132/cppcheckResult/) about possible memory leak in the case the return value of `net_getipport` overflowed to be -1, which in practice shouldn't happen, but let's guard against it and make cppcheck happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/559)
> Fix theoretical memory leaks

- toxcore/net_crypto.c
Memsetting a double to 0 is not portable.
These are the only doubles/floats in toxcore, I have grepped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/560)
> Fix non-portable zeroing out of doubles

- CMakeLists.txt
Changing the link order fixes the static Windows toxcore build on Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/564)
> Fix Windows build

- toxcore/onion_client.c
- toxcore/onion_client.h
Currently, a large majority of the traffic in the tox network is generated by
pinging onion nodes with Onion Request packets, which a node does to keep
itself announced and to check for friends coming online. This PR significantly
reduces the rate at which such requests are sent.
In part this is by fixing some bugs; probably most significantly, previously
the nodes for friends were always considered timed out when we came to ping
them, since the timeout for announce nodes was used for the check rather than
that for friend nodes, leading to some extra traffic.
Then it implements two schemes for reducing unnecessary pinging. The first is
to start to trust slightly announce nodes and paths which have been alive for a
while, and not ping them so aggressively - while reverting to the old …
> Save bandwidth by moderating onion pinging

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/575)
> Release v0.1.10

- INSTALL.md
Add soft-links for them, in the places that it expects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/571)
> Configure needs to find libsodium headers.

- CMakeLists.txt
CTest include generate a lot of unused targets
See [here](https://stackoverflow.com/questions/45169854/cmake-in-qtcreator-4-3-shows-many-automatic-targets-how-to-remove-hide-them)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/576)
> Replace include(CTest) on enable_testing()

- toxcore/DHT.c
This is an attempt to fix #237, based on a wild guess as to what might be going
on. Currently, if a friend goes offline and we try to reconnect to them, we
will continue the holepunching as if our initial attempt failed. It seems
likely that for many routers the first attempt, which tries ports close to
those which the friend's DHT neighbours report, is the one most likely to
succeed.
If this change does help with that issue, we should probably also tweak the
hole-punching algorithm to occasionally try close ports even if the first
attempt with them fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/574)
> Reset hole-punching parameters after not punching for a while

- toxcore/LAN_discovery.c
- toxcore/friend_connection.c
- toxcore/friend_connection.h
Issue: If another tox instance started on the not default port, LAN
discovery will be failed.
Now tox will iterate though all possible ports to find another tox
instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/586)
> Improve LAN discovery

- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.h
Add correct information about behaviour if input pointer is NULL
Fix #590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/592)
> Adjust docs of few toxencrypt function to the code

- CMakeLists.txt
- auto_tests/TCP_test.c
- auto_tests/conference_test.c
- auto_tests/dht_test.c
- auto_tests/network_test.c
- auto_tests/onion_test.c
- configure.ac
- other/travis/autotools-script
- other/travis/toxcore-script
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/613)
> Fix travis

- toxcore/friend_connection.c
According to my tests, this fixes #240. I expect it also fixes #237.
The problem was as follows: if a friend goes offline for long enough, we stop
searching for them on the DHT, but then if they come back with the same DHT key
(as will be the case if the network connection was interrupted but their client
wasn't restarted), prior to this patch we didn't initiate a new search.
The reason that it took two disconnections for this to cause a problem is that
we keep information on their ip address and tcp relays, and attempt to reuse
after a disconnect if there's still a DHT search ongoing. So if the first
disconnect lasted for at least 122s, the DHT search was deleted, but we could
still connect back using the old details once they reconnected; but then on a
subsequent disconnect, the old …
> forget DHT pubkey of offline friend after DHT timeout

- .travis.yml
- auto_tests/network_test.c
- other/travis/toxcore-linux-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/630)
> Fix for Travis fail on addr_resolve testing

- .travis.yml
This fixes `opam init` crashing due to a stack overflow.
https://travis-ci.org/TokTok/c-toxcore/jobs/313905019#L1152-L1164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/631)
> Add aspcud for Opam

- .travis.yml
- other/travis/toxcore-linux-install
https://github.com/hyperrealm/libconfig has deleted the branches for releases and switched to using tags instead, so the previous method of choosing a release is now broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/632)
> Lift libconfig to v1.7.1

- .travis.yml
- other/bootstrap_daemon/docker/Dockerfile
- other/travis/tox-bootstrapd-docker-linux-script
New Debian stable came out this summer, so let's use that. Better yet, the `slim` version with manpages and other things removed. Also, didn't realize it was still pulling `irungentoo/toxcore`, I guess it wasn't updated since TokTok fork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/637)
> Update tox-bootstrapd Dockerfile

- toxav/toxav.c
Fixes #620 
This is the implementation of the [proposed fix](https://github.com/TokTok/c-toxcore/issues/620#issuecomment-346902071) for [this issue](https://github.com/TokTok/c-toxcore/issues/620).
Haven't tried it myself yet but, it's simple enough to work. NOTE: this fix does not break the protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/623)
> Split video payload into multiple RTP messages when too big to fit into one

- toxcore/Messenger.c
https://github.com/TokTok/c-toxcore/issues/493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/500)
> Fixed the bug when receipts for messages sent from the receipt callback never arrived.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/638)
> Release v0.1.11

- auto_tests/encryptsave_test.c
- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/334)
> Change toxencryptsave API to never overwrite pass keys.

- CMakeLists.txt
- configure.ac
- other/version-sync
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
We're not releasing yet, but projects preparing for the release will want
to build against this version in master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/654)
> Bump toxcore version to 0.2.0.

- circle.yml
- other/travis/env-linux.sh
But enable it on circle ci, so at least we have one asan build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/661)
> Disable asan, since it seems to break on travis.

- testing/hstox/driver.c
- toxcore/network.c
We return E_WRITE because closing only fails when an I/O error occurs,
which is likely an error from the write() call above. See close(2) for
details.
http://man7.org/linux/man-pages/man2/close.2.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/656)
> Fix file descriptor leak in hstox test.

- testing/hstox/driver.c
- toxcore/network.c
These potentially cause uninitialised reads on some platforms or msgpack
library versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/657)
> Zero-initialise stack-allocated objects in hstox driver.

- toxcore/network.c
Without these, we'll have a memory leak on error paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/658)
> Call freeaddrinfo on error paths in net_getipport.

- auto_tests/tox_strncasecmp_test.c
- other/travis/toxcore-script
- testing/Messenger_test.c
- testing/hstox/driver.c
- toxav/rtp.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/crypto_core.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/tox.c
Also replace &(x) with &x for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/659)
> Fix formatting in some C files.

- auto_tests/tox_strncasecmp_test.c
- other/travis/env.sh
- other/travis/toxcore-script
- testing/Messenger_test.c
- testing/hstox/driver.c
- toxav/rtp.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/crypto_core.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/tox.c
This basically means: try until you run out of time (50 minutes on
Travis). On Linux, we really want the tests to pass, so there is no point
in limiting the number of retries. On windows, we don't retry, on FreeBSD
it's limited to 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/660)
> Increase test retries to 10 (basically infinite).

- other/pkgconfig/toxcore.pc.in
To prevent top-level linking of all libraries.
Problem: ```pkg-config --libs toxcore``` returns all libraries that are
required by all libtox*.so libraries. This is wrong because for a
dynamically linked executable only top-level libraries need to be
supplied. ```pkg-config --libs --static toxcore``` should return all
libraries for the statically linked executable.
For example, the ToxBot https://github.com/JFreegman/ToxBot executable
uses pkg-config and is linked with the opus library, which is wrong.
Based on #533.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/667)
> pkg-config .pc files: added .private versions of Libs and Required

- auto_tests/helpers.h
- toxcore/LAN_discovery.c
These may be useful when debugging toxcore locally, but are not useful in
unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/680)
> Filter out annoying log statements in unit tests.

- auto_tests/onion_test.c
- toxcore/onion_announce.c
- toxcore/onion_announce.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/675)
> Make Onion_Announce a module-private type.

- auto_tests/TCP_test.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/674)
> Make TCP_Client_Connection a module-private type.

- auto_tests/TCP_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- testing/hstox/driver.c
- testing/irc_syncbot.c
- testing/nTox.c
- testing/tox_sync.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/681)
> Fix some memory or file descriptor leaks in test code.

- CMakeLists.txt
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/network.h
- toxcore/ping.api.h
- toxcore/ping.c
The ping.api.h file looks rather ugly, but it works. This is an exercise
in finding the complete set of use cases needed from apidsl for toxcore.
We'll try to make things work as much as possible, and then make apidsl
better and make the .api.h files pretty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/679)
> Use apidsl to generate ping.h.

- .gitignore
- CMakeLists.txt
- circle.yml
- cmake/ModulePackage.cmake
- other/pkgconfig/toxcore.pc.in
- other/rpm/Makefile
- other/rpm/tox-bootstrapd.service
- other/rpm/toxcore.spec.in
Update rpm spec and use variables in cmake instead of hardcoded paths.
How to use:
0. `yum groupinstall -y 'Development Tools' && yum install -y epel-release rpm-build && rpmdev-setuptree`
1. `cmake ${TOXCORE_SOURCES}` to generate toxcore.spec from template
2. `spectool --get-files --sourcedir toxcore.spec` <- will not work before merge, use that from my branch: `git archive --prefix 'c-toxcore-0.1.10/' -o ~/rpmbuild/SOURCES/v0.1.10.tar.gz HEAD`
3. `rpmbuild -bb toxcore.spec`
Maybe setup autobuild on tags/commits?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/624)
> Update rpm spec and use variables in cmake instead of hardcoded paths

- .travis.yml
Still run all the jobs during cron and regular push to branch. We
disabled build for push to branch, so cron is the only place where all
builds are run. This also means we need to worry less about spending time
in nightly builds, because they occur only once a day.
See https://github.com/travis-ci/travis-ci/issues/9071
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/690)
> Run fewer Travis jobs during Pull Requests.

- .travis.yml
It takes anywhere from 3 to 6 minutes to install those but only the two first Linux builds make use of them, there is no need to install them in all other builds.
[Yaml anchor](http://www.yaml.org/spec/1.2/spec.html#id2785586) magic trick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/691)
> Don't install packages needlessly on Travis

- other/bootstrap_daemon/docker/Dockerfile.alpine
This PR replaces original Dockerfile with a re-worked version. New version builds a docker image based on Alpine Linux, which significantly reduces image size (to ~8.5MiB).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/465)
> Add Alpine linux Dockerfile in addition to the existing Debian one

- auto_tests/onion_test.c
- toxcore/Messenger.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/onion_client.c
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/689)
>  Make Net_Crypto a module-private type.

- auto_tests/helpers.h
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/DHT_test.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/ping.c
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/688)
> Make DHT a module-private type.

- BUILD
- auto_tests/BUILD
- auto_tests/helpers.h
- other/BUILD
- testing/BUILD
- toxav/BUILD
- toxcore/BUILD
- toxencryptsave/BUILD
This allows us and users to reproducibly build verified versions of the
library with checksums. It will power the toktok-stack continuous build
with checked-in checksums at specific git revisions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/694)
> Add bazel build scripts for c-toxcore.

- auto_tests/crypto_test.c
Increasing from 256K to 1M and increasing the number of iterations from
1000 to 2000. This makes the test more accurate and less flaky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/682)
> Use larger arrays in crypto timing tests.

- toxav/audio.c
- toxav/audio.h
By @zoff99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/698)
> Extract named constants from magic numbers in toxav/audio.c.

- auto_tests/file_saving_test.c
- auto_tests/self_conference_title_change_test.c
- auto_tests/selfname_change_conference_test.c
- testing/av_test.c
This struct will soon become opaque.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/710)
> Don't allocate or dereference Tox_Options in tests.

- toxav/ring_buffer.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/716)
> Add comment from #629 in ring_buffer.c.

- BUILD
- auto_tests/BUILD
- other/BUILD
- testing/BUILD
- toxav/BUILD
- toxcore/BUILD
- toxencryptsave/BUILD
This allows us to precisely see which libraries depend on which and lets
us split them up more, if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/714)
> Make BUILD files more finely-grained.

- .travis.yml
We will only build this during the nightly build. It's very rare for the
autotools build to break when the cmake build does not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/728)
> Disable the autotools build in PR builds.

- toxcore/group.c
Turning this code:
```c
if (cond) { ... return 0; }
if (!cond) { ... return 0; }
return -1;
```
into:
```c
if (cond) { ... return 0; }
else { ... return 0; }
```
The `return -1` in the first variant can never happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/729)
> Remove dead return statement.

- auto_tests/toxav_basic_test.c
- toxav/toxav.api.h
- toxav/toxav.c
- toxav/toxav.h
following https://github.com/TokTok/c-toxcore/issues/572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/578)
> Split toxav_bit_rate_set() into two functions to hold the maximum bitrates libvpx supports

- auto_tests/messenger_test.c
- testing/irc_syncbot.c
Also got rid of a VLA. They are overused a bit in toxcore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/730)
> Fix out of bounds read in error case in messenger_test.

- auto_tests/toxav_basic_test.c
- testing/av_test.c
- toxav/toxav.api.h
- toxav/toxav.c
- toxav/toxav.h
follow TokTok#731. This commit
completely removed all things in namespace bit_rate, and deprecated
functions are to be added back in another commit. set_xxx() is treadted
as a property of namespace audio&video, same as bit_rate change event.
toxav_basic_test is fixed, either.
As for adding legacy functions back, it should be finished in https://github.com/TokTok/c-toxcore/pull/732.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/734)
> Make audio/video bit rates "properties"

- CMakeLists.txt
Without this, `UINT*_MAX` are not defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/741)
> Add `-D__STDC_LIMIT_MACROS=1` for C++ code.

- toxav/rtp.h
This also adds RTPCapabilities and a header field to tell the receiver
about capabilities used in encoding this frame. It is intended to contain
settings relevant to the current frame being sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/739)
> Add RTP header fields for the full frame length and offset.

- toxav/rtp.h
This is more appropriate for RTP headers. Capabilities may be negotiated
up front, but flags are useful in each packet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/745)
> Change the "capabilities" field to a "flags" field.

- .travis.yml
- other/travis/toxcore-linux-install
- toxcore/onion_announce.c
- toxcore/tox_api.c
Since trusty has more up-to-date packages, we can remove some of the
custom install code. Also, we're not using hstox at the moment, so there
is no need to slow down the builds for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/759)
> Use more ubuntu packages; remove hstox for now.

- .travis.yml
- CMakeLists.txt
- auto_tests/conference_test.c
- auto_tests/crypto_test.c
- circle.yml
- other/travis/env.sh
- other/travis/toxcore-script
- toxcore/BUILD.bazel
- toxcore/crypto_core_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/757)
> Improve stability of crypto_memcmp test.

- CMakeLists.txt
- cmake/Dependencies.cmake
Instead of hard-erroring when we don't find dependencies, we just don't
build the things requested and print a warning. This is less annoying to
users because we enable a bunch of things by default. This way, we can at
least build something with the default "cmake" invocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/760)
> Make cmake script more forgiving.

- CMakeLists.txt
- other/fun/BUILD.bazel
- testing/BUILD.bazel
- toxav/rtp.c
- toxav/rtp.h
- toxav/rtp_test.cpp
This is not used by anything in the code, so we shouldn't have it in the
header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/750)
> Remove csrc from the RTPHeader struct.

- toxcore/LAN_discovery.c
Even if that means rejecting packets from ourselves if our IP is not a
"LAN" IP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/772)
> Reject discovery packets coming from outside the "LAN".

- toxcore/group.c
- toxcore/group.h
- toxcore/tox.api.h
- toxcore/tox.h
The logic and behaviour remain the same, but PEER_EXIT and PEER_JOIN are
merged into LIST_CHANGED. This allows clients to take a first step to
adapt to the API change without us having to actually submit the full
change, yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/771)
> Adopt the "change occurred" API change from isotoxin-groupchat.

- CMakeLists.txt
Otherwise it won't be found when cross-compiling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/773)
> Add gtest include directory to -I flags if found.

- cmake/Dependencies.cmake
The .lib doesn't have debugging information. The .dll has a .pdb file
next to it.
This is mostly to avoid >100 warnings in the appveyor build, but also helps if anyone ever wants to actually debug toxcore on windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/767)
> Build toxcore with libsodium.dll instead of libsodium.lib.

- testing/BUILD.bazel
- toxav/BUILD.bazel
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/rtp_test.cpp
- toxav/toxav.c
- toxav/video.c
- toxav/video.h
- toxcore/BUILD.bazel
This change does not include the addition of VP9. We do that in a
separate pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/718)
> Improve sending of large video frames in toxav.

- CMakeLists.txt
So we can keep supporting cmake 2.8.12, which is the version on ubuntu
trusty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/776)
> Optionally use newer cmake features.

- auto_tests/monolith_test.cpp
This forces us to record size changes (for LP64) and helps estimate
memory consumption of internal data structures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/778)
> Add static asserts for all the struct sizes in toxcore.

- auto_tests/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/789)
> Remove tox_test from autotools build.

- auto_tests/monolith_test.cpp
net_crypto has pthread types in its struct, so its size is system
dependent. In particular, the sizes are wrong on FreeBSD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/796)
> Make some sizeof tests linux-only.

- .travis.yml
- CMakeLists.txt
- other/astyle/format-source
- other/travis/toxcore-linux-install
apidsl is in feature freeze. We can rely on the web service, instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/794)
> Remove apidsl from the build.

- toxav/groupav.c
- toxav/groupav.h
- toxav/toxav.api.h
- toxav/toxav.h
- toxav/toxav_old.c
- toxcore/group.c
- toxcore/group.h
- toxcore/tox.c
fixes  #606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/800)
> Make group number in the toxav public API uint32_t

- auto_tests/monolith_test.cpp
- other/astyle/format-source
- toxcore/group.c
- toxcore/group.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
We can now revert the changes to the callbacks and keep supporting them
until clients have moved off them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/799)
> Implement the "persistent conference" callback changes as new functions.

- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/798)
> Add deprecation notices to functions that will go away in v0.3.0.

- CMakeLists.txt
- auto_tests/file_saving_test.c
- other/cpufeatures.c
This is needed for libvpx to work on android.
This also means that we can upload our test binaries to an android device
and actually run them, now that libcheck is no longer a blocker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/807)
> Link all tests to the android cpufeatures library if available.

- toxcore/Messenger.c
Found using the infer static analyser.
https://github.com/facebook/infer
DETECTED=infer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/814)
> Fix memory leak of Logger instance on error paths.

- toxcore/group.c
Fixes #768.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/819)
> Change default username to empty string

- CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/811)
> Update changelog for 0.2.0

- toxav/rtp.c
Resolves #812.
PR from @zoff99's code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/831)
> Don't throw away rtp packets from old Toxcore

- toxav/rtp.c
This change is <img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/832)
From @zoff99's code.
See discussion in #812.
> Don't set RTP_LARGE_FRAME on rtp audio packets

- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/824)
> Simplify sendpacket function, deduplicate some logic.

- toxcore/ccompat.h
- toxcore/logger.c
- toxcore/logger.h
This is useful for debugging a function that doesn't have a logger
available. It should not be used in production code, since it outputs to
stderr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/825)
> Add default stderr logger for logging to nullptr.

- .travis.yml
- other/travis/toxcore-linux-install
The new clang version makes gcov segfault. Also, coveralls needs another
package that it doesn't install the right version of by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/845)
> Fix coveralls reporting.

- CMakeLists.txt
this pr fix the error when `make` on macosx:
> mkdir _builds && cd _builds
> cmake ..
> make
get
> ld: unknown option: -z
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/852)
> bugfix build error on MacOS

- toxcore/net_crypto.c
see #851
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/859)
> add comment to func cryptpacket_received

- auto_tests/TCP_test.c
- auto_tests/conference_test.c
- auto_tests/crypto_test.c
- auto_tests/dht_test.c
- auto_tests/save_friend_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_one_test.c
- toxcore/crypto_core.api.h
- toxcore/crypto_core.c
- toxcore/crypto_core.h
We control the random functions in crypto_core, so we can make them
deterministic more easily. This will help test reproducibility in the
future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/857)
> Avoid the use of rand() in tests.

- CMakeLists.txt
When configuring with CMake with enabled option `BUILD_TOXAV` it warns if required libraries are missing, so I can read logs and understand why something went wrong:
```
CMake Warning at CMakeLists.txt:202 (message):
Option BUILD_TOXAV is enabled but required library OPUS was not found.
CMake Warning at CMakeLists.txt:206 (message):
Option BUILD_TOXAV is enabled but required library VPX was not found.
```
When `libconfig` is missing and option `BOOTSTRAP_DAEMON` is enabled CMake silently succeeds configuration, but `tox-bootstrapd` will not be built. I spent a few hours to understand why I don't have `tox-bootstrapd` during my CI execution. I've changed CMakeLists to display the warning:
```
CMake Warning at CMakeLists.txt:548 (message):
Option BOOTSTRAP_DAEMON is enabled but required …
```
> CMake warn if libconfig not found

- auto_tests/onion_test.c
- toxcore/onion.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/872)
> Restrict packet kinds that can be sent through onion path.

- auto_tests/network_test.c
- testing/av_test.c
- toxav/bwcontroller.c
- toxav/rtp.c
- toxcore/network.c
- toxcore/network.h
Windows doesn't report network errors though errno, it has its own facilities.
Not sure if the `new` and `kill` are the correct words here, toxcore seems to use them for `alloc` and `free`, so I'm just following the pattern.
This should fix the `Unexpected error reading from socket: 0, No error` error on Windows, which someone on IRC supposedly got 60000 times in 10 seconds. The issue was in
```C
int fail_or_len = recvfrom(sock, (char *) data, MAX_UDP_PACKET_SIZE, 0, (struct sockaddr *)&addr, &addrlen);
if (fail_or_len < 0 && errno != EWOULDBLOCK) {
LOGGER_ERROR(log, "Unexpected error reading from socket: %u, %s", errno, strerror(errno));
}
```
Because Windows doesn't use `errno` for error reporting, Windows was reporting  `EWOULDBLOCK` through `WSAGetLastError()` instead of `errno`, …
> Improve network error reporting on Windows

- other/travis/freebsd-install
FreeBSD build on Travis-CI has been failing lately:
```
+sudo apt-get install -y qemu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
qemu : Depends: qemu-system (>= 2.0.0+dfsg-2ubuntu1.36)
Depends: qemu-utils (>= 2.0.0+dfsg-2ubuntu1.36)
E: Unable to correct problems, you have held broken packages.
```
This probably has to do with the next following new message popping up:
```
Running apt-get update by …
```
> Fix FreeBSD build on Travis

- auto_tests/helpers.h
- toxcore/logger.c
Fixes #900.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/902)
> Log only the filename, not the full path in LOGGER.

- README.md
see https://github.com/TokTok/c-toxcore/pull/874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/877)
> Add minitox to under "Other resources" section in the README

- auto_tests/dht_test.c
By making it run in a port range far away from other tests. This test
creates 100 DHTs and makes either itself or other tests run out of ports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/914)
> Make dht_test more stable.

- auto_tests/TCP_test.c
This will be one of many modifications to the autotests to make their unit tests easier to read and more comprehensive. Obviously this pull request does not conclude the work on this unit test but I like to get a pull request in early to see if my style works for you.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/921)
> Beginnings of a TCP_test.c overhaul

- toxcore/net_crypto.c
- toxcore/net_crypto.h
It was a list of #defines, but clearly this is a discrete and limited set
of named values, so an enum is more appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/924)
> Make the net_crypto connection state an enum.

- auto_tests/TCP_test.c
Same thing as last time, another mild pull request as I go. A few better error messages, more logical sleep() call placements, comments, etc. For one of the test_basic functions I randomized the time between messages and the sizes in which portions of message are sent, for more coverage. 
Did not modify large chunk of the test_some function because I didn't understand the second half of it. Maybe I'll come back later once I've figured out what it's doing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/922)
> Clarify/Improve test_some test

- CMakeLists.txt
- testing/BUILD.bazel
- testing/random_testing.cc
This can be used as a random stress test for toxcore.
Adjust the weights to make certain actions more or less likely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/917)
> Add random testing program.

- auto_tests/TCP_test.c
The C compiler warns because the value is initialised in a loop and used
outside of it. In this case, it's always initialised, but changing the
value of `NUM_PORTS` can change that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/931)
> Avoid conditional-uninitialised warning for tcp test.

- auto_tests/invalid_proxy_test.c
- toxcore/Messenger.c
- toxcore/tox.api.h
- toxcore/tox.h
Currently, toxcore does not support UDP over proxies. In the future, we
can relax this by disabling UDP only if the proxy doesn't support it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/930)
> Disable UDP when proxy is enabled.

- CMakeLists.txt
- other/travis/env-linux.sh
- other/travis/toxcore-script
It's annoying to have a test touch every source file. It causes a
recompile of everything after every test run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/947)
> Remove the format test.

- toxencryptsave/Makefile.inc
These were deleted earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/950)
> Remove utils.c and utils.h from toxencryptsave build.

- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
Rename args `host:port` from `address:port`.
The *address* is well known as *Tox Address* in this project. Then we
should reserve *addres* to it, and use *host* to express the hostname or
IP address in TCP domain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/954)
> Proposal: Make arg `host` understand clearly.

- auto_tests/TCP_test.c
Mostly documentation + comments. Some cases where code was removed
in exchange for more compact/less sprawly for loops. Introduced a
function that removed like 30 lines of repeated code.
Edit: [I do not understand git and I do not understand why I am pring old commits.]()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/955)
> Another TCP_test upgrade

- toxcore/net_crypto.c
Current check allows to write one more packet than it should. Noticed this when implemented `net_crypto` module for [tox-rs](https://github.com/tox-rs/tox).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/943)
> Correct check for net_crypto packet index.

- CMakeLists.txt
- toxav/BUILD.bazel
- toxav/ring_buffer.h
- toxav/ring_buffer_test.cc
These can serve as documentation until we write actual api docs, probably
using apidsl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/964)
> Add some tests for our ring_buffer implementation.

- auto_tests/lan_discovery_test.c
- auto_tests/version_test.c
Another minor unit test PR. Big one coming up soon.
Removed a pointless declaration of a function in lan_discovery_test
and cleaned up the one error message there. Did an entire restructuring
of the version_test using macros that resulted in fewer lines of code but more
thorough testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/967)
>  lan_discovery_test and version_test cleanup

- toxav/groupav.c
- toxcore/group.c
- toxcore/group.h
We used to pass the actual peer numbers of peers leaving, but we no
longer know these in the PGC world, so we don't pass them anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/976)
> Call the "peer leaves" callback only once on group delete.

- toxav/groupav.c
Also use `net_pack_u16` in that function instead of manual ntohs+memcpy
and `net_unpack_u16` in its receiving counterpart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/977)
> Remove VLA usage from `send_audio_packet`.

- toxcore/onion.c
- toxcore/onion.h
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/onion_client.h
This is now a style rule: you can only use typedef'd function types.
Previous rules now applied in `onion_*.c`:
* `struct`s must have a name (typedef of unnamed struct is not allowed).
* `++i` for increment-stmt, not `i++`, e.g. in loops.
* Only a single declarator per struct member declaration.
* Type_Names vs. variable_names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/987)
> Use named types for onion callbacks.

- auto_tests/monolith_test.cc
- toxcore/Messenger.c
- toxcore/TCP_server.c
- toxcore/list.c
- toxcore/list.h
- toxcore/net_crypto.c
- toxcore/ping_array.c
`BS_LIST` would be a constant. `BS_List` is a type name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/978)
> Rename `BS_LIST` to `BS_List` to follow the naming conventions.

- .circleci/config.yml
- toxav/audio.c
Only in audio.c for now. This should be done everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/984)
> Avoid side-effectful assignments in conditionals.

- toxcore/friend_requests.c
- toxcore/friend_requests.h
Also:
* `#define` must be scoped. If it's used outside a scope, it must be
defined outside that scope (global `#define` does not need a matching
`#undef`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/990)
> Use named function types for friend_requests callbacks.

- toxcore/util.c
- toxcore/util.h
These are not used in a thread-safe way, but it opens the path towards
per-tox-instance time keeping and removal of some unsafe global state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/979)
> Add a thread-safe version of unix_time and friends.

- auto_tests/monolith_test.cc
- toxcore/DHT.c
- toxcore/DHT.h
* Removed `ARRAY_SIZE` and use NULL markers for end of array, instead.
The alternative is + size, but for these arrays, NULL markers made
sense, since they are arrays of non-null pointers.
* Made `INDEX_OF_PK` a self-contained macro, not dependent upon the
naming inside its call site. This is a minor change but makes the code
more local and reviews easier.
* No nested structs.
* Use only named function types ending in `_cb` for callbacks.
* Replaced two macros with functions.
* struct member names start with lowercase letters.
* It takes a bit of work to support `/**/` comments in preprocessor
macros, so I've decided not to support these. If a macro is complex
enough to need comments inside it, it's too complex. `//` comments are
allowed at the end of macro …
> Fix style in DHT.c.

- CMakeLists.txt
- auto_tests/file_transfer_test.c
- auto_tests/monolith_test.cc
- auto_tests/network_test.c
- toxav/BUILD.bazel
- toxav/Makefile.inc
- toxav/audio.h
- toxav/pair.h
- toxav/toxav.c
- toxav/video.h
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/crypto_core.c
- toxcore/logger.c
- toxcore/mono_time.c
- toxcore/network.c
- toxcore/network.h
- toxcore/util.c
- toxcore/util.h
* Moved PAIR to toxav, where it's used (but really this should die).
* Replace most MIN calls with typed `min_*` calls. Didn't replace the
ones where the desired semantics are unclear. Moved the MIN macro to
the one place where it's still used.
* Avoid assignments in `while` loops. Instead, factored out the loop body
into a separate `bool`-returning function.
* Use named types for callbacks (`_cb` types).
* Avoid assignments in `if` conditions.
* Removed `MAKE_REALLOC` and expanded its two calls. We can't have
templates in C, and this fake templating is ugly and hard to analyse
and debug (it expands on a single line).
* Moved epoll system include to the .c file, out of the .h file.
* Avoid assignments in expressions (`a = b = c;`).
* Avoid multiple declarators per struct member …
> Style fixes in TCP code; remove MIN and PAIR from util.h.

- .travis/cmake-linux
- CMakeLists.txt
- auto_tests/file_transfer_test.c
- auto_tests/monolith_test.cc
- auto_tests/network_test.c
- toxav/BUILD.bazel
- toxav/Makefile.inc
- toxav/audio.h
- toxav/pair.h
- toxav/toxav.c
- toxav/video.h
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/crypto_core.c
- toxcore/group.c
- toxcore/group.h
- toxcore/logger.c
- toxcore/mono_time.c
- toxcore/network.c
- toxcore/network.h
- toxcore/util.c
- toxcore/util.h
Also some other cleanups. This PR means that future PRs, i.e. the PGC PR,
must not break the rules established here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/998)
> Use named function types for group callbacks.

- toxcore/group.c
- toxcore/group.h
By changing numchats from uint32_t to uint16_t. This is done in PGC. This
PR is making that change in master to reduce the diff in the PGC branch.
Also:
* Inverted groupnumber_not_valid and renamed to is_groupnumber_valid.
* Renamed realloc_groupchats to realloc_conferences and made it return bool.
* Added setup_conference function that currently just zeroes the
conference structure but later will initialise more values.
* Made some `i` iterator variables local to the for-loop using
for-init-decl. This is also done in PGC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1000)
> Limit number of group chats to 65536.

- toxcore/group.c
- toxcore/group.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
These are useful once we have persistent group chats, so clients can
store data associated with this permanent group identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1001)
> Add conference_by_uid and conference_get_uid functions.

- .travis/flags.sh
- CMakeLists.txt
- toxcore/ccompat.h
These flags are needed so the code actually compiles, so can't only be
set on Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1006)
> Set C++11/C99 flag manually in older cmake on not-msvc.

- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1008)
> Set `_XOPEN_SOURCE` to 700 for FreeBSD.

- toxcore/tox.api.h
- toxcore/tox.h
256 bytes including NUL byte is confusing and makes for really annoying
bindings to other languages that don't account for NUL bytes in their
string length. We pass C strings, not byte arrays, for hostnames, so 255
makes more sense here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1012)
> Correct the max hostname length constant.

- auto_tests/conference_test.c
- auto_tests/conference_two_test.c
- auto_tests/crypto_test.c
- auto_tests/dht_test.c
Attempting to use fixed-sized integers as per #974. Only other changes were a todo comment and a functionally nonexistent modification to two for loops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1009)
> Using stdint instead of int/long

- toxcore/group.c
Also moved some macros up to the beginning of `group.c`. This change
brings us closer to the PGC PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1007)
> Use enums for group packet types.

- toxcore/net_crypto.c
Change LOGGER_ERROR to LOGGER_DEBUG for failed packet send in 
send_lossless_packet(), since the packet is added to the send queue anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1003)
> Remove LOGGER_ERROR for harmless send failure.

- CMakeLists.txt
- cmake/Dependencies.cmake
- toxcore/network.c
Also, added some #defines to make symbols visible that are in BSD but not
in UNIX. Solaris needs these, since it's fairly strict with its symbol
visibility in system headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1013)
> Link -lsocket and -lnsl for socket functions on Solaris.

- toxav/video.c
- toxcore/group.c
This almost entirely avoids any else-after-return in toxcore. One case is
left, and that one is more readable this way.
Why no else-after-return: https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return
Why exemptions exist: https://blog.mozilla.org/nnethercote/2009/08/31/no-else-after-return-considered-harmful/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1018)
> Reduce nesting by doing more early returns on error.

- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
`UID` sounds like `User ID`. While it is a Unique ID, the property of an
"identifier" is generally that it identifies a unique thing, so the 'U'
is redundant, and `GUID` as a globally unique id (which is likely also
true for these IDs) has a specific meaning and syntax, so we're not using
that. So, we just say conference `id`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1029)
> Add `by_id` and `get_id` functions, renaming from `*_uid`.

- auto_tests/Makefile.inc
Mosts of the tests in auto_tests weren't running when the project
was built using autotools. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1037)
> Update Autotools build

- toxcore/DHT.c
- toxcore/Messenger.c
All for-loops in toxcore are of the form
for (<for-init>; <for-cond>; <for-next>) { <body> }
`for-init` can be a variable declaration (like `int i = 0`), an
assignment (like `i = 0`), or empty.
`for-cond` can be any expression.
`for-next` can be an assignment or a single increment/decrement
expression (like `++i` or `--i`).
No other forms are allowed, so e.g. comma expressions in any of these are
not allowed (so no `for (i = 0, j = n; ...; ++i, --j)`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1041)
> Avoid multiple for-next expressions.

- other/analysis/gen-file.sh
- toxav/toxav.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
This allows Tox to contain additional data on top of Messenger, making
Messenger not necessarily the most top-level object. E.g. groups are
built on Messenger and currently awkwardly void-pointered into it to
pretend there is no cyclic dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1030)
> Make a separate `struct Tox` containing the Messenger.

- toxcore/Messenger.c
- toxcore/Messenger.h
The logger callback can only be set once at the beginning, because it
requires user data coming from `Tox_Options`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1047)
> Remove unused `m_callback_log` function.

- toxcore/DHT.c
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group.c
- toxcore/mono_time.c
- toxcore/mono_time.h
- toxcore/network.c
- toxcore/onion_client.c
Presumably the uses of `rand()` were fine because they were not used in
security-sensitive places, but having to think about whether a crappy RNG
is acceptable in each situation requires effort that could better be
spent elsewhere.
Also, this means that once we have a custom deterministic RNG for
testing, that RNG is used everywhere, so all the code is deterministic.
It also allowed us to delete a system-specific function that wasn't used
anywhere except in a call to `srand()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1039)
> Use the crypto random functions instead of `rand()`.

- toxcore/group.c
- toxcore/group.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1016)
> Split out conference type (text/av) from identifier.

- toxcore/tox.api.h
- toxcore/tox.h
The enumerators won't change, but the type name will change in 0.3.0.
Reasoning:
- Type names in toxcore start with an uppercase letter and either have at
least one lowercase letter in them, or are less than 4 characters long.
- Constants consist of 4 or more uppercase letters or underscores.
By these rules, "DHT" is a type name, but "TOX_USER_STATUS" is a
constant. We provide Tox_User_Status as an alternative for now, and will
switch to that in 0.3.0, removing the UPPER_CASE versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1036)
> Add deprecation notice to some UPPER_CASE enums.

- toxav/toxav.c
- toxcore/util.c
- toxcore/util.h
We use functions for this instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1067)
> Remove last use of the `MIN` macro.

- toxav/bwcontroller.c
- toxav/bwcontroller.h
* Comments in macros must be `//` style.
* No inner structs.
* Named callback types.
* No assignments as expressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1076)
> Fix style in bwcontroller module.

- toxav/audio.h
- toxav/video.h
Forward declarations are problematic, as they easily allow introducing
cyclic dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1072)
> Avoid forward declaration of rtp structs.

- toxav/msi.c
- toxav/msi.h
* Don't use anonymous enums (`typedef enum { ... } Name;`).
* Don't use macros to generate structs (too magical, hard to grep).
* Assign output parameter once, and don't access it a lot in the
function body.
* Don't pass type names as parameters to macros (this is C, we don't have
templates, sorry).
* All function-like macros must be do-while(0).
* No assignment-expressions.
* No void-casts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1078)
> Fix style in msi.c.

- toxav/rtp.c
- toxav/rtp.h
* Named callback types only.
* No anonymous enums or structs.
* Don't use enums to specify integer constants. Enums should be
enumerations. All values of an enum type should be listed[1].
[1] I don't know what to do about bit masks yet, but given that enums by
C standard can only go up to 32767 portably and 2^31 in reality, they are
probably not useful for 64 bit bit masks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1083)
> Fix coding style in rtp module.

- toxav/groupav.c
- toxav/groupav.h
- toxav/toxav_old.c
* No anonymous structs.
* No assignment expressions.
* Only one declarator per struct member declaration.
* Named callback types only, no inline types.
* No `;` empty statements.
Avoiding a cast in toxav_old.c avoids some potential (and real) bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1082)
> Fix groupav.c style and avoid casts in toxav_old.c.

- toxav/groupav.c
This probably doesn't happen, but it can in theory, so we avoid it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1080)
> Fix memory leak in error path in group A/V.

- auto_tests/conference_simple_test.c
- auto_tests/encryptsave_test.c
- auto_tests/file_transfer_test.c
- auto_tests/friend_request_test.c
- auto_tests/network_test.c
- auto_tests/save_load_test.c
- auto_tests/tox_many_tcp_test.c
- testing/av_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1049)
> Fix some printf format specifiers.

- .travis/cmake-linux
This checks that (some of) the code follows some simplicity and naming
guidelines set by the tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1053)
> Use tokstyle in the cmake travis build.

- toxav/video.c
* Constant-style macros can't be function call expressions. These must be
function calls themselves.
* Assignments can't be used as expressions.
* Therefore: `while` loops should not be used as a `for-each`
construct. Use `for`, instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1079)
> Fix style in video.c.

- toxcore/group.c
Somehow it still works because the lower levels can deal with
inconsistent/broken state, but this lets us avoid that broken state in
the first place. If a friend connection doesn't exist, we don't add it to
our group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1063)
> Avoid passing -1 as friend connection to new groups.

- .travis/bazel-linux
Instead of importing a well-known file. This gives toktok-stack more
freedom in where and how it wants to define its interface, as long as it
provides the configurations requested ("linux" and "clang").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1088)
> Use `--config` to tell bazel about the environment.

- toxav/toxav.api.h
- toxav/toxav.c
- toxav/toxav.h
* Use Camel_Snake_Case for type names.
* Use at least 4 characters for constant names. I.e. `END` is a type
name, but `RETURN` is a constant name. This is because `DHT` is a type
name (yay consistency).
* Using `min_*` functions instead of MIN, we can avoid a cast.
* Use `for`-loops for for-each-frame semantics instead of `while`.
* Don't use assignments as expressions.
* Function pointers are dereferenced automatically, so no need to
manually do so.
* Avoid void pointers that lie about not being spaghetti code. Toxcore
and toxav are both spaghetti and shouldn't pretend anything else.
* Don't use empty statements (e.g. no `;;` anywhere in the code).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix style in toxav.c.

- testing/Messenger_test.c
We should be careful on exit and remember to close files / free memory. Even in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1090)
> Fix possible resource leaks in test

- .travis.yml
- auto_tests/file_saving_test.c
- toxav/BUILD.bazel
Limited to 4GiB. That ought to be enough for any save file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1089)
> Limit the size of a save file in file_saving_test.

- auto_tests/TCP_test.c
- auto_tests/dht_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/DHT_test.c
- testing/Messenger_test.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/tox.c
Reduced by, e.g.:
* `file_transfer_test`: 33% of the `clock_gettime` calls.
* `tox_many_test`: 53% of the `clock_gettime` calls.
Other tests will see similar improvements. Real world applications will
be closer to 40-50% improvement, since tox_many_test has 100 nodes, while
file_transfer_test has 2 nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1057)
> Reduce the number of times `unix_time_update` is called.

- testing/misc_tools.c
It is invalid to compile an XPG3, XPG4, XPG4v2, or XPG5 application
using c99.  The same is true for POSIX.1-1990, POSIX.2-1992, POSIX.1b,
and POSIX.1c applications. Likewise, it is invalid to compile an XPG6
or a POSIX.1-2001 application with anything other than a c99 or later
compiler.  Therefore, Solaris libc forces an error in both cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1094)
> Set `_POSIX_C_SOURCE` to 200112L. We need it for C99 compat.

- other/fun/save-generator.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1099)
> Fix const cast in save-generator.

- auto_tests/save_compatibility_test.c
- other/analysis/run-clang
- other/fun/save-generator.c
- toxav/video.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1104)
> Avoid redefining macros from different files.

- .travis/bazel-linux
We check that:
* The license is GPLv3.
* .travis.yml conforms with the toktok style specification.
* There exists a README.md file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1097)
> Run project tests like yamllint_test.

- .travis/cmake-linux
Not only the second time it fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1107)
> Always print output on failure in cmake tests on Travis.

- CMakeLists.txt
We didn't install it before, only `tox-bootstrapd`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1092)
> Install the `DHT_bootstrap` binary on `make install`.

- toxcore/crypto_core_test.cc
So we don't accidentally elide the call given that it's a pure function
and its result isn't used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1061)
> Force storing the result of crypto_memcmp in the test.

- auto_tests/Makefile.inc
Specify correct sources, add missing test save_compatability_test, and make the 
list of tests easier to edit (one line per test, not repeated).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1112)
> Fix auto_tests Makefile

- auto_tests/toxav_basic_test.c
Turned a huge macro into a function. Macros are a pain to debug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1120)
> Stop using massive macros in `toxav_basic_test`.

- auto_tests/bootstrap_test.c
- auto_tests/conference_double_invite_test.c
- auto_tests/conference_peer_nick_test.c
- auto_tests/conference_simple_test.c
- auto_tests/conference_test.c
- auto_tests/dht_test.c
- auto_tests/file_transfer_test.c
- auto_tests/friend_request_test.c
- auto_tests/lan_discovery_test.c
- auto_tests/lossless_packet_test.c
- auto_tests/lossy_packet_test.c
- auto_tests/onion_test.c
- auto_tests/run_auto_test.h
- auto_tests/save_load_test.c
- auto_tests/send_message_test.c
- auto_tests/set_name_test.c
- auto_tests/set_status_message_test.c
- auto_tests/tcp_relay_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- auto_tests/typing_test.c
This forces all the loop bodies to be executed at least once, which is
harmless since it just means one more tox event loop iteration. This
reduces the jitter we see in coverage measurements, which is partially
caused by loops sometimes being entered and sometimes not (because their
condition happens to randomly already be true).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1119)
> Use do-while instead of while in tests.

- toxav/video.c
- toxcore/net_crypto.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1081)
> Change while-loop to for-loop to express for-each-frame.

- auto_tests/save_compatibility_test.c
`tox_new_log` has a much larger range of ports it can select from.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1124)
> Fix the `PORT_ALLOC` failure of `save_compatibility_test`.

- auto_tests/check_compat.h
This raises a signal, so we can more easily catch it with gdb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1129)
> Call `abort` instead of `exit` on test failure.

- CMakeLists.txt
- other/astyle/format-source
- testing/random_testing.cc
- toxcore/BUILD.bazel
- toxcore/crypto_core_test.cc
- toxcore/ping_array.api.h
- toxcore/ping_array.c
- toxcore/ping_array.h
- toxcore/ping_array_test.cc
No timeout test here yet, because we don't yet have the ability to
manipulate time at will, so we would have to actually sleep.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1128)
> Add some tests for `ping_array`.

- toxcore/mono_time_test.cc
Was: Util, should be: MonoTime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1130)
> Fix test class name for mono_time_test.

- other/astyle/format-source
- toxcore/crypto_core.c
Changes:
* 100 columns maximum (not strict, can be a bit more sometimes).
* No space after cast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1131)
> Format crypto_core.c.

- .circleci/cmake-asan
- .circleci/cmake-tsan
We'll make it non-required, but we want to know about these failures so
we are incentivised to fix them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1133)
> Make the tsan build fail instead of swallowing its errors.

- .travis.yml
- .travis/cmake-freebsd-stage1
Proper fix for https://github.com/TokTok/c-toxcore/pull/1071.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1075)
> Fix FreeBSD VM on Travis not shutting down

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/LAN_discovery.api.h
- toxcore/LAN_discovery.c
- toxcore/LAN_discovery.h
- toxcore/net_crypto.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
This inverts the truthiness of the return value. Previously, 0 meant
`true` and -1 meant `false`. Now, `true` (1) means `true` and `false` (0)
means `false`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1137)
> Make `ip_is_lan` return bool instead of 0/-1.

- testing/av_test.c
opencv2 is deprecated and homebrew ships with opencv3 now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1141)
> Include necessary opencv2 header on OSX.

- toxcore/DHT.c
- toxcore/DHT.h
Can't trivially get rid of recursion here, since it's a non-linear
recursive function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1140)
> Clean up `add_to_list` function a bit.

- toxcore/mono_time.c
The raw clock isn't subject to NTP adjustments. It may run less
accurately than the regular monotonic clock. I see no reason why raw
would be better for tox than the normal one.
This avoids one piece of OS-specific ifdef'd code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1136)
> Remove the use of `CLOCK_MONOTONIC_RAW`.

- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
A meanful logger for bootstrap. It outputs trace or debug log only.
* Build with default options, the bootstrap outputs nothing more.
* Build with `DEBUG=ON`, `tox-bootstrapd` outputs as,
```
Running "tox-bootstrapd" version 2016010100.
Successfully read:
...
General config read successfully
[DEBUG] /home/cotox/tox-stuff/c-toxcore/toxcore/network.c:959(new_networking_ex) Bound successfully to 0.0.0.0:33445
Set MOTD successfully.
Keys are managed successfully.
Initialized Tox TCP server successfully.
Successfully added bootstrap node #0: node.tox.biribiri.org:33445 F404ABAA1C99A9D37D61AB54898F56793E1DEF8BD46B1038B9D822E8460FAB67
List of bootstrap nodes read successfully.
Public Key: F5B0095E6C4AD95A3C1B87C452DF6427C3CB2D2A12135B9EBDDE1A979668811E
Initialized LAN discovery successfully. …
```
> Feature bootstrap trace/debug log output

- .travis/cmake-freebsd-stage1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1145)
> Fix login issue on Travis-CI FreeBSD build

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1134)
> Use `code font` for tool names and flags in INSTALL.md.

- super_donators/BUILD.bazel
- testing/av_test.c
- toxcore/DHT.c
- toxcore/tox.c
Also fix some warnings appearing under NDEBUG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1147)
> Ignore "unused-result" warning in super_donators code.

- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/state.c
- toxcore/state.h
I have wrote all the plugins for them and set them up. ~but it doesn't work yet, there is an issue with load and/or saving.~
It seems to be working now, it passes the tests and I've tested it with uTox.
Depends on  #1051.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1046)
> Finish the messenger state plugin system

- auto_tests/TCP_test.c
- auto_tests/dht_test.c
- auto_tests/onion_test.c
Because `()` means "some unknown number of parameters".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1150)
> Use `(void)` for empty parameter lists in C.

- toxav/msi.c
Narrowing down #1149.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1153)
> Always use the passed logger (from Messenger) in msi_kill.

- auto_tests/typing_test.c
Implements the run_auto_test fixture in typing_test.c to save lines of code because we need to think of the starving african programmers.
Also improves a few error messages to help developers discern where the assert failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1157)
> Use run_auto_test fixture in typing_test.c

- toxcore/Messenger.c
- toxcore/Messenger.h
Very small two line change, this bool/if statement was written in a very convoluted way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1165)
> Fixed a silly boolean practice using uint8_t

- auto_tests/conference_test.c
- toxcore/group.c
We were mistakenly not making a rejoin attempt on freezing connections due to 
all closest connections going down. This fixes that, and tweaks the test. I've 
still only done tens rather than hundreds of tests, but I'm fairly confident 
that the conference test now consistently passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1192)
> Send rejoin packets on conference disconnection

- toxav/toxav.c
Closes #1194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1195)
> Fix using uninitialized mutex on call end

- .circleci/cmake-asan
This runs in the same build as asan, so "asan" now stands for both asan
and ubsan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1196)
> Run UBSAN (undefined behaviour sanitizer) on Circle CI.

- .cirrus.yml
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
This CI can run Bazel tests, because it supports IPv6. This is nice,
because now we can run IPv6 tests on every PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1198)
> Add Cirrus CI configuration.

- toxcore/BUILD.bazel
See https://github.com/TokTok/toktok-stack/pull/38.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1197)
> Use new `@pthread` library from toktok-stack for Windows compat.

- toxcore/state.c
- toxcore/state.h
No use making this a macro. LTO will inline this anyway, if we care about
performance. Generally, we avoid function-like macros that can be functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1208)
> Remove a function-like macro and replace it with a function.

- auto_tests/network_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1224)
> Avoid use of IPv6 in tests if not supported (e.g. on Travis).

- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/TCP_server.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1216)
> Fix memleak in tcp server by wiping priority queues on deletion

- toxav/msi.c
- toxav/video.c
- unistd.h doesn't exist on MSVC.
- `vpx_codec_iface_t` is already `const`, so adding `const` qualifiers is
redundant and causes warnings on MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1209)
> Improve Windows compatibility of toxav code.

- other/astyle/format-source
- toxcore/LAN_discovery.h
So it gets regenerated when the .api.h file changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1206)
> Add LAN_discovery to the list of apidsl-generated files.

- auto_tests/save_load_test.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1215)
> Ensure save data unchanged after save and load

- other/DHT_bootstrap.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/misc_tools.c
- testing/misc_tools.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1231)
> Use `bool` for IPv6 flag in test programs and `DHT_bootstrap`.

- other/analysis/run-clang
- other/bootstrap_daemon/src/tox-bootstrapd.c
Useful for using memory analyzing tools.
Closes #1220
```bash
sed -i 's/DMIN_LOGGER_LEVEL/DMIN_LOGGER_LEVEL_IGNORE/' CMakeLists.txt
mkdir _build
cd _build
cmake -DBOOTSTRAP_DAEMON=ON \
-DBUILD_TOXAV=OFF \
-DENABLE_STATIC=ON \
-DENABLE_SHARED=OFF \
-DCMAKE_BUILD_TYPE=Debug \
..
make
cp ../other/bootstrap_daemon/tox-bootstrapd.conf .
sed -i "s|/var/lib/tox-bootstrapd|${PWD}|" tox-bootstrapd.conf
sed -i "s|/var/run/tox-bootstrapd|${PWD}|" tox-bootstrapd.conf
sed -i '/^bootstrap_nodes = /,$d' tox-bootstrapd.conf
python3 ../other/bootstrap_daemon/docker/get-nodes.py >> tox-bootstrapd.conf
valgrind --leak-check=full --show-leak-kinds=all \
./tox-bootstrapd --foreground --config tox-bootstrapd.conf
```
```
==13673== Memcheck, a memory error detector
==13673== Copyright (C) 2002-2017, and GNU …
```
> Make tox-bootstrapd free memory on SIGINT and SIGTERM

- CMakeLists.txt
We can now run `ctest --output-on-failure -D ExperimentalMemCheck -j 50`
to run valgrind on all tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1229)
> Include `CTest` in CMakeLists.txt to get valgrind support.

- toxcore/logger.c
- toxcore/logger.h
- toxcore/tox.c
These are not compiled out under `NDEBUG` and should be provably correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1230)
> Add `LOGGER_ASSERT` for checking fatal error conditions.

- auto_tests/messenger_test.c
- testing/Messenger_test.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/group.c
- toxcore/group.h
- toxcore/state.c
- toxcore/state.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1213)
> Make saving and loading the responsibility of Tox rather than Messenger

- .travis/cmake-freebsd-stage1
- .travis/tox-bootstrapd-docker
- other/bootstrap_daemon/README.md
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/bootstrap_daemon/tox-bootstrapd.service
- other/bootstrap_daemon/tox-bootstrapd.sh
tox-bootstrapd can use around 600 TCP sockets during TCP server's normal
functioning. Many systems default to having a soft limit of 1024 open file
descriptors, which we are close to reaching, so it was suggested we bump that
limit to a higher number. iphy suggested increasing it to 32768.
Related to the discussion at #1227.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1234)
>  Increase NOFILE limit for tox-bootstrapd

- toxcore/group.c
Closes #1269.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1271)
> Return TOX_ERR_CONFERENCE_SEND_MESSAGE_NO_CONNECTION if we are not connected to any peers

- auto_tests/conference_test.c
- docs/minpgc.md
- toxcore/Messenger.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group.c
- toxcore/group.h
- toxcore/state.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1156)
> conferences saving

- CMakeLists.txt
- INSTALL.md
- cmake/StrictAbi.cmake
Closes #1262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1278)
> Add cmake option for building additional tests

- auto_tests/encryptsave_test.c
- toxcore/crypto_core.c
Two instances of VLA usage in the encrypt/decrypt functions of crypto_core left users vulnerable to a stack overflow. Here is a patch and addition to the encryptsave test to make sure it doesn't reappear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1242)
> Fix critical stack overflow arising from VLA usage

- other/docker/windows/get_packages.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1281)
> Allow unauthenticated wine packages in the Windows build.

- toxav/groupav.c
- toxcore/group.c
- toxcore/group.h
- toxcore/state.c
- toxcore/state.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
(based on #1156)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1266)
> Expose offline conference peers in API

- cmake/StrictAbi.cmake
STRICT_ABI only breaks linkage if static libraries are not available,
because then we try to link against shared libraries with hidden symbols.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1289)
> Enable auto tests under STRICT_ABI if static libs are available.

- toxcore/group.c
(based on #1266)
* delete existing peers with same real_pk on adding a peer
* send freeze packet on quit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1267)
> Improve handling of peers entering and leaving conferences

- .travis/autotools-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1291)
> Use correct path to test log to cat on error.

- toxcore/group.c
Hopefully fixes #1285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1287)
> Avoid sending group messages to a peer before we have its group number

- toxcore/network.c
This code is undefined behaviour as is, and breaks on various platforms
requiring strict alignment (many microcontrollers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1293)
> Fix misaligned 4-byte access in trace logging.

- CMakeLists.txt
- auto_tests/Makefile.inc
- auto_tests/conference_av_test.c
- auto_tests/conference_test.c
- auto_tests/run_auto_test.h
- toxav/groupav.c
- toxav/groupav.h
- toxav/toxav.api.h
- toxav/toxav.h
- toxav/toxav_old.c
- toxcore/group.c
see #1303, #1304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1305)
> Expose api functions for enabling and disabling AV in AV groups

- .cirrus.yml
To make this reproducible. With floating versions (always latest), this
can break any time a new bazel version is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1314)
> Fix bazel build version at 0.22.0 for CI.

- auto_tests/tox_many_tcp_test.c
The test's intermittent failure may well be exposing a real bug in the
TCP relay and/or onion systems, but we can't find the bug, and keeping
the test is disrupting our CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1311)
> Disable failing TCP server test

- auto_tests/tox_many_tcp_test.c
This fixes an redefinition error when creating amalgamation.cc during
static analysis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1320)
> add undef guard in tox_many_tcp_test

- toxcore/DHT.c
It's a bug introduced in c-toxcore after assocs refactoring. See the original code: https://github.com/irungentoo/toxcore/blob/bf69b54f64003d160d759068f4816b2d9b2e1e21/toxcore/DHT.c#L1740-L1763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1310)
> Do not send the same packet to the same node twice

- auto_tests/conference_test.c
- toxcore/group.c
- toxcore/group.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
closes #1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1309)
> add configurable limit on number of stored frozen peers

- toxcore/group.c
This fixes a buffer overflow when a malformed *.tox save file is
loaded.
Again found with AFL and #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1334)
> fix missing group title length check

- toxcore/BUILD.bazel
- toxcore/mono_time.c
Since mono_time is accessed from the main thread as well as the toxav
thread it is needed to properly lock time updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1345)
> fix concurrency issues in mono_time

- toxcore/mono_time.c
I got an angry email from one of my Travis builds about Toxcore not building on Windows anymore.
https://ci.appveyor.com/project/iphydf/c-toxcore/builds/27267869?fullLog=true#L847
https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_mutex_destroy.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1347)
> Fix pthread_mutex_destroy getting too many arguments

- auto_tests/BUILD.bazel
Seems like this one works (from Cirrus CI):
```
//c-toxcore/auto_tests:lan_discovery_test FLAKY, failed in 1 out of 2 in 75.0s
Stats over 2 runs: max = 75.0s, min = 13.1s, avg = 44.0s, dev = 31.0s
```
Resolves #1354 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1358)
> Allow Bazel to rerun tests marked as flaky

- toxav/toxav.c
- toxav/video.c
- toxcore/Messenger.c
- toxcore/net_crypto.c
- toxcore/net_crypto.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1346)
> Fix most TSAN failures

- auto_tests/toxav_many_test.c
- toxav/toxav.api.h
- toxav/toxav.h
- toxcore/net_crypto.c
It seems that call control actions must be synchronized to `tox_iterate` in order to avoid some race conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1343)
> Fix TSAN failures in tests

- toxav/bwcontroller.c
- toxcore/LAN_discovery.c
- toxcore/network.c
The current code violates the C standard and causes crashes on strict
alignment architectures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1381)
> Use `net_pack` instead of casting bytes to ints.

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
We don't expose this to the user code, yet, because it would break the
API, but this is useful for future internal code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1383)
> Pass packet ID to custom packet handlers.

- BUILD.bazel
- auto_tests/BUILD.bazel
- other/BUILD.bazel
- other/bootstrap_daemon/BUILD.bazel
- other/fun/BUILD.bazel
- super_donators/BUILD.bazel
- testing/BUILD.bazel
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1387)
> Use rules_cc instead of native cc_library rules.

- toxav/toxav.c
- toxcore/Messenger.h
- toxcore/TCP_client.h
- toxcore/friend_connection.h
- toxcore/group.c
- toxcore/group.h
- toxcore/logger.h
- toxcore/tox.c
Most of our enums already have one. Some didn't. Tokstyle is going to
require commas at the end of enumerator lists in enum definitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1389)
> Standardise on having a comma at the end of enums.

- toxav/toxav.c
- toxav/toxav_old.c
- toxcore/network.c
In windows network code, we implement inet_pton and inet_ntop, which take
void pointers. We can do slightly better because we already know the type
when we call these functions, so we can avoid casting between void
pointer and the addr struct types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1390)
> Avoid casting back and forth between void-ptr.

- toxav/bwcontroller.c
- toxav/msi.c
- toxav/toxav.c
https://github.com/TokTok/hs-tokstyle/pull/43 implements a validation for
this. We should avoid locally declaring functions from another
translation unit, and instead use header files to export/import them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1395)
> Mark file-local function definitions as `static`.

- toxcore/network.c
Avoid any dynamic format strings, even ones like `cond ? "str1" : "str2"`.
See https://github.com/TokTok/hs-tokstyle/pull/45 for the corresponding validator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1397)
> Check that LOGGER macros are only called with string literals.

- toxav/audio.c
- toxav/bwcontroller.c
- toxav/msi.c
- toxav/toxav.c
We want functions declared as `static` to also be defined as `static`.
See https://github.com/TokTok/hs-tokstyle/pull/44 for the corresponding tokstyle check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1396)
> Make function defns match their decls regarding storage class.

- .cirrus.yml
code.tox.chat is down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1400)
> Disable bazel remote cache on CI.

- .cirrus.yml
We now check whether the cache application is reachable and running via
cURL. If it's running, we add the `--config=remote` line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1404)
> Smarter setup of bazel remote cache on Cirrus CI.

- testing/afl_toxsave.c
malloc.h doesn't exist on most platforms, and certainly not in stdc. No
functions from malloc.h are actually used here, and stdlib.h is enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1413)
> Make afl_toxsave.c a bit more portable; fix memory leak.

- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/toxav.c
We're actually still using it, but we got a private pointer now,
preparing us for having a private mono_time in toxav.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1416)
> Stop using Messenger's mono_time in bandwidth controller.

- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1418)
> Change ToxAVCall struct mutex to a more distinct name

- toxav/rtp.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/state.c
- toxcore/tox.c
See https://github.com/TokTok/hs-tokstyle/pull/49 for the corresponding
tokstyle analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1419)
> Remove newlines from the end of LOGGER format strings.

- toxcore/tox.api.h
- toxcore/tox.h
This adds complexity for very little value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1425)
> Stop using the "inline namespace" feature of apidsl.

- toxav/BUILD.bazel
- toxav/toxav.api.h
- toxav/toxav.h
- toxcore/BUILD.bazel
- toxcore/ccompat.h
- toxcore/crypto_core.api.h
- toxcore/crypto_core.h
- toxcore/crypto_core_mem.c
- toxcore/crypto_core_test.cc
- toxcore/ping_array.api.h
- toxcore/ping_array.h
- toxcore/tox.api.h
- toxcore/tox.h
- toxcore/tox_api.c
- toxencryptsave/crypto_pwhash_scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c
- toxencryptsave/defines.h
We put some tokstyle exemptions into the source files themselves,
instead. This way we can check some of the code in those files, and more
in the future when tokstyle supports more constructs (like apidsl).
Also: hacked ping_array.api.h to not emit `_array` as parameter names.
We'll need to fix apidsl to do this better. This works for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1426)
> Remove tokstyle exemptions from build files.

- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/Messenger.c
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_private.h
This is to prepare for ToxAV becoming independent of toxcore internal calls.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1424)
> Add new semi-private API functions to set per-packet-id custom handlers.

- .travis.yml
- auto_tests/BUILD.bazel
- auto_tests/Makefile.inc
- other/fun/BUILD.bazel
- toxcore/BUILD.bazel
This test was fixed by @robinlinden, but not enabled in all builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1435)
> Enable TCP relay test in Bazel and autotools build.

- auto_tests/save_compatibility_test.c
- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1434)
> Skip invalid TCP relays and DHT nodes when loading save data.

- .travis.yml
- .travis/tox-bootstrapd-docker
- cmake/ModulePackage.cmake
- other/bootstrap_daemon/README.md
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/get-nodes.py
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/fun/bootstrap_node_info.py
* Use fully static build for the bootstrap daemon.
* Store a sha256sum of the binary in the repo.
* Updated documentation for it.
* Add support for fully static build in cmake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1437)
> Rework the toxchat/bootstrap-node Docker image.

- toxcore/Messenger.c
If you have UINT32_MAX friends, then adding one more friend will cause an
overflow of the friend list (wrap to 0) and result in all friends being
deleted. This subsequently results in a null pointer dereference when
we're trying to add one friend to the deleted friend list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1456)
> Limit the number of friends you can have to ~4 billion.

- toxcore/crypto_core_mem.c
We need this for vanilla nacl builds on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1462)
> Include `<string.h>` for `explicit_bzero`.

- auto_tests/run_auto_test.h
- auto_tests/tox_one_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/docker/update-sha256
- toxav/ring_buffer_test.cc
- toxav/rtp_test.cc
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/crypto_core.c
- toxcore/crypto_core_mem.c
- toxcore/crypto_core_test.cc
- toxcore/ping.c
- toxcore/ping_array.c
- toxcore/ping_array_test.cc
- toxcore/tox.c
- toxcore/util_test.cc
* Use-after-free because we free network before dht in one case.
* Various unchecked allocs in tests (not so important) but also some in toxcore (a bit important).
* We used to not check whether ping arrays were actually allocated in DHT.
* `ping_kill` and `ping_array_kill` used to crash when passing NULL.
Also:
* Added an assert in all public API functions to ensure tox isn't NULL.
The error message you get from that is a bit nicer than "Segmentation
fault" when clients (or our tests) do things wrong.
* Decreased the sleep time in iterate_all_wait from 20ms to 5ms.
Everything seems to still work with 5ms, and this greatly decreases
the amount of time spent per test run, making oomer run much faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Fix errors on error paths found by oomer.

- .cirrus.yml
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
Use `bazel test //c-toxcore/... --build_tag_filters=-haskell` to run all
tests except the ones that depend on Haskell (i.e. cimple tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1436)
> Enable cimple tests by default but allow disabling them.

- toxcore/Makefile.inc
- toxencryptsave/Makefile.inc
This is working, so probably `NACL_LIBS` is entirely useless, but I
can't be bothered to figure out what this was supposed to be, so here we
are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1489)
> typo: `NAC_LIBS` -> `NACL_LIBS`.

- .restyled.yaml
Also limit clang-format to .cc files. Don't apply it to .c files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1495)
> chore: Exclude imported libsodium sources from restyled.

- toxcore/group_chats.c
Sanctions are not saved to the tox save file, so when a peer tried to re-create a dead group, others were not able to sync with them due to the inability to validate the sanctions credentials. Now in such a situation we simply don't send sanctions until a moderator or founder arrives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1507)
> fix: Fix a bug preventing non-founders from rebooting a dead group from save

- toxcore/group_connection.c
create_array_entry() needs to handle inbound handshake acks which are empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1509)
> fix:revert regression causing handshakes to sometimes fail

- other/analysis/gen-file.sh
- other/analysis/run-clang
- other/analysis/run-clang-analyze
- other/analysis/run-cppcheck
- other/analysis/run-gcc
- other/analysis/run-infer
- other/bootstrap_daemon/docker/update-sha256
These are more robust wrt. spaces in names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1497)
> refactor: Use bash arrays instead of strings for static analysis scripts.

- toxcore/group_connection.c
create_array_entry() needs to be able to handle empty received handshake ack packets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1525)
> fix:Revert regression

- toxcore/DHT.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
We now occasionally send our own IP info to a peer in a ping packet if we don't have a direct
connection established already. This fixes an issue where if two peers handshake via a
TCP connection, they would never be able to establish a direct connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1526)
> fix:Improve ability to establish direct UDP connections in groups

- toxcore/group_moderation.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1528)
> fix:Don't call memcpy on sanctions list if it's empty

- .circleci/cmake-asan
- .circleci/cmake-tsan
- .travis/autotools-linux
- .travis/cmake-freebsd-env.sh
- .travis/cmake-freebsd-stage1
- .travis/cmake-freebsd-stage2
- .travis/cmake-osx
- .travis/cmake-win32
- .travis/cmake-win64
- .travis/cmake-windows.sh
- .travis/flags-clang.sh
- .travis/flags-gcc.sh
- .travis/flags.sh
- .travis/tox-bootstrapd-docker
- .travis/upload-coverage
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1515)
> style: Run restyled on Travis and Circle CI scripts.

- toxcore/DHT.c
- toxcore/DHT.h
This function would sometimes return a close node's IP address instead of our own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1533)
> fix:Fix ipport_self_copy()

- toxcore/Messenger.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- Remove unused variable announced_node
- Fix bug causing self_join callback to be triggered when it shouldn't be (this also fixes a toxic bug where the peer join after a timeout doesn't always trigger) 
- Some renames and cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1536)
> fix:More small fixes

- auto_tests/group_message_test.c
- toxcore/group_announce.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
We now send each peer in a single packet instead of the entire
peer list in one big packet. This removes a theoretical hard
limit on the number of peers that can join a group and ensures
that the maximum packet size doesn't exceed the MTU of common
network media.                                                         
Some unnecessary syncing logic was removed. This will increase
the aggressiveness of syncing with more redundancy, but should
improve overall syncing speed.
Additionally, the ping packet now contains a checksum of the
public key hash of all confirmed peers instead of just the peer
count. This will ensure that sync requests will be made in
the case that all group peers have the same peer count, but a
different set of peers (i.e. group splits).
Finally - an unused 32-bit uint …
> fix:Refactor peer list syncing

- toxcore/group_chats.c
- toxcore/group_connection.h
This is to prevent packet request spam when we receive many out of order packets at once
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1543)
> fix: Ngc req throttle

- toxcore/group_chats.c
- toxcore/tox.api.h
- toxcore/tox.h
If we received the topic in a sync request the callback would give the client the peer id of the syncer rather than the peer who actually set the topic. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1544)
> fix: bug causing topic callback to sometimes give client the wrong peer id

- toxcore/group_chats.c
- toxcore/group_moderation.c
- toxcore/tox.api.h
- toxcore/tox.h
When the list is full it will attempt to remove an entry for an offline peer.
If all sanctioned peers are online an error will be returned and the situation
can be dealt with manually by the caller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1550)
> fix: Add sanctions list entry purging

- toxcore/group_chats.h
This allows us to change the max number of moderators without breaking
the save format. This should be a temporary fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1551)
> fix: Make save format moderator list a fixed size

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
We now flag peers that should be deleted and handle the event from the main loop.
In addition we now have exit types which are passed to clients via the API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1553)
> refactor: peer deletion

- toxcore/group_chats.c
- toxcore/group_connection.c
The problem: Peer A joins group and makes announcement. Peer A closes client. Peer B gets Peer A's stale announcement and attempts to handshake. Peer A opens client and tries to join the group (same public key). Peer B ignores Peer A's new announcement because he already has that public key in his peer list, and both peers' handshake attempts fail because they no longer have the same shared session key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1567)
> fix: bug sometimes preventing handshakes from taking place

- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group_chats.c
- toxcore/group_chats.h
We now periodically check that we're connected to at least one TCP relay, and
if not, we attempt to add relays. Previously we never checked our
connections with relays if the group state was connected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1568)
> fix: Make group TCP relay connections more robust

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1569)
> fix: Make sure clients get peer exit event

- toxcore/Messenger.c
- toxcore/group_announce.c
- toxcore/group_chats.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1570)
> fix: Make group announcements work without TCP requirement
