TokTok/c-toxcore

- README.md
@iphydf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/12)
> Fix readme for TokTok

- CMakeLists.txt
- other/travis/toxcore-after_script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/26)
> 6. Cmake bootstrapd

- auto_tests/tox_test.c
- other/apidsl/tox.in.h
- testing/nTox.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/45)
> Stateless friend status message

- auto_tests/tox_test.c
- other/apidsl/tox.in.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/54)
> Make typing change callback stateless

- other/astyle/format-source
- other/travis/toxcore-script
This is easier to use from a precommit hook, so it can be used to ensure that
all formatting is correct before committing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/53)
> Add format-source script.

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/55)
> docs(INSTALL.md): update instructions for Gentoo

- auto_tests/toxav_many_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/66)
> Fix plane size calculation in test

- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/network.c
- toxcore/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/79)
> Remove redundant `return` statements.

- toxcore/TCP_server.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/94)
> Rearrange fields to decrease size of structure

- toxcore/network.h
cc @isotoxin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/108)
> Prevent <winsock.h> inclusion by <windows.h>.

- CMakeLists.txt
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/68)
> Add address sanitizer option to cmake file.

- auto_tests/tox_test.c
Check to ensure that all 3 tox instances are up rather than
just one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/123)
> Use correct logical operator for tox_test

- .travis.yml
- CMakeLists.txt
- other/travis/env-osx.sh
- other/travis/env-windows.sh
- other/travis/toxcore-after_failure
- other/travis/toxcore-osx-install
- other/travis/toxcore-script
- other/travis/toxcore-windows-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxcore/77)
> Add OSX and Windows build to travis config.

- cmake/ModulePackage.cmake
- toxcore/tox.c
Group chats were changed and now need to be updated. This change got
lost in the merge.
> C++ the second round.

- INSTALL.md
@iphydf as requested on IRC, I have no idea about osx & cross-compiling stuff though.
> docs(INSTALL): update compiling instructions for Linux

- INSTALL.md
-tags/1.0.3 
+tags/1.0.11
Also expanded the @"Rpm Development Tools"  bit for clarity and sanity across the instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/206)
> Corrected libsodium tag

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/223)
> TravisCI shorten IRC message

- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/243)
> Enable address sanitizer on the cmake build.

- CMakeLists.txt
- testing/hstox/binary_decode.c
- testing/hstox/binary_encode.c
- testing/hstox/driver.c
- testing/hstox/methods.c
- testing/hstox/packet_kinds.c
This allows for easier development. It is not used on travis (yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/256)
> Add spectest to the cmake test suite.

- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
Fixes #205.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/271)
> Convert to and from network byte order in set/get nospam.

- toxav/toxav.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/284)
> Add NONE enumerator to bit mask.

- testing/hstox/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/286)
> Support float32 and float64 in msgpack type printer.

- toxav/bwcontroller.c
- toxav/rtp.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/301)
> rename messenger function, prepend m_

- auto_tests/tox_one_test.c
- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/314)
> Fix off by one error in saving our own status message.

- other/astyle/format-source
- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.h
Also, make sure this won't happen again by checking for it in
format-source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/326)
> Fix unresolved reference in toxencryptsave API docs.

- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/336)
> Correct TES docs to reflect how many bytes functions actually require.

- circle.yml
can't hurt
also circleCI has ssh access
and keeps the artifacts for download
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/369)
> Integrate with CircleCI to build artifacts in the future

- .gitignore
- CMakeLists.txt
- auto_tests/crypto_test.c
- toxcore/Makefile.inc
- toxcore/crypto_core.c
- toxcore/crypto_core_mem.c
Implementation mostly taken from libsodium utils.
Fix #347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/354)
> Add secure memcmp and memzero implementation.

- auto_tests/messenger_test.c
So we can see what went wrong if it fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/401)
> Add logging callback to messenger_test.

- other/travis/env-windows.sh
This way we can at least see what fails in which way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/400)
> Run windows tests but ignore their failures.

- auto_tests/crypto_test.c
- other/travis/autotools-linux-install
- other/travis/autotools-script
- toxencryptsave/toxencryptsave.c
Fixes #363.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/393)
> Set up autotools build to build against vanilla NaCl.

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/388)
> Fix logging condition for IPv6 client timestamp updates.

- other/travis/autotools-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/418)
> Clarify how the autotools build is done on Travis.

- other/travis/env-linux.sh
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/445)
> Make Travis tests slightly more robust by re-running them.

- other/travis/env-linux.sh
- other/travis/env-osx.sh
- other/travis/env-windows.sh
- other/travis/env.sh
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/446)
> Limit number of retries to 3.

- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/447)
> Release v0.1.5.

- auto_tests/TCP_test.c
- auto_tests/network_test.c
- auto_tests/resource_leak_test.c
- testing/dns3_test.c
- toxav/bwcontroller.c
- toxav/rtp.c
- toxav/toxav.c
- toxcore/LAN_discovery.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
First step to fix #124
Part of commits will be squashed, when code review finished
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/385)
> Add platform-independent Socket and IP implementation

- toxcore/Messenger.c
Found by chance by Nurupo when browsing the file. Doesn't affect anything, but might as well get rid of it...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/486)
> Remove empty line in Messenger.c

- testing/dns3_test.c
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
Fix #494
Fix #495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/497)
> Fix network

- appveyor.yml
See https://www.appveyor.com/docs/how-to/download-file/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/521)
> Fix appveyor script: install curl from chocolatey.

- CMakeLists.txt
- appveyor.yml
fixes #482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/483)
> Make BUILD_TOXAV an option and fail if dependencies are missing

- toxcore/list.c
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/510)
> Fix list malloc(0) bug

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/523)
> Release v0.1.7

- other/travis/autotools-script
- other/travis/toxcore-script
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/525)
> Retry autotools tests the same way as cmake tests.

- toxcore/tox.api.h
- toxcore/tox.h
Fixes #456.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/526)
> Add TOX_NOSPAM_SIZE to the public API.

- circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/488)
> Save compiled Android artifacts after CircleCI builds.

- toxcore/TCP_client.h
- toxcore/network.c
I'm not sure if this will really fix that, so take it as a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/537)
> Fix TokTok/c-toxcore#535

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/536)
> Release v0.1.8

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/539)
> Make OSX test failures fail the Travis CI build.

- CMakeLists.txt
- other/travis/hstox-install
- testing/hstox/binary_decode.c
- testing/hstox/binary_encode.c
- testing/hstox/driver.c
- testing/hstox/driver.h
- testing/hstox/fuzz_main.c
- testing/hstox/test_main.c
- testing/hstox/util.h
The new encoding is `0` for `Nothing` and `[1, x]` for `Just x`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/449)
> Use new encoding of `Maybe` in msgpack results.

- CMakeLists.txt
- other/version-sync
- testing/hstox/byteswap.h
- testing/hstox/driver.c
- testing/hstox/util.h
Also some minor reformatting and fixes to the hstox sut driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/552)
> Fix formatting and spelling in version-sync script.

- CMakeLists.txt
- cmake/StrictAbi.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/553)
> Factor out strict_abi cmake code into a separate module.

- auto_tests/selfname_change_conference_test.c
Found by cppcheck.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/561)
> Remove unused variable

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/563)
> Release v0.1.9

- INSTALL.md
- docs/TCP_Network.txt
- docs/av_api.md
- docs/updates/Crypto.md
by @dartraiden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/598)
> Fix typos in docs

- other/travis/toxcore-osx-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/605)
> Fix OS X Travis.

- auto_tests/conference_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
- auto_tests/tox_one_test.c
- auto_tests/tox_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/587)
> Fix tox test

- testing/hstox/byteswap.h
- testing/hstox/driver.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/648)
> Make hstox compile on FreeBSD

- CMakeLists.txt
- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/652)
> Add support for building the monolith test on android.

- CHANGELOG.md
- auto_tests/conference_test.c
- cmake/ModulePackage.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/666)
> Fix some typos in code and cmake comments

- toxav/rtp.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/665)
> Remove useless if statement

- CMakeLists.txt
- other/pkgconfig/toxcore.pc.in
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/ping.c
- toxcore/ping_array.api.h
- toxcore/ping_array.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/668)
> Make Ping_Array a module-private type.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/616)
> Add projects link to Readme.

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/friend_requests.c
- toxcore/friend_requests.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/670)
> Make Friend_Requests a module-private type.

- auto_tests/onion_test.c
- toxcore/friend_connection.c
- toxcore/onion_client.c
- toxcore/onion_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/669)
> Make Onion_Client a module-private type.

- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/672)
> Make Friend_Connections a module-private type.

- toxcore/TCP_server.c
- toxcore/TCP_server.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/673)
> Move TCP_Secure_Connection from .h to .c file.

- toxav/rtp.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/crypto_core.api.h
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/net_crypto.c
- toxcore/ping_array.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/684)
> Add random_u16 function and rename the others to match.

- toxcore/DHT.c
- toxcore/DHT.h
These will be needed for new group chats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/677)
> Make pack/unpack_ip_port public DHT functions.

- CMakeLists.txt
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/DHT.c
- toxcore/LAN_discovery.api.h
- toxcore/LAN_discovery.c
- toxcore/friend_connection.c
- toxcore/net_crypto.c
- toxcore/network.h
- toxcore/onion_announce.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/687)
> Use apidsl to generate LAN_discovery.h.

- cmake/Dependencies.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/693)
> Make libcheck optional for windows builds.

- auto_tests/BUILD
- auto_tests/file_saving_test.c
- toxav/BUILD
- toxcore/BUILD
- toxencryptsave/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/697)
> Use C99 standard in bazel builds.

- toxav/bwcontroller.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/700)
> Use more descriptive names in bwcontroller.

- toxav/audio.c
By @zoff99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/699)
> Add some explanatory comments to the toxav audio code.

- circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/701)
> Add astyle to Circle CI build.

- circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/702)
> Update to astyle 2.04 on CircleCI to get the correct result

- auto_tests/simple_conference_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/707)
> Fix log message in simple_conference_test: invite -> message.

- toxcore/tox.c
Fix #704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/705)
> Add correction support for conference

- testing/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/708)
> Add testing/*.c (except av_test) to bazel build.

- other/BUILD
- other/bootstrap_daemon/BUILD
- other/fun/BUILD
- super_donators/BUILD
- testing/BUILD
- testing/av_test.c
- toxav/BUILD
Also, fix av_test.c, since I broke it last time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/713)
> Add BUILD files for all the little tools in the repo.

- circle.yml
- toxav/audio.c
- toxav/audio.h
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/groupav.h
- toxav/ring_buffer.c
- toxav/ring_buffer.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
- toxav/video.c
- toxav/video.h
- toxcore/LAN_discovery.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/712)
> Fix high quality video sending (backport to 0.1.x).

- other/bootstrap_daemon/BUILD
- testing/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/722)
> Use self-built portaudio instead of system-provided.

- toxav/rtp.c
- toxav/rtp.h
These are the names used in the next PR, in RTPHeaderV3, so here we
rename the old struct members already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/727)
> WIP #1: Rename some rtp header struct members to be clearer.

- auto_tests/conference_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/742)
> Improve conference test stability.

- toxav/BUILD.bazel
- toxav/rtp.c
- toxav/rtp.h
- toxav/rtp_test.cpp
- toxcore/BUILD.bazel
- toxcore/crypto_core.api.h
- toxcore/crypto_core.h
- toxcore/network.c
- toxcore/network.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/721)
> Manually serialise RTPHeader struct instead of memcpy.

- other/travis/toxcore-linux-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/761)
> use official debian domain

- auto_tests/monolith_test.cpp
- other/astyle/format-source
- toxav/rtp_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/756)
> Format .cpp files with format-source.

- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/util.h
- toxcore/util_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/755)
> Add some unit tests for util.h.

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/770)
> Add MSVC compilation instructions

- INSTALL.md
- appveyor.yml
- cmake/Dependencies.cmake
- third_party/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/775)
> Look for dependencies in third_party/

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/779)
> Remove leftover symmetric key from DHT struct.

- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/783)
> Send 0 as peer number in CHANGE_OCCURRED group event.

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/friend_connection.c
- toxcore/friend_requests.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/782)
> Use `const` more in C code.

- auto_tests/helpers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/788)
> Don't print trace level logging in tests.

- auto_tests/file_transfer_test.c
- auto_tests/helpers.h
- auto_tests/resource_leak_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_one_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/792)
> Increase range of ports available to Toxes during tests

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/803)
> Fix the windows build: pthread needs to be linked after vpx.

- other/astyle/format-source
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/804)
> Fix OSX tests: find(1) doesn't work like on Linux.

- CMakeLists.txt
- cmake/ModulePackage.cmake
It's missing vpx and opus at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/806)
> Fix toxcore.pc generation.

- toxcore/TCP_connection.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/813)
> Minor cleanups: dead stores and avoiding complex macros.

- toxcore/Messenger.c
- toxcore/net_crypto.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/util.c
DETECTED=cppcheck
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/815)
> Some minor cleanups suggested by cppcheck.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/818)
> Change README to talk about cmake instead of autoreconf.

- auto_tests/selfname_change_conference_test.c
- auto_tests/simple_conference_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/820)
> Fix auto_tests to stop using the deprecated conference API.

- auto_tests/monolith_test.cpp
- auto_tests/selfname_change_conference_test.c
- auto_tests/simple_conference_test.c
- toxcore/group.c
- toxcore/group.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/821)
> Remove deprecated conference namelist change callback.

- auto_tests/file_transfer_test.c
- toxcore/Messenger.c
By increasing a magic number.. Also, added more verbose logging to the
file transfer test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/828)
> Make file transfers 50% faster.

- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/837)
> Update version to 0.2.1.

- auto_tests/dht_test.c
- auto_tests/file_saving_test.c
- auto_tests/messenger_test.c
- auto_tests/onion_test.c
- auto_tests/simple_conference_test.c
- auto_tests/toxav_many_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/fun/cracker.c
- other/fun/sign.c
- other/fun/strkey.c
- testing/DHT_test.c
- testing/Messenger_test.c
- testing/misc_tools.c
- toxav/bwcontroller.c
- toxav/rtp.c
- toxcore/network.c
It's not supported in mingw.
See https://github.com/TokTok/c-toxcore/issues/786.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/809)
> Remove the use of the 'hh' format specifier.

- testing/DHT_test.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/797)
> Move struct DHT_Friend into DHT.c.

- auto_tests/onion_test.c
Makes debugging easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/801)
> Add logging to the onion_test.

- CMakeLists.txt
- toxcore/ccompat.h
Fixes #881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/883)
> Make toxcore compile on BSD

- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
@iphydf This is the fix of PR #892.
PS, #892 didn't fix the crash issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/893)
> Fix bootstrap crashes, still

- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/894)
> Fix logging related crash in bootstrap node

- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/897)
> Fix ipport_isset: port 0 is not a valid port.

- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/899)
> Fix macOS macro because of GNU Mach

- toxcore/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/906)
> Sort bazel build file according to buildifier standard.

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/913)
> Minor cleanup: return early on error condition.

- toxav/audio.c
- toxav/audio.h
- toxav/groupav.c
- toxav/groupav.h
- toxav/msi.c
- toxav/msi.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/video.c
- toxav/video.h
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/network.c
- toxcore/network.h
- toxcore/util.c
- toxcore/util.h
In preparation for adding log statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/933)
> Add Logger to various net_crypto functions, and add `const` to Logger where possible.

- toxcore/tox.api.h
- toxcore/tox.h
- toxcore/tox_api.c
Fixes #946.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/948)
> Add a MAX_HOSTNAME_LENGTH constant.

- other/travis/toxcore-script
- toxencryptsave/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/951)
> Only run astyle if the astyle binary exists.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/952)
> Release v0.2.3

- toxcore/tox.api.h
- toxcore/tox.h
Added missing API description of add_tcp_relay().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/953)
> Add missing MAX_HOSTNAME_LENGTH doc.

- auto_tests/dht_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/958)
> Fix leak of Logger instances in dht_test.

- testing/random_testing.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/965)
> Add `#include <cstdio>` for `std::printf`.

- .travis/cmake-linux
- .travis/cmake-osx
- auto_tests/conference_double_invite_test.c
- auto_tests/friend_connection_test.c
- auto_tests/overflow_recvq_test.c
- auto_tests/overflow_sendq_test.c
- auto_tests/run_auto_test.h
- auto_tests/send_message_test.c
Most of the auto-tests should use this fixture, but I've only done a few
to set an example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/966)
> Use run_auto_test.h test fixture for some auto-tests.

- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/985)
> Clarify the intent of "file kinds" in the API.

- .travis.yml
- .travis/bazel-linux
PR-blocking, not nightly, because the bazel build is the only one that performs a layering check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/996)
> Add the bazel build as one of the PR blocking builds.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1005)
> Use the correct repository name in the coverage badge.

- configure.ac
.. to compare strings. `==` is for numeric values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1014)
> Use string comparison operator in configure.ac.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1024)
> Release v0.2.4

- auto_tests/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1023)
> Run buildifier on c-toxcore BUILD files.

- auto_tests/dht_test.c
astyle doesn't catch all of these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1017)
> Add missing braces in dht_test.c.

- toxcore/list.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1022)
> Make `resize` in `list.c` return bool instead of 0/1.

- toxav/bwcontroller.h
- toxcore/Messenger.h
- toxcore/TCP_client.h
- toxcore/network.h
- toxcore/onion_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1019)
> Synchronise parameter names in headers with those in the implementation.

- auto_tests/dht_test.c
- toxav/toxav.c
- toxav/video.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1020)
> Add github usernames to TODOs.

- auto_tests/messenger_test.c
- toxav/msi.c
- toxav/video.c
Also removed an unused identifier in messenger_test.c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1021)
> Remove redundant casts to the same type.

- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1048)
> Fix error message in m_send_generic_message

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1054)
> Release 0.2.5

- CMakeLists.txt
- toxav/BUILD.bazel
- toxav/Makefile.inc
- toxav/audio.c
- toxav/audio.h
- toxav/pair.h
- toxav/toxav.c
- toxav/video.c
- toxav/video.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1066)
> Remove all uses of the PAIR macro in toxav.

- auto_tests/file_saving_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1062)
> Check that the save file size isn't larger than our address space.

- auto_tests/conference_double_invite_test.c
- auto_tests/conference_simple_test.c
- other/analysis/gen-file.sh
- other/bootstrap_daemon/src/command_line_arguments.c
- other/bootstrap_daemon/src/log.h
- other/bootstrap_daemon/src/log_backend_stdout.h
- other/bootstrap_daemon/src/log_backend_syslog.c
- other/bootstrap_daemon/src/log_backend_syslog.h
- testing/DHT_test.c
- testing/Messenger_test.c
Also remove the use of a VLA in a context where there can be unbounded
memory allocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1068)
> Fix a few warnings from clang.

- .travis.yml
This avoids its dependency on FreeBSD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1074)
> Move OSX to stage 1 of Travis.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1071)
> Temporarily disable FreeBSD build, since it times out.

- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1060)
> Avoid implicit conversion of negative value to uint32_t.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1093)
> Release 0.2.6

- .circleci/cmake-asan
- .circleci/cmake-tsan
- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1098)
> Run both asan and tsan on Circle CI.

- .travis/upload-coverage
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1103)
> Upload coverage to codecov as well as coveralls.

- testing/Makefile.inc
- testing/misc_tools.c
Sorry for the bug...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1106)
> Fix libmisc_tools building

- .circleci/cmake-asan
- .circleci/cmake-tsan
See https://github.com/ninja-build/ninja/issues/814
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1102)
> Enable color diagnostics on circleci.

- auto_tests/save_compatibility_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1110)
> Add check to make sure tox was created successfully

- toxcore/group.c
This hopefully fixes #1114.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1117)
> Fix leave callback calling in del_groupchat

- auto_tests/Makefile.inc
- auto_tests/save_compatibility_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1125)
> Run save_compatibility_test in the autotools build.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1142)
> Release 0.2.7

- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1151)
> Fix typo: tcp_replays -> tcp_relays.

- toxcore/tox.c
Possibly this is what's happening in #1149.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1154)
> Assert that we don't kill tox before killing toxav.

- toxav/rtp_test.cc
- toxcore/mono_time_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1158)
> Use C++ style casts in C++ code.

- .travis/bazel-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1161)
> Use most recent version of Bazel (0.17.1).

- .circleci/config.yml
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1164)
> Format yaml files according to yamllint's requirements and remove branch filter for appveyor.

- .travis/bazel-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1188)
> Fix yamllint test (it's gone from bazel, add a new one).

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1199)
> Run tests on Appveyor (Windows native build).

- toxcore/onion_client.c
This resets friend search rate in two circumstances where it should be
reset:
* when the friend gets a dhtpk packet to us;
* when a friend connection to the friend goes down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1202)
> Combine last_reported_announced with last_seen in Onion_Friend

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1225)
> Release 0.2.8

- .travis/bazel-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1272)
> Upgrade bazel to 0.19.0 to fix the bazel build.

- toxcore/network.c
- toxcore/onion_client.c
- toxcore/util.c
- toxcore/util.h
Also, use them in the `onion_client` module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1295)
> Implement all min/max functions for (un)signed int types.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1283)
> Release 0.2.9

- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1302)
> Specify that buffer size for tox_conference_peer_get_name is given by $size

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1324)
> Release 0.2.10

- toxcore/group.c
It's possible that 8e2281ee fixes #961, but not very likely.
Based on #1309 (ad2b30d3).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1321)
> Some small fixes to groups.

- INSTALL.md
- appveyor.yml
- other/docker/windows/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1329)
> bump libsodium version in appveyor.yml

- .gitignore
Add one more IDE to the list of ignored folders.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1299)
> Add VScode folder to .gitignore

- toxcore/group.c
Should fix #961, at least in its most likely incarnations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1362)
> Workaround for message number saving

- .travis/cmake-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1371)
> Bump to astyle-3.1 in travis build.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1380)
> Disable FreeBSD travis build until it is fixed.

- .travis.yml
- .travis/cmake-linux
This way we can check that building with Ninja works, in addition to "make". We test "make" on Circle CI, so we test Ninja on Travis CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1378)
> Use ninja build system for the cmake-linux build.

- .cirrus.yml
- .travis.yml
- .travis/bazel-linux
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1382)
> Add a mutex lock/unlock inside every public API function.

- .travis/cmake-linux
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- toxcore/DHT.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1370)
> use -1 rather than ~0 in unsigned integer types

- toxav/groupav.h
- toxcore/group.c
- toxcore/group.h
- toxcore/onion_client.h
- toxcore/tox.api.h
- toxcore/tox.h
Should be essentially a pure refactoring.
Based on #1321 (a7b93015)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1322)
> Clean-up of group.c code

- .cirrus.yml
- .travis/bazel-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1394)
> Enable remote cache for bazel builds.

- toxcore/group.c
This may fix problems with very large conferences. Sadly, it seems 
infeasible to test large conferences on one machine, so this is entirely 
theoretical.
Based on #1322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1392)
> Clear out old conference connections.

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1399)
> Periodically try to send direct packets when connected by TCP.

- toxcore/DHT.c
This function exists and simplifies some code a little bit. There are
lots of places in DHT.c where we have the exact same code, so there is a
lot of opportunity to factor out common bits. For now, we just make a
minor improvement that's easy to review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1398)
> Minor cleanup: use `assoc_timeout` function where possible.

- toxcore/network.c
Remove useless parameter, replace with assert (just to be sure). Also
replaced some memsets with 0-initialiser and memcpy with assignment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1391)
> Minor cleanups in network code.

- .travis.yml
- .travis/cmake-linux
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1403)
> Install libsodium from apt instead of from source.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1405)
> Release 0.2.11

- auto_tests/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1411)
> Fixes towards building on MSVC.

- INSTALL.md
- other/fun/BUILD.bazel
- other/fun/minimal-save-generator.c
Have written this long ago, iphy said it sounds useful to add
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1407)
> Add minimal save generator

- other/astyle/format-source
- toxcore/tox.api.h
This one is unfortunately a little more complicated to use. I may add a
simpler API later, but for now, it's JSON-based (because I couldn't get
binary data to work without it getting mangled somewhere along the way -
JSON is at least text-transport-safe).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1406)
> Migrate format-source script to new apidsl web app.

- .circleci/cmake-asan
- .circleci/cmake-tsan
- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1414)
> Show function names in asan/tsan stack traces on CircleCI.

- toxav/audio.c
- toxav/video.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1415)
> Fix 2 memory leaks in ToxAV.

- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1417)
> Create own instance of Mono_Time for ToxAV

- toxav/BUILD.bazel
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1420)
> Use public API for sending in BWC

- .travis/cmake-linux
- other/astyle/format-source
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1421)
> Install ci-tools and get tokstyle via the script it provides.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1423)
> Give CI workflow a better name: clang-sanitizers

- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1422)
> Use public API for sending in RTP

- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1433)
> Fix saving of combination of loaded and connected TCP relays

- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/net_crypto.c
Also changed their return type to bool instead of 1/0 ints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1430)
> Invert `not_valid` functions and name them `is_valid`.

- .github/release-drafter.yml
- codecov.yml
See https://github.com/release-drafter/release-drafter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1444)
> Set up release-drafter to automatically draft the next release.

- .github/settings.yml
- codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1443)
> Allow test coverage to fluctuate 2% up and down, but not below 80%.

- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1451)
> Fix formatting.

- docs/DHT-Group-Chats.md
This fixes the markdown and removes all mention of bans.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1453)
> Fix groupchat docs

- CMakeLists.txt
- testing/BUILD.bazel
- testing/trace.cc
Use `cmake -DEXECUTION_TRACE=ON` to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1452)
> Add execution trace option for debugging.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1458)
> Release 0.2.12

- other/analysis/gen-file.sh
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/cpufeatures.c
- testing/DHT_test.c
- toxcore/LAN_discovery.api.h
- toxcore/LAN_discovery.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/crypto_core.c
- toxcore/group.c
- toxcore/group.h
- toxcore/list.c
- toxcore/list.h
- toxencryptsave/crypto_pwhash_scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c
This check puts all of our code in a C++ anonymous namespace, which is
effectively making all functions `static`. This allows the compiler to
determine that a function is unused, so we can delete it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1463)
> Add a check that we don't have any unused functions.

- toxcore/group_announce.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1468)
> Add missing null pointer check

- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1469)
> Never send null data in groupchat lossless UDP

- toxcore/Messenger.c
- toxcore/group_announce.c
- toxcore/group_announce.h
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
- toxcore/onion_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1470)
> Clean up and improve group define/function names

- .restyled.yaml
- auto_tests/TCP_test.c
- auto_tests/conference_invite_merge_test.c
- auto_tests/conference_peer_nick_test.c
- auto_tests/conference_test.c
- auto_tests/encryptsave_test.c
- auto_tests/file_saving_test.c
- other/astyle/format-source
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/toxav.c
- toxcore/DHT.c
Also added a bunch of asserts to tests where they don't check allocs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1467)
> Fix a bug in savedata loading when malloc fails.

- .restyled.yaml
- .travis.yml
- .travis/cmake-linux
- other/analysis/check_recursion
- other/astyle/format-source
- other/docker/Dockerfile.ci
- other/docker/run-ci
This isn't quite Travis, but close enough for local testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1473)
> Add a script to run Travis CI locally.

- toxcore/group_chats.c
- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1484)
> Make sure data is not null before re-sending a group message ack

- .cirrus.yml
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group_chats.c
- toxcore/onion_client.c
- toxcore/onion_client.h
Added accessors where needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1490)
> Move structs back into the .c files, making them private.

- auto_tests/TCP_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/net_crypto.c
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1493)
> Add logging to TCP and onion client.

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1500)
> Fix some group connection issues

- auto_tests/TCP_test.c
- auto_tests/onion_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1496)
> Stop hard-coding packet IDs in tests.

- .github/settings.yml
- toxcore/TCP_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1498)
> refactor: Limit scope of loop iterators.

- .github/release-drafter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1504)
> chore: Remove release-drafter configuration in favour of global one.

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_moderation.c
Most of these will be removed eventually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1508)
> cleanup:improve group debugging messages

- toxcore/group_chats.c
- toxcore/group_connection.c
Also more debugging messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1511)
> fix:make sure we immediately request a packet re-send if handler fails

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1510)
> chore: Don't build pushes to branches, only to tags.

- other/fun/bootstrap_node_info.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1516)
> cleanup: Make pylint and mypy happy with bootstrap_node_info.py.

- toxcore/group_chats.c
- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1522)
> fix:Fix a bug in the group lossless implementation

- toxcore/group_chats.c
These functions only need to be called once before the loop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1529)
> fix:Remove a bunch of redundant calls to ipport_isset() and pack_ip_port()

- toxcore/Messenger.c
- toxcore/group_announce.c
- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_moderation.c
We no longer allow multiple declarators per declaration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1530)
> style: Make group code compliant with the latest tokstyle.

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_moderation.c
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1531)
> cleanup:Improve groupchat logging

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1534)
> fix:Fix bug sometimes preventing peers from receiving tcp nodes and refactor pings

- toxcore/group_chats.c
Also removed some unnecessary calls to set_peers_checksum() (already called in peer_add())
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1540)
> fix:Attempt to fix a group handshake bug

- toxcore/group_announce.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
- toxcore/group_moderation.c
- toxcore/group_moderation.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1542)
> cleanup: Lots of groupchat code cleanup

- toxcore/group_chats.c
- toxcore/group_chats.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1545)
> refactor: A better way to get unique peer ID's

- toxcore/group_announce.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
- toxcore/group_moderation.c
- toxcore/group_moderation.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1547)
> cleanup: More code cleanup

- toxcore/group_chats.c
- toxcore/group_chats.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1548)
> fix: Try to limit unnecessary sync request spam

- toxcore/group_chats.c
TCP connections need to be severed before we attempt to re-add a
peer, and peers need to be deleted if they give us incorrect sync info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1555)
> fix: handling sync errors and reconnections

- toxcore/group_chats.c
- toxcore/group_connection.c
Also add some extra checks to make sure we can't send/recv packets from
peers that are pending deletion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1560)
> fix: Put gcc_check_received_array() in main loop to remove possible recursion

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1565)
> fix: a few more group handshake bugs

- toxcore/group_chats.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1566)
> fix: Remove unnecessary 4 byte field from handshake packet

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1573)
> fix: bug preventing tcp relays from being saved

- auto_tests/group_moderation_test.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1577)
> fix: group exit type enum style: Foo_Bar -> FOO_BAR

- toxcore/group_announce.c
- toxcore/group_announce.h
- toxcore/group_chats.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1578)
> cleanup: More groupchat code cleanup

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1583)
> fix: bug preventing tcp connections from being initiated with initial peer

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1588)
> Fix: rejoin spam on handshake and remove unused function

- toxcore/group_chats.c
This usually happens when a peer reconnects and no longer has the same shared
session key, or when we get a stale announcement. In the rare case that
this occurs due to packet corruption they will still be able to
reconnect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1592)
> Fix: Delete peers who send packets that we cannot decrypt

- toxcore/group_chats.c
- toxcore/group_chats.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1594)
> fix: Reset self announce timer even if we don't announce

- auto_tests/group_announce_test.c
- auto_tests/group_message_test.c
- auto_tests/group_moderation_test.c
- auto_tests/group_state_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1600)
> cleanup: Some fixes and improvements to group autotests

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1605)
> fix: possible null dereference and fix some variable name issues

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1608)
> feat: Fix and complete group manual disconnect functionality

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.api.h
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1612)
> cleanup: Remove useless function and improve reconnect API error handling

- docs/DHT-Group-Chats.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1613)
> docs: Update groupchat docs

- auto_tests/onion_test.c
- toxcore/network.h
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1616)
> chore: Add backwards compatibility code for onion

- auto_tests/onion_test.c
- toxcore/network.h
- toxcore/onion.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1619)
> cleanup: Remove unused packet IDs

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1630)
> fix: handshake bug

- toxcore/group_chats.c
- toxcore/group_chats.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1632)
> refactor: Make TCP relay sharing packet lossless

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1679)
> cleanup: Trivial cleanup

- README.md
- updated the IRC channels info to reflect the current state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1693)
> chore: Update IRC info

- .cirrus.yml
- .github/settings.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1703)
> chore: Upgrade to toktok-stack:0.0.11.

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1672)
> docs: Add instructions for building unit tests to INSTALL.md

- .cirrus.yml
- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/DHT.h
- toxcore/DHT_test.cc
We definitely need more of this kind of test so refactorings don't
accidentally break things in ways that happen to still work in auto
tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1713)
> test: Add some unit tests for important internal DHT functions.

- .circleci/config.yml
- .github/settings.yml
- .travis/cmake-linux
- other/analysis/gen-file.sh
- other/analysis/run-check-recursion
- other/analysis/run-clang
- other/analysis/run-infer
- testing/DHT_test.c
- toxcore/Messenger.c
- toxcore/ccompat.h
- toxcore/crypto_core.c
- toxencryptsave/BUILD.bazel
- toxencryptsave/toxencryptsave.api.h
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1723)
> chore: Run infer static analyser on circle ci builds.

- toxav/bwcontroller.c
- toxav/ring_buffer.c
- toxav/rtp.c
- toxav/toxav.c
- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1725)
> cleanup: add some missing null checks

- CHANGELOG.md
- CMakeLists.txt
- auto_tests/save_load_test.c
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.api.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1722)
> chore: Release 0.2.13

- toxcore/TCP_connection.c
This makes the code a little more flat and readable. We also change the logic so that we can kill the necessary number of unused relays immediately rather than having to collect them and remove them in a separate loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1732)
> cleanup: Refactor kill_nonused_tcp()

- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/Messenger.c
- toxcore/onion.c
- toxcore/onion.h
- toxcore/onion_announce.c
- toxcore/onion_announce.h
This will be used in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1734)
> chore: Add logger to onion and onion announce objects

- .github/workflows/coverity-scan.yml
I can't test this locally, so let's hope it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1736)
> chore: Add workflow for running coverity scan.

- toxav/audio.c
- toxav/groupav.c
- toxav/msi.c
- toxav/ring_buffer.c
- toxav/toxav.c
- toxcore/crypto_core.c
- toxcore/group.c
All for-loops must have an init-decl, a condition, and an increment
statement. Any loop that doesn't have one of these should be a while
loop (only 2 of these exist in toxav, none in toxcore).
See https://github.com/TokTok/hs-cimple/pull/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1744)
> cleanup: Enforce for loop consistency.

- .github/workflows/clang-tidy-review.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1746)
> chore: Add clang-tidy review github workflow.

- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1740)
> cleanup: Put fatal errors where API return values should be impossible

- .github/workflows/coverity-scan.yml
Otherwise, no analysis will happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1752)
> chore: Use an incrementing version number for coverity scans.

- toxcore/onion.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1770)
> cleanup: merge onion.c changes from new groupchats fork

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1768)
> chore: merge DHT changes from new groupchats fork

- other/analysis/gen-file.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1772)
> chore: Add .cc files to the static analysis.

- toxcore/TCP_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1776)
> cleanup: remove unused function argument from set_tcp_connection_status()

- toxav/audio.c
- toxav/rtp.c
- toxav/toxav.c
- toxav/toxav_old.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/mono_time.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/state.h
These should only be used before a toplevel thing that can be commented on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1778)
> chore: Tie down the use of doxygen comments.

- .cirrus.yml
So we can use the latest cimple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1779)
> chore: Update toktok-stack version.

- toxcore/crypto_core_mem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1790)
> cleanup: remove redundant (and incorrect) comments

- .github/workflows/ci.yml
- .travis/cmake-windows.sh
To test the cross compilation dockerfile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1792)
> chore: Add cross compilation CI targets.

- toxcore/BUILD.bazel
- toxcore/friend_connection.c
- toxcore/friend_connection.cc
- toxcore/friend_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1798)
> chore: merge friend_connections from NGC fork

- .cirrus.yml
- .github/workflows/ci.yml
- .travis/tox-bootstrapd-docker
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/print-version
- toxcore/tox.h
This will also push to dockerhub on merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1811)
> chore: Add bootstrap daemon docker image build.

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .travis/tox-bootstrapd-docker
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1812)
> chore: Only push versioned docker image on tag builds.

- .github/settings.yml
- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1813)
> chore: Login to dockerhub before trying to push to dockerhub.

- toxav/msi.c
- toxav/toxav.c
- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1816)
> cleanup: put breaks inside case braces

- .github/settings.yml
- .github/workflows/ci.yml
- .travis/cmake-osx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1820)
> chore: Add macOS build.

- auto_tests/run_auto_test.h
This reduces complexity of the single function. Also reduced duplication
a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1819)
> refactor: Extract some functions from the big run_auto_test function.

- auto_tests/dht_test.c
- testing/DHT_test.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/onion_announce.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1673)
> cleanup: Remove hardening code from DHT

- toxav/groupav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1836)
> fix: possible unintended negative loop bound

- .travis/cmake-windows.sh
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
Neither of these clauses can ever be reached
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1835)
> cleanup: remove dead code

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/group.c
- toxcore/list.c
- toxcore/net_crypto.c
- toxcore/onion.c
See https://github.com/TokTok/hs-tokstyle/pull/100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1853)
> cleanup: Remove useless parentheses.

- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/msi.c
- toxav/ring_buffer.c
- toxav/toxav.c
- toxav/video.c
- toxcore/TCP_client.c
See https://github.com/TokTok/hs-tokstyle/pull/102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1860)
> cleanup: Fix `calloc` argument order.

- .circleci/cmake-asan
- .circleci/cmake-tsan
These are somewhat flaky. A few more retries should make them pass unless
they are properly broken. Most of the time they time out and one more
attempt would pass it. I've added 2 more attempts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1867)
> chore: Retry asan/tsan tests a few more times.

- BUILD.bazel
- auto_tests/BUILD.bazel
- other/BUILD.bazel
- other/fun/BUILD.bazel
- super_donators/BUILD.bazel
- toxcore/BUILD.bazel
- toxencryptsave/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1873)
> chore: Enable layering check in all c-toxcore build files.

- .cirrus.yml
- .github/settings.yml
Also increased memory limits so it doesn't OOM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1876)
> chore: Ignore some failures in bazel-tsan.

- toxav/toxav.c
Control logic is now placed in control-specific helper functions instead of having one giant confusing function that does everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1841)
> cleanup: refactor toxav_call_control

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/network.c
- toxcore/network.h
- toxcore/onion_client.c
I'm not sure this is a good idea. Feedback welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1894)
> cleanup: Deduplicate a somewhat complex loop in DHT.c.

- .github/scripts/cmake-linux
- .github/scripts/cmake-osx
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1899)
> cleanup: Make `Networking_Core` pointer-to-const where possible.

- .circleci/cmake-asan
- .circleci/cmake-tsan
- toxav/groupav.c
- toxav/groupav.h
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/LAN_discovery.c
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/onion.c
- toxcore/onion.h
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
I missed these the first time around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1903)
> cleanup: Even more pointer-to-const parameters.

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1906)
> cleanup: Split large switch statement into functions.

- other/BUILD.bazel
- other/fun/BUILD.bazel
- testing/BUILD.bazel
We want to ensure that nobody links against testing code in production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1905)
> chore: Mark unsafe code as testonly.

- toxcore/TCP_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1915)
> cleanup: replace magic numbers with appropriately named constants

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/config.c
Introduced in 5fbcbb6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1917)
> fix: buffer overwrite in bootstrap config

- .circleci/config.yml
- .github/settings.yml
- other/analysis/run-cpplint
- other/bootstrap_daemon/src/config.c
- other/fun/cracker.c
- other/fun/minimal-save-generator.c
- other/fun/sign.c
- other/fun/strkey.c
- toxav/audio.h
- toxav/groupav.h
- toxav/msi.c
- toxav/msi.h
- toxav/ring_buffer.c
- toxav/rtp.h
- toxav/toxav.c
- toxav/video.h
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/network.c
- toxcore/network.h
- toxcore/ping.h
- toxcore/ping_array.h
- toxcore/tox_api.c
- toxencryptsave/toxencryptsave.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1914)
> chore: Add cpplint to the CI.

- toxav/groupav.c
We now malloc and free the data field separately. This increases readability of the code and gets rid of static analyzer false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1920)
> cleanup: refactor group audio packet data handling

- toxav/groupav.c
Introduced in 762a601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1926)
> fix: group av memory leak

- .github/workflows/ci.yml
- auto_tests/BUILD.bazel
- other/fun/BUILD.bazel
See https://github.com/robinlinden/c-toxcore/runs/4974117996?check_suite_focus=true#step:3:160 for what a failed build looks like.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1933)
> chore: Add a Bazel Buildifier CI job

- .github/workflows/sonar-scan.yml
- toxav/groupav.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
This reverts commit e3d20afc6a36869531dde7b9155a5312c70c67d5.
It doesn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1922)
> chore: Don't run sonar scan on pull requests.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1938)
> cleanup: small refactor of DHT getnodes function

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
Also fix a bad comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1955)
> cleanup: Properly copy Node_format using serialized format

- other/analysis/run-infer
- toxcore/group.c
So people can run it locally more easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1958)
> chore: Make run-infer script use docker.

- toxav/groupav.c
- toxav/groupav.h
- toxav/msi.c
- toxav/ring_buffer.c
- toxav/ring_buffer.h
- toxav/rtp.c
- toxav/toxav.h
- toxav/toxav_old.c
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1972)
> chore: Make the last few remaining top level comments doxygen style.

- .github/scripts/cmake-linux
- .github/scripts/cmake-osx
- .github/settings.yml
- docs/Doxyfile
- netlify.toml
- other/docker/doxygen/Dockerfile
- toxav/toxav.h
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/ping_array.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1976)
> docs: Make crypto_core.h appear on doxygen.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1978)
> chore: Release 0.2.14

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1980)
> fix: Reduce logging verbosity in TCP server.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1983)
> chore: Release 0.2.15

- CMakeLists.txt
- auto_tests/tox_dispatch_test.c
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/events/conference_connected.c
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/conference_peer_list_changed.c
- toxcore/events/conference_peer_name.c
- toxcore/events/conference_title.c
- toxcore/events/events_alloc.h
- toxcore/events/file_chunk_request.c
- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/events/file_recv_control.c
- toxcore/events/friend_connection_status.c
- toxcore/events/friend_lossless_packet.c
- toxcore/events/friend_lossy_packet.c
- toxcore/events/friend_message.c
- toxcore/events/friend_name.c
- toxcore/events/friend_read_receipt.c
- toxcore/events/friend_request.c
- toxcore/events/friend_status.c
- toxcore/events/friend_status_message.c
- toxcore/events/friend_typing.c
- toxcore/events/self_connection_status.c
- toxcore/tox_events.c
- toxcore/tox_events.h
- toxcore/tox_unpack.c
- toxcore/tox_unpack.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1996)
> feat: Add unpacker functions for events structures.

- toxcore/Makefile.inc
Fixes #2009.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2010)
> chore: Remove duplicate source file in autotools build.

- .github/workflows/coverity-scan.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2018)
> fix: Coverty scan

- .github/scripts/cmake-android
- .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1992)
> chore: Set up an Android CI job

- INSTALL.md
Added the recently introduced libmsgpack dependency in INSTALL.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2016)
> docs: Add libmsgpack dependency in INSTALL.md

- .clusterfuzzlite/Dockerfile
- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2027)
> fix: add continous fuzzing

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
- toxcore/TCP_common.c
- toxcore/TCP_server.c
- toxcore/net_crypto.c
- toxcore/network.c
ERROR is caught in tests, so we'll use it more for things that ought not
to happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2039)
> refactor: Add a bit more logging; change WARNING to ERROR.

- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/msi.c
- toxav/ring_buffer.c
- toxav/rtp.c
- toxav/toxav.c
- toxav/video.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_common.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/list.c
- toxcore/logger.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_client.c
- toxcore/tox.c
- toxencryptsave/toxencryptsave.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2055)
> cleanup: Avoid implicit bool conversions in logical operators.

- auto_tests/onion_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxcore/onion_announce.c
- toxcore/onion_announce.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2053)
> cleanup: Enable tokstyle's `-Wlarge-struct-params`.

- .cirrus.yml
- .github/scripts/autotools-linux
- .github/scripts/cmake-freebsd-stage2
- .github/settings.yml
- .github/workflows/ci.yml
- other/docker/autotools/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2069)
> chore: Simplify and speed up nacl build using toxchat/nacl.

- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2073)
> chore: Fix build-args in win32/win64 docker build.

- .github/scripts/cmake-windows.sh
- .github/workflows/ci.yml
- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2072)
> chore: Simplify and speed up windows builds using docker image.

- toxcore/group.c
Found here: https://github.com/TokTok/c-toxcore/actions/runs/1863916365
Depends on: https://github.com/TokTok/c-toxcore/pull/2058
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2064)
> fix: toxsave memory leak while loading groups

- .clang-format
- .restyled.yaml
- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/toxsave_harness.cc
- testing/random_testing.cc
- toxav/ring_buffer_test.cc
- toxav/rtp_test.cc
- toxcore/DHT_test.cc
- toxcore/Messenger.c
- toxcore/ccompat.h
- toxcore/crypto_core_test.cc
- toxcore/friend_connection_test.cc
- toxcore/list_test.cc
- toxcore/logger.h
- toxcore/mono_time_test.cc
- toxcore/network_test.cc
- toxcore/ping_array_test.cc
- toxcore/util_test.cc
Fixes #1990.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2075)
> chore: Add a .clang-format that mostly agrees with astyle.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/TCP_connection.c
- toxcore/crypto_core.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion_client.c
- toxcore/tox.c
- toxencryptsave/toxencryptsave.c
Found by https://github.com/TokTok/hs-tokstyle/pull/142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2096)
> cleanup: Return boolean constants, not ints from bool functions.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/rtp.c
- toxav/toxav.c
- toxav/video.c
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/group.c
- toxcore/list.c
- toxcore/mono_time.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/tox.c
- toxcore/tox_api.c
- toxencryptsave/toxencryptsave.c
Found by https://github.com/TokTok/hs-tokstyle/pull/148.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2102)
> cleanup: Mark all local non-pointers as const where possible.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/tokstyle/Dockerfile
- toxav/msi.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group.c
- toxcore/group.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/network.c
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/tox.c
Also use `bool` type in place of `uint8_t` which was the old bool type
in toxcore before C99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2103)
> cleanup: Remove more implicit bool conversions.

- toxcore/onion_client.c
This forces the onion to consider all friends as new after a 10 second
period of the onion being disconnected. new friends are aggressively
searched for in the DHT, whereas old friends are only searched for in
intervals spanning minutes.
maybe fixes #2080 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2092)
> perf: fix issue with friend finding taking too long after disconnects.

- .github/workflows/ci.yml
- auto_tests/dht_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/friend_connection.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/tox.c
- toxcore/tox.h
Also reduce log verbosity a bit.
Fixes https://github.com/TokTok/c-toxcore/issues/647.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2104)
> fix: Report failure to DHT bootstrap back to the client.

- toxav/msi.c
- toxcore/DHT.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2113)
> cleanup: Remove superfluous parentheses on the rhs of assignments.

- toxcore/TCP_connection.h
- toxcore/crypto_core.c
- toxcore/tox.c
- toxcore/tox_api.c
Tokstyle will require this format:
- Optionally a single include (the module header).
- System includes.
- Local includes.
In headers, there is no module header to include, so system includes
come first there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2117)
> cleanup: Comply with strict include ordering.

- auto_tests/TCP_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_client.c
- toxcore/network.c
- toxcore/network.h
- toxcore/onion.c
Failure is defined as either being passed an invalid IP/Port, or some
unexpected error code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2115)
> cleanup: Log at ERROR level when `connect()` fails.

- toxav/rtp.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_server.c
- toxcore/network.c
- toxcore/network.h
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/ping_array.c
- toxcore/tox.c
Also removed one explicit bool cast.
Also avoid using the same name for struct fields and global functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2123)
> cleanup: Remove some more implicit bool conversions.

- auto_tests/auto_test_support.c
- auto_tests/lan_discovery_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/coverage/run_mallocfail
- toxcore/LAN_discovery.c
- toxcore/tox_test.cc
This is added later when we actually send the broadcasts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2126)
> cleanup: Remove port from `Broadcast_Info`.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2138)
> chore: Release 0.2.17

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_connection.c
- toxcore/tox.c
Nothing very noteworthy, I just came across this and made it slightly
more readable.
I'm not making this function `bool` right now because it's used in NGC
and that will break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2144)
> cleanup: Minor cleanups in TCP_connection.c.

- other/DHT_bootstrap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2143)
> fix: Allow port range in DHT_bootstrap.c.

- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2146)
> chore: Add testing/Dockerfile to the CI build.

- toxcore/tox.h
This will help with code generation, FFI generation, and API validation later on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2153)
> docs: Put all the tox public api into a fake "tox" namespace.

- auto_tests/toxav_many_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2154)
> test: Speed up toxav_many_test by using fake mono_time.

- other/analysis/run-cppcheck
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/TCP_client.c
- toxencryptsave/toxencryptsave.c
Also enable cppcheck in both C and C++ mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2157)
> cleanup: Split the huge TCP client packet handler.

- .github/scripts/flags-clang.sh
- .github/scripts/flags-gcc.sh
- auto_tests/onion_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/network.c
- toxcore/network.h
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
These changes will make the DHT compatible with the new groupchats implementation. Additionally, onion announces now support arbitrary extra data.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2164)
> feat: Merge onion_announce changes from new groupchats fork

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/bwcontroller.c
- toxav/video.c
- toxcore/DHT.c
- toxcore/group.c
As of https://github.com/TokTok/hs-tokstyle/pull/172.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2166)
> cleanup: Reduce scope of variables as requested by cimple.

- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
This is the standard across toktok repos. Exceptions are a pain for
automation and tooling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2173)
> chore: Use "master" as the branch in toktok-fuzzer.

- .cirrus.yml
- .clang-format
- other/analysis/gen-file.sh
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/websocket/websockify/BUILD.bazel
- testing/fuzzing/BUILD.bazel
- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/fuzz_adapter.c
- testing/fuzzing/toxsave_harness.cc
- toxcore/BUILD.bazel
- toxcore/DHT_fuzz_test.cc
- toxcore/logger.h
- toxcore/network.c
- toxcore/tox_events.c
- toxcore/tox_events_fuzz_test.cc
- toxcore/tox_events_test.cc
Needs https://github.com/TokTok/toktok-stack/pull/451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2170)
> test: Add fuzzer tests to the bazel build.

- testing/fuzzing/BUILD.bazel
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- toxcore/BUILD.bazel
- toxcore/DHT_fuzz_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2184)
> test: Add some support functions to make writing fuzzers easier.

- other/docker/sources/Dockerfile
This is needed so other/docker/coverage/run works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2189)
> chore: Add third_party to toxcore-sources docker image.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2183)
> test: Enable more tests for msan.

- testing/fuzzing/BUILD.bazel
- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/fuzz_adapter.c
- testing/fuzzing/fuzz_adapter.h
- toxcore/mono_time.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2193)
> perf: Make time move a lot faster in fuzzing runs.

- toxcore/tox.c
So the rest of the code can assume non-null more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2200)
> cleanup: Add more null checks in `tox_new`.

- testing/fuzzing/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2187)
> test: Add DHT and tox_events fuzz tests to the cmake build.

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2225)
> fix: fix typo in git command in INSTALL.md

- auto_tests/network_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
This function doesn't use Network yet, but it will in the future, and
for now it's better to pass Network to all network I/O functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2217)
> cleanup: Add Network object parameter for addr_resolve.

- .github/dependabot.yml
To keep the third_party/cmp submodule up-to-date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2236)
> chore: Add dependabot config.

- .gitmodules
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
The upstream maintainer is active and has merged our changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2240)
> chore(deps): Use upstream cmp directly instead of our fork.

- auto_tests/forwarding_test.c
By trying to create a tox tcp relay on 100 ports starting at 36570.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2249)
> test: Improve stability of forwarding_test.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2233)
> cleanup: Replace a series of `if` statements with a `switch`.

- .github/workflows/docker.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/esp32/CMakeLists.txt
- other/docker/esp32/Dockerfile
- other/docker/esp32/hello/CMakeLists.txt
- other/docker/esp32/hello/hello_main.c
- other/docker/esp32/run
- other/docker/esp32/toxcore/CMakeLists.txt
- other/docker/esp32/toxcore/toxcore_main.cc
- toxcore/mono_time.c
- toxcore/network.c
It won't actually run until we reduce memory consumption by 2
orders of magnitude, but that'll be the eventual goal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2243)
> chore: Add initial ESP32 docker build.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2266)
> fix: Fixed leak and overrun added in e49a477a

- auto_tests/toxav_basic_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2270)
> test: Improve error messages in toxav_basic_test.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_announce.c
Note: This code cannot presently be called
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2272)
> fix: Add missing return on error

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2273)
> fix: Really fix overrun added in e49a477a

- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/toxsave_harness.cc
This does nothing but has a working simple RNG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2289)
> test: Add a Null_System used in toxsave_harness.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2299)
fixes #2298
> fix: remove the assert because buffer can be larger than UINT16_MAX.

- other/bootstrap_daemon/README.md
Old instructions do not work as we do not tag every version, we only tag latest version for the image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2333)
> docs: Update README for bootstrap node docker

- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2371)
> docs: fix group_peer_exit_cb

- .github/workflows/docker.yml
- .github/workflows/sonar-scan.yml
- azure-pipelines.yml
- other/docker/alpine-s390x/Dockerfile
- other/docker/freebsd/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2434)
> chore: Cancel old PR builds on docker and sonar-scan workflows.

- README.md
We can replace this with a tox groupchat once we make a release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2456)
> docs: Remove defunct IRC channel from README.md

- toxcore/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2458)
> fix: also Install header for private/experimental API functions with autotools

- .github/workflows/ci.yml
- .github/workflows/post-submit.yml
It takes 15+ minutes and will very rarely fail, so it's not worth blocking PRs on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2476)
> chore: Move s390x build to post-merge.

- auto_tests/tox_dispatch_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox_unpack.c
- toxcore/tox_unpack.h
extracted from my other pr https://github.com/TokTok/c-toxcore/pull/2378
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2480)
> feat: add ngc related unpack functions

- .github/workflows/ci.yml
- .github/workflows/docker.yml
The old ones are going to stop working soon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2481)
> chore: Update github actions `uses`.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2490)
> cleanup: Some portability/warning fixes for Windows builds.

- .github/workflows/post-submit.yml
- .github/workflows/sonar-scan.yml
We can then use that to build a coverage web UI on render.com using the Dockerfile.nginx build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2491)
> chore: Build a docker image with coverage info in it.

- .clang-tidy
- .github/settings.yml
- other/analysis/run-clang-tidy
- other/docker/clang-tidy/Dockerfile
- toxcore/DHT.h
- toxcore/events/events_alloc.h
- toxcore/group_announce.h
- toxcore/group_chats.h
- toxcore/group_common.h
- toxcore/group_connection.h
- toxcore/group_pack.h
- toxcore/onion_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2507)
> cleanup: Run clang-tidy on headers, as well.

- other/bootstrap_daemon/README.md
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/command_line_arguments.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/config.h
- other/bootstrap_daemon/src/tox-bootstrapd.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2517)
> chore: Spellcheck tox-bootstrapd

- toxcore/crypto_core_test_util.cc
- toxcore/crypto_core_test_util.hh
- toxcore/test_util.hh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2543)
> refactor(test): Slightly nicer C++ interface to tox Random.

- .github/workflows/ci.yml
noticed it was rather slow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2560)
> fix(ci): window builds now build in parallel

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2562)
> chore: add clangd files to .gitignore

- auto_tests/group_moderation_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2563)
> test: Add printf log statement to group_moderation_test.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/bin_pack.c
- toxcore/bin_pack.h
- toxcore/bin_pack_test.cc
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/tox_events.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2575)
> refactor: Pass `this` pointer as first param to s11n callbacks.

- toxav/groupav.c
- toxav/groupav.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2582)
> cleanup: Rename group to conference in groupav documentation.

- auto_tests/tox_new_test.c
This can be used for some static analysis that doesn't currently survive a full iterate loop, but can possibly survive a new+kill.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2590)
> test: Add a simple new/delete test for Tox.

- auto_tests/TCP_test.c
- auto_tests/auto_test_support.c
- auto_tests/conference_av_test.c
- auto_tests/conference_invite_merge_test.c
- auto_tests/conference_simple_test.c
- auto_tests/conference_test.c
- auto_tests/crypto_test.c
- auto_tests/file_streaming_test.c
- auto_tests/file_transfer_test.c
- auto_tests/forwarding_test.c
- auto_tests/friend_request_test.c
- auto_tests/group_general_test.c
- auto_tests/group_invite_test.c
- auto_tests/group_message_test.c
- auto_tests/group_moderation_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
Also one in `DHT_bootstrap.c`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2602)
> cleanup: Add `const` where possible in auto tests.

- .github/workflows/ci.yml
- other/docker/rpm/rpm.Dockerfile
- other/docker/rpm/run
- other/rpm/toxcore.spec.in
- toxcore/LAN_discovery.c
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2604)
> chore: Fix rpm build; add a CI check for it.

- .github/workflows/post-submit.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2610)
> chore: Fix post-submit coverage image.

- .github/workflows/post-submit.yml
It made progress, but then the last step failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2611)
> chore: Really fix coverage docker image build.

- other/astyle/astylerc
To explain why some options are disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2634)
> chore: Add some comments to the astyle config.

- .github/workflows/ci.yml
- other/docker/slimcc/.gitignore
- other/docker/slimcc/Makefile
- other/docker/slimcc/run
- other/docker/slimcc/slimcc.Dockerfile
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2624)
> test: Add slimcc compiler compatibility test.

- toxcore/network.c
Otherwise warnings happen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2655)
> cleanup: Check that WINXP macro exists before comparing it.

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2659)
> cleanup: Simplify custom packet length check in NGC.

- .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2697)
> test: Build toxcore on NetBSD (VM).

- auto_tests/group_general_test.c
- auto_tests/group_invite_test.c
- auto_tests/group_moderation_test.c
- auto_tests/group_save_test.c
- auto_tests/group_state_test.c
- auto_tests/group_sync_test.c
- auto_tests/group_tcp_test.c
- auto_tests/group_topic_test.c
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2705)
> refactor: Rename Queries to Query to align with other enums.

- .github/workflows/ci.yml
- .github/workflows/coverity-scan.yml
- .github/workflows/docker.yml
- .github/workflows/post-submit.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2712)
> chore: Update github actions.

- .cirrus.yml
- toxcore/tox.h
- toxcore/tox_dispatch.h
- toxcore/tox_events.h
Also add experimental api warnings on tox_events.h and tox_dispatch.h.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2743)
> docs: Add missing param docs for callbacks.

- other/docker/compcert/compcert.Dockerfile
- other/docker/windows/get_packages.sh
- other/emscripten/Dockerfile
Noticed CI failing in #2760. This should fix the failures that are not caused by that PR's changes. The remaining failures would need to be fixed in the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2761)
> chore: Fix CI

- .cirrus.yml
14.0 is EOL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2777)
> chore: Upgrade to FreeBSD 14.1 in cirrus build.

- other/bootstrap_daemon/docker/Dockerfile
- other/docker/perf/Dockerfile
- testing/Dockerfile
CodeQL scanning is complaining about this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2778)
> cleanup: Sort apk/apt install commands in Dockerfiles.

- .gitmodules
There are a few minor modifications in there that make it aligned with cimple's standards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2779)
> chore: Use toktok's cmp instead of upstream.

- .github/scripts/flags-clang.sh
- .github/scripts/flags-gcc.sh
- auto_tests/conference_av_test.c
- auto_tests/conference_double_invite_test.c
- auto_tests/conference_invite_merge_test.c
- other/analysis/run-clang
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/fun/save-generator.c
- other/fun/sign.c
- other/fun/strkey.c
- toxav/groupav.c
- toxcore/DHT.c
- toxcore/announce.c
- toxcore/group.c
- toxcore/group_chats.c
- toxcore/onion_client.c
- toxencryptsave/toxencryptsave.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2786)
> cleanup: Fix all `-Wsign-compare` warnings.

- toxcore/events/dht_get_nodes_response.c
This was added everywhere except here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2788)
> fix: Add missing free in dht_get_nodes_response event.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/pkgsrc/pkgsrc.Dockerfile
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2792)
> chore: Release 0.2.20

- .github/workflows/checks.yml
Across PR milestone, "next" milestone, and draft release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2791)
> chore: Add check to ensure version numbers agree.

- auto_tests/TCP_test.c
- testing/fuzzing/fuzz_support.cc
- toxcore/TCP_client.c
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2774)
> feat(net): add missing connect to network struct

- other/bootstrap_daemon/websocket/websockify/go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2809)
> chore: Upgrade dependencies for websockify.

- BUILD.bazel
- toxcore/BUILD.bazel
They are still experimental, but we can start integrating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2814)
> chore: Add dispatch/events headers to bazel export.

- toxcore/sort_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2827)
> cleanup: Add missing `#include` to sort_test.cc.

- auto_tests/TCP_test.c
- toxcore/TCP_client.c
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2828)
> fix: Allow TCP connections to fail `connect` calls.

- .github/workflows/deploy.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2850)
> chore: Fix xcframework checksum creation.

- toxcore/DHT.c
This is mostly forward thinking, where we might introduce other ip families, in addition to ipv4, ipv6, tcp_ipv4 etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2853)
> refactor: don't fully discard received DHT nodes.

- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2856)
> fix: ip to string function not accepting tcp families

- auto_tests/TCP_test.c
- auto_tests/network_test.c
- other/docker/cppcheck/toxcore.cfg
- toxav/rtp.c
- toxav/toxav.c
- toxcore/TCP_common.c
- toxcore/TCP_server.c
- toxcore/network.c
- toxcore/network.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2857)
> perf: Use stack allocation for strerror rendering.

- .github/workflows/deploy.yml
- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2869)
> chore: Add wasm to the nightly binary deploys.

- other/docker/wasm/wasm.Dockerfile
- toxcore/network.c
This is needed by dart's wasm_ffi.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2871)
> chore: Export wasmExports from the wasm binary.

- .cirrus.yml
- .clog.toml
- .github/workflows/ci.yml
- CHANGELOG.md
- other/deploy/ios.sh
- other/deploy/macos.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2872)
> docs: Update changelog format to use the new clog-compatible way.

- .github/scripts/cmake-osx
- .github/workflows/deploy.yml
- other/docker/goblint/sodium.c
- other/make_single_file
Fixes https://github.com/TokTok/c-toxcore/issues/2810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2873)
> chore: Add deploy job for single C file library.

- .github/workflows/deploy.yml
- other/deploy/single-file/.gitignore
- other/deploy/single-file/Makefile
- other/deploy/single-file/make_single_file
- other/docker/goblint/goblint.Dockerfile
- other/docker/sparse/sparse.Dockerfile
- other/docker/tcc/tcc.Dockerfile
This makefile is untested, so hope is the strategy here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2874)
> feat: Add a Makefile for the single file deploy build.

- .github/ISSUE_TEMPLATE/release.yml
- .github/workflows/draft.yml
- .github/workflows/release.yml
- .reviewable/completion.js
- .reviewable/settings.yaml
Fixes https://github.com/TokTok/c-toxcore/issues/2051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2878)
> chore: Add release issue template and workflow.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/version-sync
- tools/update-versions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2883)
> chore: Add version update script compatible with ci-tools.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/pkgsrc/pkgsrc.Dockerfile
- other/docker/pkgsrc/pkgsrc.patch
- so.version
- third_party/.gitignore
- toxcore/tox.h
Pre-release for toxcore. Primarily, we now have an experimental network profiling callback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2882)
> chore: Release v0.2.21-rc.1

- toxcore/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2895)
> fix(bazel): missing dep for fuzz target

- auto_tests/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2896)
> fix(bazel): missing dep for auto_tests

- toxcore/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2901)
> fix(bazel): make net_prof visible to its consumers

- toxcore/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2903)
> fix(bazel): one more fuzz target that needs netprof

- toxav/toxav.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2899)
> fix(toxav): handle vpx_image_alloc failure

- .github/scripts/cmake-osx
- .github/workflows/ci.yml
- other/docker/goblint/goblint.Dockerfile
- toxav/rtp.h
- toxcore/friend_connection.h
- toxcore/tox_options.h
Cimple is now stricter in these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2918)
> cleanup: Fix comment formatting errors.

- .github/scripts/sonar-prepare
- .github/workflows/sonar-scan.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2920)
> chore: Fix sonar-scan CI action.
