- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1572)
> fix: bug causing invalid TCP nodes to be copied to group announcements

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.h
- toxcore/tox.c
Instead of spamming peers for invites for 15 seconds straight in intervals we now
have a simple timer and make one request per n seconds.
In addition, the CS_MANUALLY_DISCONNECTED and CS_FAILED states were merged
with CS_DISCONNECTED and state logic was simplified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1579)
> refactor: invite sending and main do_gc loop

- toxcore/Messenger.c
- toxcore/group_chats.c
- toxcore/group_chats.h
Self announcements are now refreshed when either our TCP or UDP connection changes
as long as one or the other is connected. We no longer spam the DHT needlessly
when our TCP status updates. In addition, we always attempt to refresh
our announcements every 10 minutes if possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1581)
> refactor: Improve self group announcement mechanism

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
This fixes an issue where a tcp connection number was being killed twice which
would occasionally cause buggy behaviour if a new peer was assigned that same
id (e.g. on a rejoin or reconnect)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1584)
> fix: Kill tcp connection when peer is marked for deletion

- auto_tests/tcp_relay_test.c
This is a non-hermetic network test. initramfs node is down, so let's
have a second one for redundancy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1586)
> test: Fix tcp_relay_test by adding a second bootstrap node.

- toxcore/group_chats.c
- toxcore/group_chats.h
This greatly reduces the amount of unnecessary sync requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1589)
> refactor: Add peer count back into ping packet

- toxcore/Messenger.c
- toxcore/group_chats.c
- toxcore/group_chats.h
Instead of every peer refreshing their announcements every n minutes we ask
each peer to play a lottery every n minutes where their chance of winning
is relative to the number of peers in the group, and announce only if they
win. We only need a bare minimum of one announcement in the DHT at any given
time, so this ensures that while not constantly burdening the DHT with
unnecessary traffic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1591)
> Refactor: Reduce unnecessary amount of group announcement spam

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
- Make sure peers can't be marked for deletion twice
- Ignore handshake packets from peers we've already handshaked with
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1593)
> Fix: A couple small fixes 

- toxcore/group_chats.c
- toxcore/group_chats.h
- We no longer have the peer who receives a sync request send the requestor's
info to the rest of the group as this was redundant (and broken)
- Lots of unnecessary/duplicate code pertaining to handshaking was removed
- Message ID's are set to a fixed number when we send/receive handshake
packets instead of incrementing. This is because it's impossible to
proceed with the connection if either of those first two packets
are lost, so incrementing the counters just messes up the order
- Sync responses no longer contain the number of peers being sent
in the series of peer announces as this was unnecessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1595)
> refactor: Simplify and improve group handshake protocol

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1597)
> fix: Broadcast a quit packet before we rejoin a group

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group_chats.c
- toxcore/group_chats.h
- Remove a TCP callback that wasn't doing what it was supposed to be doing
- We now update our UDP and TCP connection status from the main loop
- Properly keep track of our TCP connection status: previously we were
updating our announcement every time we connected to an individual
peer via TCP, now we update it when we add or remove a TCP relay
- UDP status now differentiates between LAN and WAN
- Remove the recently added self announcement refresh (it's probably
unnecessary)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1601)
> refactor: Self-announce/self-connection refactor

- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1603)
> fix: bug causing invalid tcp relays to be copied to peer relay lists

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/group_chats.c
- toxcore/group_chats.h
Everything the Messenger Group struct held is now taken care of by the
GC_Chat instance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1604)
> refactor: Remove a bunch of useless group code from Messenger.c

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_connection.c
- toxcore/group_connection.h
- No longer store duplicate TCP relays for peer connections
- Replace old TCP relays with new ones instead of ignoring them
- Only send peers TCP relays if we connect to new ones rather
than sending the same ones over and over again on a timer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1607)
> refactor: Improve TCP relay sending and storing

- toxcore/group_chats.c
This would normally result in lot of unnecessary invite and sync requests which
would either fail or supply bad group info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1609)
> fix: Connected peers don't need to receive group announcements

- toxcore/group_chats.c
- toxcore/group_connection.h
We now continually attempt to send peers our TCP relays on a timer if we currenlty have no
TCP connections with them. This prevents situations where we may never establish shared
TCP relays with a peer in the case of packet loss or other temporary connection issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1620)
> fix: Improve group TCP connections

- appveyor.yml
Not sure why I didn't hit this in my PR adding conan since I rebased it multiple times. :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1633)
> fix: AppVeyor failing due to conan remote being added twice

- toxcore/group_chats.c
Note: The underlying bug still exists, as it relates to the TCP implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1659)
> fix: bug causing group announcements to be spammed non-stop

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
```
* g++       9.2.0-r4  -> 9.3.0-r0
* gcc       9.2.0-r4  -> 9.3.0-r0
* libatomic 9.2.0-r4  -> 9.3.0-r0
* libcurl   7.67.0-r0 -> 7.67.0-r1
* libgcc    9.2.0-r4  -> 9.3.0-r0
* libgomp   9.2.0-r4  -> 9.3.0-r0
* libstdc++ 9.2.0-r4  -> 9.3.0-r0
* python3   3.8.2-r0  -> 3.8.2-r1
```
Most of these don't affect the binary, but these are the packages we install in the docker image that have changed since the checked-in checksum worked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1667)
> chore: Update tox-bootstrapd checksum due to newer packages in Alpine

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/audio.c
- toxcore/DHT.c
The default stack size for musl-libc is 128kb, which is smaller than the largest stack allocations in toxcore. We should try to keep stack allocations well below this limit in order to avoid stack overflows on musl builds.
Using the compiler flag `-Wlarger-than=2000` we can see that after this change the largest stack allocation is now just over 2kb. 
It's worth noting that musl versions >= 1.22 allow us to increase the stack size by setting the LDFLAGS: `-Wl,-z,stack-size=<size>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1664)
> cleanup: use heap memory instead of stack for large variables

- auto_tests/file_saving_test.c
- auto_tests/save_compatibility_test.c
The issue was that fopen with r or w without the b flag on Windows does LF
and CR translations when reading and writing. Not good for binary files.
I'm not making the Windows tests required for merge yet as conference_av
still fails sometimes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1663)
> fix: Fix file tests on windows

- INSTALL.md
- other/docker/windows/Dockerfile
- other/docker/windows/build_dependencies.sh
- other/docker/windows/build_toxcore.sh
- other/docker/windows/get_packages.sh
- other/windows_build_script_toxcore.sh
Based on Windows docker scripts with some tweaks:
* add parameter `CROSS_COMPILE` for switching between Cygwin and Docker:
* `true` for Docker
* `false` for Cygwin
* disable `set -e -x` because some dependencies builds fail due to that
* remove prefix and tmp folders to run a clean build each time
* build **Opus** from tarball not from git clone because `autogen.sh` failed on Cygwin due to some error with `ltmain.sh` symlink:
```bash
Updating build configuration files, please wait....
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
autoreconf-2.69: libtoolize failed with exit status: 1
```
* add `-fstack-protector` to `CMAKE_EXE_LINKER_FLAGS` and `-lssp` when creating `libtox.dll` to fix (https://github.com/msys2/MINGW-packages/issues/5868)
* change …
> chore: Cygwin build

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1684)
> cleanup: Update INSTALL.md instructions

- appveyor.yml
- conanfile.py
This PR allow c-toxcore to be build as a conan package.
So client can use "c-toxcore/0.2.12" as requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1686)
> chore: Enable c-toxcore conan packaging

- .cirrus.yml
- appveyor.yml
The problem was that when running commands in powershell, any stderr
output is treated as an "exception", stopping the build even if the exit
code of the command was good.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1691)
> chore: Fix Appveyor and add workarounds for Cirrus CI

- auto_tests/save_load_test.c
The test explicitly wanted a UDP connection when a TCP connection would suffice. This was a remnant of back when the test was part of a multi-purpose autotest (https://github.com/TokTok/c-toxcore/commit/c3515c49e012f76c5d2ca104476e372d924a79f9) that didn't attempt to connect to TCP relays and needed a UDP connection specifically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1705)
> fix: issue with save_load autotest

- .cirrus.yml
- .github/settings.yml
This ensures that we don't break Cimple compatibility despite Travis
being gone (which used to test this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1706)
> chore: Enable cimple tests on cirrus build.

- toxcore/onion_client.c
The following line: 
`onion_c->udp_connected = udp_connected  || get_random_tcp_onion_conn_number(nc_get_tcp_c(onion_c->c)) == -1;`
sets our onion client connection status to UDP if we fail to find a random onion tcp connection number, regardless of whether or not we're actually connected to the DHT. This causes the API to sometimes incorrectly report our connection status as UDP. The main issue here is that this can occur when we explicitly force TCP connections, which may lead to some confusion for the end user.
The TCP connection check doesn't seem to be doing anything useful so I've removed it. The execution path of the proceeding call to `onion_connection_status()` on line 1843 is independent of the value of `onion_c->udp_connected` because the return value is treated as a boolean. …
> fix: bug causing API to report wrong self connection status

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/net_crypto.c
This fixes three issues:
1. Errors for `crypto_connection_status()` are now checked. If a valid connection status is not found, the friend is assigned a connection status of none.
2. It was possible for the API function `tox_friend_get_connection_status()` to return an incorrect friend connection status, because `m_get_friend_connectionstatus()` could return `UNKNOWN_STATUS`, which did not correspond to a value from the `Tox_Connection` enum, and was not checked for: https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.c#L1291
3. Per lines 902-909, It was possible for us to get a friend connection status callback erroneously reporting the friend's connection to have switched from NONE to TCP, even though a TCP connection had not really been established.
---
This change is [<img …
> fix: some friend connection issues

- toxcore/DHT.c
Mono_Time needs to acquire a lock each time one of its functions are
used. This becomes very costly in the DHT code where timeouts for all
connected nodes are recalculated. Improve this by caching the timestamp
at the begin of a do_dht() iteration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1708)
> perf: reduce calling into Mono_Time in DHT

- toxcore/group.c
Fixes #1598 -- thanks to peirick for reporting the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1602)
> fix: Fix buffer over-read when a peer leaves a conference

- other/bootstrap_daemon/src/global.h
- toxcore/DHT.c
This PR fixes a stack based buffer overflow in the DHT packet handler which is . I don't know if it's exploitable because I patched away the crypto layer, but I'd choose to error safe side here and assume yes until proven otherwise.
I'll open a PR to discuss how to prevent issues with computed values in macros in the future.
ASAN Report leading to this find:
```
=================================================================
==23521==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffdc4aad100 at pc 0x0000002eafea bp 0x7ffdc4aacb50 sp 0x7ffdc4aac318
WRITE of size 1029 at 0x7ffdc4aad100 thread T0
#0 0x2eafe9 in __asan_memcpy /home/abuild/rpmbuild/BUILD/llvm-11.0.1.src/build/../projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
#1 0x3711d2 in …
```
> fix: Sec/fix crypto size compute

- .cirrus.yml
- toxav/toxav.c
- toxcore/DHT.h
- toxcore/TCP_connection.h
- toxcore/friend_connection.h
- toxcore/network.c
This should cut down the build time a bit by downloading the binaries
built for `//third_party/...`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1716)
> chore: Use toktok-stack docker image with built third_party.

- other/analysis/run-gcc
- toxcore/tox.c
In this case, there was no way it would not be, but a code change down
the stack could cause a variable to become uninitialised. This avoids a
gcc warning and is more locally-correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1729)
> cleanup: Ensure that error codes are always initialised.

- auto_tests/save_compatibility_test.c
- testing/afl_toxsave.c
* Buffer overrun in auto test.
* Resource leak in AFL test code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1733)
> cleanup: Minor fixes in test code.

- toxcore/crypto_core.api.h
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/crypto_core_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1727)
> cleanup: Avoid endian-specific code in `crypto_core`.

- auto_tests/TCP_test.c
- auto_tests/crypto_test.c
- auto_tests/network_test.c
- auto_tests/save_load_test.c
- auto_tests/set_name_test.c
- auto_tests/set_status_message_test.c
- auto_tests/toxav_basic_test.c
- auto_tests/toxav_many_test.c
- toxcore/Messenger.c
- toxcore/ccompat.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1743)
> chore: Minor cleanups of warnings given by cppcheck.

- .github/workflows/coverity-scan.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1738)
> chore: Add missing `sudo` to coverity apt-get calls.

- other/bootstrap_daemon/src/config.c
Includes should be sorted alphabetically and null-terminating is unnecessary with `snprintf`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1737)
> refactor: Fix previous refactor

- other/analysis/run-clang-tidy
- other/bootstrap_daemon/src/log.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxav/msi.c
- toxcore/DHT.c
- toxcore/tox.c
- toxcore/tox_api.c
- toxencryptsave/toxencryptsave.c
The android warnings are disabled now because they suggest using
linux-only extensions of libc. Useful for android indeed, but we're
targeting non-android and non-linux systems as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1747)
> cleanup: Fix some clang-tidy warnings and make them errors.

- toxcore/TCP_client.c
- toxcore/TCP_client.h
In the "no proxy" case, the `IP_Port` in the default "no proxy" default
proxy info is uninitialised. It is never used for any decisions in the
code, but it is copied in memory, making it a potential crash on systems
with trap representations of ints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1751)
> fix: Fixed uninitialised value copy.

- toxcore/Messenger.c
The assert was removed, because it triggers as soon as the padding bytes
in the struct Saved_Friend are non zero. The Tox specification doesn't
say anything about the value of these bytes, so we should just ignore
them.
Found with #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1333)
> refactor: Clean up friend loading.

- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1754)
> fix: off-by-one error caused by integer division without proper cast

- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/onion.c
- toxcore/ping.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1753)
> cleanup: use crypto_memzero to wipe secret keys when no longer in use

- toxav/toxav.api.h
- toxav/toxav.c
- toxav/toxav.h
This allows for prioritizing audio over video transcoding and improves
performance when multiple CPU cores are available.
I would be happy if someone could help me write some tests for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1307)
> refactor: Split toxav_iterate into audio and video part

- toxcore/TCP_client.c
- toxcore/network.c
- toxcore/network.h
- toxcore/ping.c
- toxcore/ping.h
We now either log errors or properly propagate them. In the case of ping_send_request we make the function return void because it doesn't seem to matter whether or not it succeeds (none of its callers check the return value).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1759)
> cleanup: address some unused return values

- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/msi.c
- toxav/rtp.c
- toxav/toxav.c
- toxav/video.c
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/friend_connection.c
- toxcore/friend_requests.c
- toxcore/group.c
- toxcore/list.c
- toxcore/logger.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/ping.c
- toxcore/ping_array.c
- toxcore/tox.c
- toxcore/util.c
Currently only `crypto_core_mem.c` needs this. We should try not to
depend on configure'd values. Also note: config.h is only created and
used in the autotools build. In CMake, we pass `-D` flags directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1761)
> cleanup: Don't include `"config.h"` unless needed.

- .travis/tox-bootstrapd-docker
- other/bootstrap_daemon/README.md
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
/var/lib/tox-bootstrapd on the host is owned by hosts's tox-bootstrapd
and chowned 700, but the container attempts to access it as its own
tox-bootstrapd user with possibly different uid:gid, which will fail if
host's tox-bootstrapd user has different uid:gid than the tox-bootstrapd
user inside the container.
This change makes the container use host's tox-bootstrapd uid:gid, which
fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1765)
> feat: Fix file permission issue with toxchat/bootstrap-node Docker container

- .circleci/config.yml
- other/analysis/gen-file.sh
- other/analysis/run-clang
- toxcore/crypto_core_test.cc
Also fix crypto_core_test.cc to comply with the stack frame limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1773)
> chore: Fix gen-file.sh: it wasn't globbing properly.

- CMakeLists.txt
- other/analysis/run-clang
- other/analysis/run-gcc
- other/fun/BUILD.bazel
- other/fun/cracker.c
- other/fun/cracker_simple.c
- more inteligent secret key generation
- use OpenMP for multithreading
- support prefixes with odd number of hex characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1622)
> perf: Make the key cracker a bit faster

- other/astyle/format-source
APIDSL no longer works with these header files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1783)
> cleanup: fix format-source

- toxcore/DHT.c
fixes #1788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1789)
> refactor: rename variable to clarify purpose

- .github/workflows/ci.yml
- .travis/cmake-freebsd-stage2
This is more likely to change with the code so should live here, not in
dockerfiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1794)
> chore: Move cmake-freebsd-stage2 back into the toxcore repo.

- toxcore/network.c
I missed this one because cimple didn't recurse into `#ifdef`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1797)
> cleanup: Move `sodium.h` include to front of network.c.

- .cirrus.yml
- toxav/bwcontroller.h
- toxav/groupav.h
- toxav/msi.c
- toxav/rtp.c
- toxav/rtp.h
- toxcore/logger.c
- toxcore/tox.h
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
Tokstyle no longer allows:
* Includes inside an `extern "C"`
* Comments on function definition and declaration to be different.
* Doxygen comments commenting on other doxygen comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1801)
> chore: Fix up a few source code comment and style issues.

- .github/workflows/ci.yml
All pushes have already been checked in the pull request. This is just
duplicate work, wasting GH action runners.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1807)
> chore: Don't run CI on master branch pushes.

- .cirrus.yml
- toxcore/tox.h
There is no more apidsl, so you can edit tox.h manually now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1810)
> chore: Remove apidsl comment from tox.h.

- .cirrus.yml
- .github/settings.yml
- .github/workflows/ci.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/ccompat.h
It's nice we are able to compile with `tcc`. Let's not break that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1830)
> chore: Add "tcc" and "compcert" compiler targets.

- .github/settings.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/net_crypto.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/ping.c
Found by tokstyle after https://github.com/TokTok/hs-tokstyle/pull/95.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1834)
> cleanup: Reduce the scope of for-loop iterator variables.

- auto_tests/conference_av_test.c
- auto_tests/conference_double_invite_test.c
- auto_tests/conference_invite_merge_test.c
- auto_tests/conference_peer_nick_test.c
- auto_tests/conference_test.c
- auto_tests/friend_connection_test.c
- auto_tests/lossless_packet_test.c
- auto_tests/lossy_packet_test.c
- auto_tests/overflow_recvq_test.c
- auto_tests/overflow_sendq_test.c
- auto_tests/reconnect_test.c
- auto_tests/run_auto_test.h
- auto_tests/send_message_test.c
- auto_tests/typing_test.c
This also allows us to set other tox options. Currently it will only bootstrap to the testnet TCP node since none of the non-NGC tests use TCP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1815)
> test: add ability for autotests to use TCP connections

- .cirrus.yml
- .github/settings.yml
This has in the already found real bugs that only happen when compiling
with stack protector and no optimisations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1837)
> chore: Add bazel-debug build.

- toxav/audio.h
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/msi.h
- toxav/toxav.c
- toxav/video.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1844)
> cleanup: make struct typedefs have the same name as their struct

- auto_tests/toxav_basic_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1845)
> fix: use correct sample size in toxav_basic_test

- .github/workflows/ci.yml
- .travis/cmake-linux
Since all of the checks from the old `.travis/cmake-linux` (as far as I can tell) have been added to e.g. Circle CI, I nuked most of the file similarly to how it was done in 8ce2ae0fcbc4bb4d2952fb1245a72b408d8f3170.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1850)
> chore: Add a GH Actions code coverage job

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/group.c
- toxcore/mono_time.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/ping_array.c
- toxcore/tox.c
- toxcore/tox_api.c
- toxencryptsave/toxencryptsave.c
`malloc` is used only for byte/int arrays. Also, we no longer allow plain
`void *` allocations. Every allocation should have a real value type.
See https://github.com/TokTok/hs-tokstyle/pull/103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1861)
> cleanup: Use `calloc` instead of `malloc` for struct allocations.

- .cirrus.yml
- other/fun/BUILD.bazel
I broke it. I'll re-enable it if/when I fix omp support in the bazel
build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1870)
> chore: Disable the OpenMP cracker in bazel for now.

- other/bootstrap_daemon/BUILD.bazel
- testing/BUILD.bazel
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
This ensures that we're explicit about what we depend on and avoids
transitive dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1871)
> chore: Enable compiler layering check.

- other/analysis/gen-file.sh
- toxav/bwcontroller.c
- toxav/rtp.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/network.c
- toxcore/onion_client.c
- toxcore/state.c
See https://github.com/TokTok/hs-tokstyle/pull/105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1865)
> cleanup: Remove extra parens around function arguments.

- toxav/audio.c
Fixes #1694
Thanks to @ryancaicse for the pointer!
---
That for loop is so filthy, it needs to be re-written as a while loop, but I don't want to even touch that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1832)
> fix: a double-unlocking mutex in toxav

- testing/BUILD.bazel
- toxcore/Messenger.c
This seems to be the sweet spot for the current tokstyle implementation.
4 cores gives the same speedup, 5 also, 6 makes it slower, and 2 also
makes it slower.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1866)
> chore: Run tokstyle with 3 cores.

- other/DHT_bootstrap.c
- other/fun/BUILD.bazel
- other/fun/strkey.c
- testing/DHT_test.c
- testing/Messenger_test.c
atoi doesn't check if the conversion from string to int succeeded which doesn't allow us to do proper error handling.
We also now make sure that the port argument is a valid port in addition to being properly converted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1874)
> cleanup: replace all instances of atoi with strtol

- .cirrus.yml
- testing/BUILD.bazel
These have all dependencies built with asan/tsan, so they can do deeper
sanity checks such as checking what opus is doing with our buffers.
The asan check currently fails for me locally, so these are not yet set
to be required for PRs to be merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1875)
> chore: Add asan/tsan bazel builds.

- .circleci/config.yml
- .cirrus.yml
- .github/settings.yml
- .github/workflows/ci.yml
- BUILD.bazel
- auto_tests/conference_av_test.c
- auto_tests/encryptsave_test.c
- other/astyle/format-source
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/crypto_core.c
- toxcore/crypto_core_test.cc
- toxcore/network.h
- toxcore/onion.c
- toxcore/onion_client.c
- toxcore/ping.c
- toxencryptsave/BUILD.bazel
Also added a valgrind build to run it on every pull request. I've had to
disable a few tests because valgrind makes those run infinitely slowly,
consistently timing them out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1877)
> fix: Fix some uninitialised memory errors found by valgrind.

- toxcore/Messenger.c
This fixes high CPU load in c-toxcore due to started but not accepted
file transfers causing lots of iterations in do_all_filetransfers(...).
Additionally this skips expensive calls max_speed_reached(...).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1878)
> fix: don't count filetransfer as sending until accepted

- .circleci/config.yml
- .cirrus.yml
- .github/settings.yml
- .restyled.yaml
- auto_tests/encryptsave_test.c
- other/analysis/gen-file.sh
- other/analysis/run-check-recursion
- other/analysis/run-clang
- other/analysis/run-clang-analyze
- other/analysis/run-clang-tidy
- other/analysis/run-cppcheck
- other/analysis/run-gcc
- other/analysis/run-infer
- other/analysis/variants.sh
- toxcore/crypto_core.c
Currently: 1) libsodium and 2) nacl.
Note that the "nacl" variant is actually libsodium. We just want to make
sure the static analysers see the `VANILLA_NACL` code paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1880)
> chore: Run static analysers in multiple variants.

- .github/scripts/cmake-freebsd-stage2
- .github/scripts/cmake-osx
- .github/scripts/cmake-windows.sh
- .github/scripts/flags.sh
- .github/scripts/sonar-build
- .github/scripts/sonar-prepare
- .github/workflows/docker.yml
- .github/workflows/sonar-scan.yml
- sonar-project.properties
We can't run this on pull requests because it needs access to the
`SONAR_TOKEN` secret. Perhaps in the future we can make it a
`pull_request_target` workflow, but then we can't use cmake to initialise
the environment, meaning we need to specify the inputs manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1883)
> chore: Add sonar-scan analysis on pushes.

- .github/settings.yml
- .github/workflows/ci.yml
- .github/workflows/sonar-scan.yml
- other/analysis/check_recursion
- other/bootstrap_daemon/docker/get-nodes.py
- other/fun/bootstrap_node_info.py
- other/fun/make-funny-savefile.py
Also fix the types in all Python files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1884)
> chore: Add mypy Python type check.

- toxcore/Messenger.c
Replaced with snprintf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1891)
> cleanup: Remove our only use of sprintf.

- auto_tests/network_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/bwcontroller.c
- toxav/rtp.c
- toxav/toxav.c
- toxcore/TCP_client.c
- toxcore/network.c
- toxcore/network.h
We have a more portable wrapper that is now also thread-safe. Also
stopped using sprintf in the one place we used it. This doesn't really
help much, but it allows us to forbid sprintf globally.
See https://github.com/TokTok/hs-tokstyle/pull/110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1889)
> cleanup: Stop using `strerror` directly.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
No need to make copies of the data. There is no concurrency in qsort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1898)
> cleanup: Use pointer cast instead of memcpy in qsort callback.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/LAN_discovery.h
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/group.c
- toxcore/group.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/onion_client.c
- toxcore/ping.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1901)
> cleanup: Make parameters pointers-to-const where possible.

- BUILD.bazel
They were already exposed as `cc_library`, but we need to make the files
as text available so that binding generators can access them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1909)
> chore: Expose public API headers as files in bazel.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/TCP_common.c
- toxcore/TCP_common.h
- toxcore/TCP_server.c
- toxcore/group.c
- toxcore/network.c
We still have them in toxav. That will need to be cleaned up later.
Flexible array members have very limited usefulness. In this particular
case, it's almost entirely useless. It confuses static analysers and is
yet one more C feature we need to understand and support. It is also the
only reason we need special support in tokstyle for calloc with a `+`
operator in the member size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1910)
> cleanup: Remove our only use of flexible array members in toxcore.

- .github/workflows/ci.yml
- other/make_single_file
This will also be used for static analysers that can't deal with multiple
source files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1916)
> chore: Add a make_single_file script, used for CI.

- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/fun/save-generator.c
This is a small change to fix a reproducible problem of DHT_Bootstrap.exe being unable to read the data from the key file. Seems to be an issue with EOL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1923)
> fix: corruption in key files, making it unable to load when node starts.

- toxav/groupav.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1929)
> cleanup: make some non-const pointers const

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/LAN_discovery.c
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test.cc
The brackets serve no purpose and make us do extra string parsing when using the output for other things.
Also removed a useless call to ip_ntoa in LAN_discovery.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1937)
> cleanup: remove brackets from ip_ntoa ipv6 formatting

- .cirrus.yml
- .github/settings.yml
See https://github.com/TokTok/toktok-stack/pull/327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1939)
> chore: Rename bazel-release to -opt and -debug to -dbg.

- toxav/audio.c
- toxav/rtp.c
These showed up as false positives in sonar's static analysis, but it took long enough to figure that out that some extra sanity checks are warranted for readability purposes.
Also removed some unnecessary null checks before calling `free()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1942)
> cleanup: Add some toxav bounds/sanity checks

- auto_tests/TCP_test.c
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/docker/update-sha256
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_common.c
- toxcore/TCP_common.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
Also added a whole bunch of logging that I needed while debugging the
issue. The solution in the end is that bootstrap needs to resolve IPs,
and getaddrinfo fails in the browser. Most of the time we bootstrap
against IPs anyway, so trying to parse as IP address first will shortcut
that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1945)
> fix: Fix bootstrap on emscripten/wasm.

- testing/BUILD.bazel
So we can push the latest cimple to toktok-stack and then start fixing
the warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1956)
> chore: Disable some cimple warnings for now.

- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/LAN_discovery.c
- toxcore/LAN_discovery.h
- toxcore/friend_connection.c
It only needs net and dht public key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1964)
> cleanup: Don't pass the whole DHT object to lan discovery.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
strerror_r() has two versions: GNU-specific and XSI-compliant. The XSI
version always stores the string in the provided buffer, but the GNU
version might store it in the provided buffer or it might use some
immutable static buffer instead. Since we always free the error string,
we might end up freeing the immutable static buffer.
https://man7.org/linux/man-pages/man3/strerror.3.html
Fixes #1967
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1948)
> fix: potential freeing of an immutable static buffer

- .circleci/config.yml
- .github/workflows/ci.yml
- .gitignore
- other/analysis/check_includes
- other/analysis/check_recursion
- toxav/audio.c
- toxav/msi.h
- toxcore/ccompat.h
- toxcore/onion_client.c
Most system headers contain functions (e.g. `memcpy` in `string.h`)
which aren't needed in our own header files. For the most part, our own
headers should only include types needed to declare our own types and
functions. We now enforce this so we think twice about which headers we
really need in the .h files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1968)
> cleanup: Ensure we limit the system headers included in .h files.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/onion_client.c
Using modulus to generate random numbers in a range creates a bias in its output. The libsodium randombytes_uniform() function guarantees a uniform distribution of possible outputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1975)
> refactor: use proper method for generating random numbers in a range

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_common.c
- toxcore/TCP_server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1984)
> fix: Reduce logging verbosity even more.

- README.md
* Drop the Travis build status.
* Drop the link to projects since we're not using that GitHub feature
anymore.
* Update the Binaries/Downloads link to point to tox.chat/downloads. The
previous link just lead to a page telling the user to go to
tox.chat/downloads.
* Update the code coverage badge to point to codecov.
I looked at replacing the Travis build status with GitHub Actions, but we don't run the "CI" workflow on master, only on other branches, so there was no direct replacement. Should we replace that with a badge for a different workflow or from some other CI provider?
Fixes #1670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1979)
> chore: Update readme header

- toxav/msi.c
- toxav/msi.h
Fixes #1977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1985)
> cleanup: Split msi callback array into 1 member per callback

- .github/scripts/flags-clang.sh
- other/docker/autotools/run
- other/docker/circleci/Dockerfile
- other/docker/circleci/run
- other/docker/doxygen/run
Fixes #128.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1982)
> chore: Add an easy way to run autotools and circleci builds locally.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/network.c
- toxcore/tox.c
* Function arguments must use `foo_cb *p` and can't just use `foo_cb p`
* You can no longer cast function pointers (if it's incompatible, you
must wrap the callback). I'm avoiding this with tokstyle exclusions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1987)
> cleanup: Comply with new cimple callback rules.

- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/LAN_discovery.c
- toxcore/LAN_discovery.h
- toxcore/friend_connection.c
It was kind of thread-safe, maybe, but there was a data race that makes
tsan unhappy. We now do interface detection once per Tox instance
instead of once per process.
Fixes #405.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1988)
> cleanup: Make LAN discovery thread-safe without data races.

- .github/scripts/flags-clang.sh
- .github/scripts/flags-gcc.sh
- netlify.toml
- other/analysis/run-clang
- other/analysis/run-clang-tidy
- other/analysis/run-gcc
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/ccompat.h
- toxcore/crypto_core.c
- toxcore/tox.c
These help static analysis and ubsan. We should eventually have all
functions annotated like this with a cimple check to make sure every
pointer has an explicit nullability annotation. The `nullable`
annotation does nothing in GCC, but will be used by cimple to validate
that every parameter has defined nullability.
See https://github.com/TokTok/c-toxcore/issues/2004
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2002)
> cleanup: Add nonnull annotations to function definitions.

- appveyor.yml
- conanfile.py
The issue was that the build was getting mixed up with us building both the static and shared library at the same time. Normally in CMake, you only build one at a time, controlled by `BUILD_SHARED_LIBS`, so now we only build a static library in the Conan build to match what it expects.
I also ran into 
```
conan remote add -i 0 conancenter https://center.conan.io
ERROR: Remote 'conancenter' already exists in remotes (use update to modify)
Command exited with code 1
```
which I think was working around a stale cache, so I added that the cache should be dropped whenever the conanfile.py changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2011)
> fix: Conan build link failures

- CMakeLists.txt
- other/bootstrap_daemon/bash-completion/completions/tox-bootstrapd
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/src/Makefile.inc
Uses bash coding style of https://github.com/scop/bash-completion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2007)
> feat: add bash-completion for tox-bootstrapd

- auto_tests/Makefile.inc
- configure.ac
- toxcore/Makefile.inc
Fixes https://github.com/TokTok/c-toxcore/pull/2010#issuecomment-1033844777.
Turns out libtoxcore.so wasn't being linked against libmsgpackc.
Also adds ability to set custom paths for headers and libs. Basically the libsodium copy-pasta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2015)
> fix: shared toxcore autotools build failing 

- auto_tests/Makefile.inc
- configure.ac
The test was removed in c7ecee7c150617723faa434d70e5647e76f5a53f but
the entries in the build system remained, causing autotools to spit out
warnings.
```
$ ./autogen.sh 
Running autoreconf -if...
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'configure_aux'.
libtoolize: copying file 'configure_aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:258: installing 'configure_aux/ar-lib'
configure.ac:174: installing 'configure_aux/compile'
configure.ac:259: installing 'configure_aux/config.guess'
configure.ac:259: installing …
```
> chore: get skeletons out of the closet

- CMakeLists.txt
- auto_tests/auto_test_support.h
- auto_tests/dht_getnodes_api_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/tox.c
- toxcore/tox_api.c
- toxcore/tox_private.h
This PR adds functionality for clients to send DHT getnodes requests to their DHT peers, as well as to see nodes sent to them from their peers in getnodes response packets. 
A typical use case would be for a DHT network crawler, but it could also be used for understanding and diagnosing DHT network behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1935)
> feat: add DHT queries to private API

- .github/scripts/flags-clang.sh
The warnings in question: `../auto_tests/../toxcore/crypto_core.h:89:4: error: unknown command tag name [-Werror,-Wdocumentation-unknown-command]    * @retval 0 if both mem locations of length are equal `
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2019)
> chore: Silence clang compile warnings causing circle-ci/asan to fail

- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/events/conference_connected.c
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/conference_peer_list_changed.c
- toxcore/events/conference_peer_name.c
- toxcore/events/conference_title.c
- toxcore/events/file_chunk_request.c
- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/events/file_recv_control.c
- toxcore/events/friend_connection_status.c
- toxcore/events/friend_lossless_packet.c
- toxcore/events/friend_lossy_packet.c
- toxcore/events/friend_message.c
- toxcore/events/friend_name.c
- toxcore/events/friend_read_receipt.c
- toxcore/events/friend_request.c
- toxcore/events/friend_status.c
- toxcore/events/friend_status_message.c
- toxcore/events/friend_typing.c
- toxcore/events/self_connection_status.c
- toxcore/tox_unpack.c
- toxcore/tox_unpack.h
tox_unpack is for unpacking Tox types, and bin_unpack is for unpacking ints and binary data. This prevents us from creating dependency cycles due to tox_unpack depending on tox.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2022)
> cleanup: Split tox_unpack into two smaller libs

- .circleci/cmake-ubsan
- toxcore/attributes.h
We enable them on CI, but a default build will compile without them so a
default build doesn't end up with lots of warnings (which we also
disable on CI).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2021)
> chore: Disable non-null attributes by default.

- auto_tests/encryptsave_test.c
- auto_tests/save_friend_test.c
- auto_tests/tox_one_test.c
- other/analysis/check_includes
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/ccompat.h
- toxcore/onion_announce.c
- toxcore/onion_client.c
One of these was creating a single 262144 byte stack frame. We now have
a way to check and limit the allocation size of a VLA. The `Cmp_Data`
ones were also fairly large. Now, no allocation is larger than 2KiB
(though rtp.c allocates close to that much).
Fixes #1998.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2013)
> cleanup: Don't use VLAs for huge allocations.

- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
This should be the last building block for continous fuzzing in c-toxcore.
For now I only enabled batch fuzzing for 15min daily, Corpus pruning (needed) and coverage generation. I'm not sure how much we use of our GH Actions quota, so these numbers need to be monitored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2025)
> chore: add continous fuzzing to our CI

- toxcore/crypto_core.c
```
Building C object CMakeFiles/toxcore_static.dir/toxcore/crypto_core.c.o
c-toxcore/toxcore/crypto_core.c:251:5: warning: implicit declaration of function 'assert' is invalid in C99 [-Wimplicit-function-declaration]
assert(length >= crypto_box_MACBYTES);
^
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2026)
> chore: Fix implicit declaration warning in fuzz build

- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2028)
> fix: syntax error introduced in 8bf37994fd12acec9e3010437502f478399b99b4

- .clusterfuzzlite/build.sh
Builds an additonal fuzzing target, which puts the tox save file parsing code under stress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2030)
> chore: expand fuzzing to toxsave

- testing/fuzzing/toxsave_harness.cc
We can not assert that loading succeeds while feeding corrupted data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2031)
> fix: remove bogus asserts in fuzzer harness

- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
- Increase fuzzing time to 1h
- Start runs at 6:00 UTC and 8:00 UTC, I guess that should fall into low activity times. Would be interesting to get some statistics on what they really are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2035)
> chore: fine tune fuzzing settings

- auto_tests/set_name_test.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
[this is a copy of the branch at git://expert.chickenkiller.com/c-toxcore.git ;
the actual submitter wants to avoid using github, so I (zugz) made this pr for them]
- Make sender send more data per iteration.
- Make receiver iterate more often while receiving.
Before this commit tox would send at maximum around 4MiB/s. With this
patch sustained speeds of up to 100MiB/s were observed on a
low-latency, high-bandwidth network.
As a consequence of iterating more frequently the receiver's CPU usage
is increased for the duration of the transfer. The data structures
used to represent friends and file transfers cause the sender code use
costly loops that do little real work. This patch makes this problem
more visible: the sender uses more CPU while sending.
Poor network conditions were simulated …
> perf: Take advantage of fast networks for file transfers

- toxcore/Messenger.c
This fixes a bug where file transfers would break when the sendto() system call failed with errno 11 (usually indicating a full packet queue).
The max loops constant has also been greatly reduced, as it was excessively CPU intensive, and most connections would not benefit from such a high value. In the future it will be set dynamically.
See 2073d02
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2041)
> fix: file transfer bug introduced in commit 2073d02

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
Previously we would try to send three random TCP relays that we're
connected to to each friend once every 5 minutes. The problem with
this method is that it could take an extraordinarily long time
to share every relay; some relays might be consistently skipped
while others might be sent repeatedly. Moreover, there's no
guarantee that the nodes you try to send are actually online.
This leads to a prety unreliable and flaky way of sharing.
Now we reduce the timer to two minutes, and cycle through the list
trying 3 nodes each share attempt. This guarantees that every online
node in our list gets shared with every friend after a fixed amount of
time (which depends on how many nodes are in the list)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> feat: Improve how we share TCP relays with friends

- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/tox_events.h
They were losing precision by going through uint32_t.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2052)
> fix: Fix return type of functions returning uint64_t.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_server.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/tox.c
Also avoid implicit enum-to-int.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2056)
> cleanup: Avoid implicit boolean and floating point conversions in decls.

- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2058)
> fix: properly deallocate frozen peers

- other/docker/perf/Dockerfile
- other/docker/perf/entrypoint.sh
- other/docker/perf/run
This works on my kernel. If your kernel is older/newer, you may need a
different alpine base image that matches your kernel more closely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2066)
> test: Add a profiling script and Dockerfile.

- .github/workflows/coverity-scan.yml
Instead of on every push. It only produces results once a day anyway.
Fixes https://github.com/TokTok/c-toxcore/issues/2034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2074)
> chore: Make coverity scan a nightly job.

- toxcore/group.c
Don't allocate the memory trusting the values in a toxsave file.
Fixes #2083
Found with https://github.com/TokTok/c-toxcore/runs/5266641816?check_suite_focus=true#step:5:479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2084)
> fix: out-of-memory condition by corrupted save file

- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
Also added declarations using the `_cb` type for each of the callback
handlers in tox.h. This forces cppcheck to check whether the parameter
names in the definitions agree with the `_cb` parameter names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2091)
> cleanup: Avoid casting function pointers.

- toxav/bwcontroller.c
- toxav/msi.c
- toxav/rtp.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/TCP_client.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/group.c
- toxcore/list.c
- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2097)
> cleanup: Remove implicit conversions from `uint32_t` to `bool`.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_common.c
- toxcore/logger.c
- toxcore/mono_time.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
- toxcore/tox.c
Missed a few of those in check-c. check-cimple now catches these with a
stronger type check.
Other changes:
* `ptr + int` must always have the `ptr` first, so `int + ptr` is not
allowed anymore.
* `close` and `time` were shadowing libc functions. `file_data` was
shadowed in a function (and is not a good function name anyway), so
renamed to `send_file_data` which is more descriptive.
* Within a function, all local variables of the same name must have the
same type.
* The `strerror_r` change wasn't necessary, but I kept it because it
seems a bit clearer to me now. `#ifdef`s inside functions are a bit
confusing sometimes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2099) …
> cleanup: Reduce name shadowing; remove ptr-to-bool conversions.

- CMakeLists.txt
- other/cpufeatures.c
The method to detect CPU features in Android has changed and this is no
longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2100)
> chore: remove cpufeatures.c

- toxcore/onion_client.c
Also renamed it to `is_valid`, since that's what the comment says it
means.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2105)
> cleanup: Change valid status of onion friend to bool.

- toxcore/tox.c
Enums should be fairly strong type guarantees about the possible value
range. The API says the return value is unspecified, so this is not a
breaking change.
Fixes https://github.com/TokTok/c-toxcore/issues/169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2114)
> cleanup: Avoid creating invalid enum values.

- auto_tests/TCP_test.c
- auto_tests/dht_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxav/msi.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_client.c
- toxcore/TCP_common.c
- toxcore/TCP_common.h
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/friend_connection.c
- toxcore/friend_requests.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/ping.c
- toxcore/tox.c
- toxcore/util.c
- toxcore/util.h
- toxcore/util_test.cc
These were found by the new stronger type check in cimple. The one
bugfix is in `crypto_sha512_cmp`, which used to think `crypto_verify_32`
returns bool while actually it's -1/0/1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2116)
> cleanup: Remove more boolean conversions (and a bugfix).

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_server.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/group.h
- toxcore/list.c
- toxcore/list.h
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion.c
- toxcore/onion_client.c
- toxcore/ping.c
- toxcore/tox.c
These were found by the new cimple type check which is completely
unforgiving to implicit boolean conversions. After this PR, there should
be no more implicit int-to-bool or bool-to-int conversions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2120)
> cleanup: Remove all boolean-int conversions.

- .github/scripts/flags-gcc.sh
- toxcore/ccompat.h
g++ doesn't emit these warnings properly, so the `run-gcc` tool, which
compiles code as C++, doesn't work for all of these. There are a few
builds that do use GCC, e.g. the sonar-scan build, so these flags will
be passed at some point in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2122)
> chore: Enable a bunch more warnings in GCC builds.

- toxcore/network.c
It is the same as `EINPROGRESS`, so the check is useless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2127)
> cleanup: Remove `EAGAIN` from the list of ignored errors.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/DHT_test.cc
Also added an assert to tell coverity that we don't actually have an
overflow (or underflow) of the length parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2128)
> test: Add unit test for create/handle request packets.

- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion_client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2130)
> cleanup: Remove redundant `()` around `return` expression.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/TCP_client.c
Hopefully this will make it clear enough to coverity that we're not
overrunning any buffers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2140)
> cleanup: Add assertion for decrypted data length.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
- toxcore/tox.c
It causes warnings in the logs.
Also added the IP/Port to TCP connect logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2141)
> cleanup: Disable LAN discovery in TCP-only mode.

- auto_tests/save_load_test.c
- toxcore/onion_client.c
- toxcore/onion_client.h
- toxcore/tox.c
- toxcore/tox_test.cc
It does nothing in the onion, but we shouldn't be reporting failure for
it. Also added a bit more information to the `tox_bootstrap` logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2142)
> cleanup: Count re-adding an existing bootstrap node as success.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
For coverity, which continues to think we're overrunning buffers when
at this point it's easy to prove we're not. Here would be the corrected
coverity finding:
6. Condition packet_length <= 105 /* 1 + 32 * 2 + 24 + 16 */, taking false branch.
7. Condition packet_length > 1024, taking false branch.
Now packet_length must be > 105 and <= 1024.
12. Condition len1 == packet_length - (89 /* 1 + 32 * 2 + 24 */) - 16, taking true branch.
len1 must be > 0 (105 - 89 - 16) and <= 919 (1024 - 89 - 16).
14. decr: Decrementing len1. The value of len1 is now between 0 and 919 (inclusive).
This is where coverity goes wrong: it thinks len1 could be up to 2147483629.
15. buffer access should be OK. Coverity thinks it's not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> chore: Be even more explicit about integer range bounds.

- toxav/groupav.c
- toxcore/group.c
- toxcore/group.h
Almost nothing used these. The one thing that did only does it to get a
`Mono_Time` object. We should probably get that from elsewhere, but for
now the refactoring is just this simple move.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2150)
> cleanup: Move all the group.h structs into group.c.

- toxav/rtp.c
This happens when shutting down a toxav session when it still has some
packets in its internal queue. It's not a serious leak and happens very
rarely (1 in 300 runs of the toxav_many_test), but it can happen and
long-running tox instances that start and end calls a lot would
eventually discover this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2155)
> fix: Eliminate memory leak in toxav.

- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group.h
- toxcore/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2156)
> cleanup: Sync doc comments between .h and .c files.

- .circleci/config.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
lossless packet test works now, but all the other tests have weird false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2163)
> chore: Enable memory sanitizer build.

- auto_tests/save_load_test.c
We were leaving a self_connection_status callback attached to tox1 while
reloading tox2 and 3, the only other toxes in the network. This lead to
tox1 occasionally going offline, triggering the "Tox went offline"
assert and failing the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2160)
> test: Improve the stability of the save_load test

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/friend_connection.c
- toxcore/group.c
- toxcore/network.c
- toxcore/network.h
- toxcore/onion_client.c
Most of these were safe (some were not), but even the safe ones can
become unsafe (non-portable) later on when adding pointer or float members.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2149)
> cleanup: Avoid `memset` on structs.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxcore/Messenger.c
- toxcore/network.c
Cimple cannot actually find these without also causing false positives,
but I found them with cimple before removing the code causing false
positives again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2167)
> cleanup: Reduce scope of array-typed variables where possible.

- testing/fuzzing/toxsave_harness.cc
This should test some additional code paths. @iphydf brought that up some time ago and I think it's a good idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2176)
> test: try to save the fuzzed save file again

- auto_tests/TCP_test.c
- auto_tests/auto_test_support.c
- auto_tests/auto_test_support.h
- auto_tests/lan_discovery_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/BUILD.bazel
- toxav/toxav.c
- toxav/toxav_old.c
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/tox.c
- toxcore/tox_struct.h
To avoid unsafe casts that tokstyle doesn't allow and that can cause
random breakages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2158)
> cleanup: Expose `struct Tox` to internal code.

- auto_tests/tox_many_tcp_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_server.c
If the TCP port is in use, try the next TCP port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2182)
> test: Improve stability of tox_many_tcp_test.

- .github/scripts/cmake-osx
- toxcore/ccompat.h
Hopefully they don't throw warnings at us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2186)
> cleanup: Use `_Static_assert` in gcc/clang.

- auto_tests/network_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
- toxcore/network.h
This isn't used anywhere except in network_test. That test now checks
behaviour of the function actually used elsewhere in tox code, instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2188)
> cleanup: Make addr_resolve a private function.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/net_crypto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2195)
> fix: Correct calculation of packet sent time

- auto_tests/Makefile.inc
It keeps timing out. Not great, but it's covered by other builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2196)
> test: Remove save_load_test from autotools build.

- toxcore/Messenger.c
`connection_status_callback` is also used as struct field in net_crypto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2202)
> cleanup: Avoid name clash between struct field and function.

- auto_tests/onion_test.c
- toxcore/onion.c
- toxcore/onion.h
- toxcore/onion_announce.c
- toxcore/onion_announce.h
- toxcore/onion_client.c
- toxcore/onion_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2199)
> cleanup: Mark Mono_Time const where possible.

- .cirrus.yml
- .github/settings.yml
This is very slow, around 20 minutes, which seriously slows down
velocity for little gain. MSAN runs on unit tests and 1 auto test, so
we'll catch increasingly many valgrind-ish bugs that way in one of the
1-5-minute builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2208)
> chore: Remove valgrind build.

- auto_tests/TCP_test.c
- auto_tests/auto_test_support.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/Messenger_test.c
- toxcore/LAN_discovery.c
- toxcore/LAN_discovery.h
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_client.c
- toxcore/TCP_client.h
- toxcore/TCP_common.c
- toxcore/TCP_common.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/attributes.h
- toxcore/friend_connection.c
- toxcore/friend_connection.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
- toxcore/tox_private.h
- toxcore/tox_struct.h
The idea here is to have a `Network` object that contains functions for
network operations and an optional userdata object that can manage those
network operations. This allows e.g. a fuzzer to replace the network
functions with no-ops or fuzzer inputs, reducing the need for `#ifdef`s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2177)
> feat: Add support for overriding network functions.

- .clusterfuzzlite/Dockerfile
- .github/workflows/docker.yml
- other/docker/tokstyle/Dockerfile
Needed for the build afterwards.
Also added the cflite Dockerfile to automatic CI builds so changes to it
are checked in pull requests.
Also fixed the tokstyle docker image. It needs clang instead of gcc now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2210)
> chore: Clone submodules in clusterfuzzlite Dockerfile.

- CMakeLists.txt
- other/analysis/run-cppcheck
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/coverage/Dockerfile
- testing/BUILD.bazel
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/crypto_core_test.cc
- toxcore/group_moderation.c
- toxcore/group_moderation.h
- toxcore/group_moderation_fuzz_test.cc
- toxcore/group_moderation_test.cc
- toxcore/util.c
- toxcore/util.h
Continuation of https://github.com/TokTok/c-toxcore/pull/2168 which was accidentally closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2169)
> feat: Merge moderation portion of new groupchats codebase

- toxcore/tox_api.c
- toxcore/tox_test.cc
Generating functions is ugly. Ideally astyle wouldn't ask us to write 4
lines of code where 1 would be more readable, but such is life (until we
move to clang-format).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2212)
> cleanup: Expand `CONST_FUNCTION` and remove the macro.

- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/tox.c
- toxcore/tox_private.c
- toxcore/tox_private.h
Also moved lock/unlock to tox_private so they can be used across these 2
tox/tox_private translation units.
Also removed 2 unused functions from the private api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2211)
> cleanup: Move definitions of tox_private.h functions to tox_private.c.

- auto_tests/file_saving_test.c
- auto_tests/lossless_packet_test.c
- auto_tests/lossy_packet_test.c
- auto_tests/save_compatibility_test.c
- auto_tests/save_friend_test.c
- auto_tests/send_message_test.c
- other/fun/save-generator.c
- toxcore/tox_test.cc
We should use the functions for these instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2214)
> cleanup: Remove all uses of `TOX_*_MAX_SIZE` macros.

- toxcore/bin_pack.c
- toxcore/bin_pack.h
- toxcore/bin_pack_test.cc
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/conference_peer_name.c
- toxcore/events/conference_title.c
- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/events/friend_lossless_packet.c
- toxcore/events/friend_lossy_packet.c
- toxcore/events/friend_message.c
- toxcore/events/friend_name.c
- toxcore/events/friend_request.c
- toxcore/events/friend_status_message.c
No real reason to have different names. Also "bin" is shorter than
"bytes" to write.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2219)
> refactor: Rename bin_pack/unpack functions the same as cmp funcs.

- .github/scripts/flags-gcc.sh
- auto_tests/TCP_test.c
- auto_tests/crypto_test.c
- other/analysis/run-gcc
This only happens in tests, which are easy to fix. Inside toxcore we
should actually be more stringent, but for now this helps already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2227)
> cleanup: Disallow stack frames of over 9000 bytes.

- .clusterfuzzlite/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2228)
> chore: Fix path to fuzzer binaries in clusterfuzz build.

- CMakeLists.txt
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
Nothing checks whether these layers are actually observed. The bazel
build does check this, so there's no need to have this documentation in
the cmake build. It'll just go out of date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2229)
> cleanup: Remove layers in the cmake build.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/TCP_server.c
- toxcore/TCP_server.h
- toxcore/bin_pack.h
- toxcore/friend_connection.h
- toxcore/friend_requests.h
- toxcore/group.c
- toxcore/group.h
- toxcore/list.c
- toxcore/list.h
- toxcore/logger.h
- toxcore/mono_time.c
- toxcore/mono_time.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/network.h
- toxcore/onion.h
- toxcore/onion_announce.h
- toxcore/onion_client.h
- toxcore/ping.h
- toxcore/ping_array.h
These should be no-ops when passed a null pointer.
See https://github.com/TokTok/hs-tokstyle/pull/190 for the tokstyle check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2238)
> cleanup: Make `*_free` and `kill_*` functions nullable.

- testing/fuzzing/BUILD.bazel
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/fuzz_tox.h
- toxcore/DHT_fuzz_test.cc
- toxcore/group_moderation_fuzz_test.cc
These help creating fuzzer fixtures with non-trivially constructed
objects and takes care of cleaning them up afterwards so the fuzzer code
can focus on the system under test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2232)
> test: Add fuzzer support functions for internal toxcore objects.

- .github/scripts/flags-clang.sh
- CMakeLists.txt
- INSTALL.md
- other/analysis/run-clang
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/logger.c
- toxcore/logger.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2244)
> refactor: Allow NULL logger; make it no-op in NDEBUG.

- auto_tests/network_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test.cc
- toxcore/tox.c
Every use of this function needs to allocate the same buffer. None of
the callers uses a differently sized buffer, so we might as well put it
in a struct and have the type checker prove the buffer size is correct.
Also rename `ip_ntoa` to `net_ip_ntoa` to avoid clashes with ESP-IDF
system libraries which define this function as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2248)
> refactor: Use a struct for the `ip_ntoa` buffer.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
- toxcore/onion_client.c
It was a no-op.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2250)
> cleanup: remove populate_path_nodes_tcp

- other/analysis/run-gcc
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
`system_random()` can fail and return NULL, which should be handled by
toxencryptsave functions.
Also synced function comments between .h and .c file for toxencryptsave.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2246)
> fix: Don't crash if RNG init failed.

- auto_tests/TCP_test.c
- auto_tests/announce_test.c
- auto_tests/auto_test_support.c
- auto_tests/forwarding_test.c
- auto_tests/lan_discovery_test.c
- auto_tests/onion_test.c
- auto_tests/save_load_test.c
- auto_tests/tox_events_test.c
- auto_tests/toxav_many_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- testing/Messenger_test.c
- testing/fuzzing/BUILD.bazel
- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/toxsave_harness.cc
- toxav/toxav.c
- toxcore/mono_time.c
- toxcore/mono_time.h
- toxcore/mono_time_test.cc
- toxcore/ping_array_test.cc
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
- toxcore/tox_private.c
- toxcore/tox_private.h
This makes it so if mono_time is overridden, no monotonic time-related
system call is invoked in tox_new.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2206)
> feat: Allow overriding mono_time in tox_new.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/announce.c
This isn't in production yet. It's in the new announce store code. The
problem was that a negative plain_len was converted to unsigned, which
made it a very large number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2255)
> fix: Fix a stack overflow triggered by small DHT packets.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
In case DEBUG logging is disabled, the formatting done in the
`LOGGER_DEBUG` statement above will not occur, leaving uninitialised
memory here.
Addresses issue 1 in https://github.com/TokTok/c-toxcore/issues/2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2257)
> fix: Format IP as string again in error log.

- .github/workflows/ci.yml
- other/docker/misra/.gitignore
- other/docker/misra/Dockerfile
- other/docker/misra/Makefile
- other/docker/misra/run
- toxav/msi.c
Disabled a whole bunch of rules from the MISRA-C set. Some of them
should be fixed, but most of the ones we violate have good reasons. This
PR documents those reasons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2251)
> chore: Add MISRA-2012 check using cppcheck's misra addon.

- auto_tests/announce_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/announce.c
- toxcore/announce.h
This avoids common names like `on_stored` and `store_data` in global
symbols. Turns out, toxic also has a `store_data`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2258)
> refactor: Rename announce functions into their own namespace.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/bin_pack_test.cc
- toxcore/bin_unpack.c
Each array element is at least 1 byte, so if there are fewer bytes than
array elements, the array size is invalid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2261)
> refactor: Protect array unpacking against invalid lengths.

- testing/fuzzing/BUILD.bazel
- testing/fuzzing/CMakeLists.txt
- testing/fuzzing/func_conversion.h
- testing/fuzzing/fuzz_support.cc
Declutters the fuzz system code a bit, hiding the cast behind a `!` operator.
This doesn't do perfect forwarding, because we don't need it and it complicates the code a bit (littering `std::forward` all over the place).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2277)
> refactor: Avoid `static_cast` in `Fuzz_System` functions.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/crypto_core.c
Right now it only gets built from the first 2 friends in the DHT friend
list: either friend 0 and then 1 or friend 1 and then 0. The randomness
in this code doesn't make sense unless the intention was to select from
all friends, which the code will now do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2283)
> fix: Allow onion paths to be built from more random nodes.

- testing/fuzzing/bootstrap_harness.cc
Right now, it can't fail, but later we want the fuzzer to randomly let
I/O functions fail, so we shouldn't assert that tox_new succeeded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2285)
> test: Don't abort fuzz test when tox_new fails.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/fuzzing/bootstrap_harness.cc
- toxcore/DHT.c
It can't happen in almost every reality, except when the RNG is fairly
broken and doesn't add 2 fake DHT friends on startup. Still, this code
should be defensive and never index outside `num_friends` elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2282)
> fix: Fix potential array out-of-bounds in DHT onion path building.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/onion_announce.c
- toxcore/util.c
- toxcore/util.h
This makes more sense as a module for them to live in. Now, util no
longer depends on crypto_core and can thus potentially be used in
crypto_core in the future (functions like min/max may be useful).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2284)
> refactor: Move crypto utilities from util to crypto_core.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
Revert "fix: Allow onion paths to be built from more random nodes."
This reverts commit 5073882e0f0ea114e4f0efe719a72ecf7b168926.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2287)
> fix: Don't allow onion paths to be built from real friends.

- .github/scripts/coverage-linux
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/proxy/go.mod
- other/proxy/go.sum
- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/fuzz_support.cc
- toxcore/TCP_client.c
- toxcore/network.c
If the `recvbuf` network function returns 0 all the time, that means
there is never any data available on the TCP socket. This change makes
it so there is a random amount of data available on the TCP socket.
Also allow the fuzzer to enable proxy mode.
All of the above invalidate the bootstrap fuzzer corpus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2279)
> test: Enable fuzzing for TCP.

- .github/workflows/cflite_batch.yml
MSAN and UBSAN might be slower, but they still provide valuable information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2288)
> test: enable additional sanitizers for fuzzing

- toxav/msi.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2281)
> cleanup: Avoid goto in msi.c.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/onion_client.c
- toxcore/onion_client.h
Also remove gendering of friends in some comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2297)
> cleanup: remove unused field last_seen from Onion_Friend

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2300)
> chore: Release 0.2.18

- auto_tests/auto_test_support.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/fuzzing/BUILD.bazel
- testing/fuzzing/e2e_fuzz_test.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/protodump.cc
- testing/fuzzing/protodump_reduce.cc
- toxcore/crypto_core.c
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2291)
> test: Add a protocol dump test to generate initial fuzzer input.

- README.md
Might actually be a good idea since the rest of the process seems to go smoothly when cmp submodule is included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2323)
> docs: Update README.md to include cmp submodule info

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
Thanks @zugz for pointing out the bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2327)
> fix: unlock correct dht_friend

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
alternative / continuation of #2328 using `case:  return` to satisfy cimple
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2329)
> refactor: extract each case in handle packet in messenger

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2339)
> fix: missing net to host conversion of port in logging

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
The group privacy status was incorrectly set to private when a peer accepted a friend's group invite, which would cause handshake requests to fail in certain scenarios
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2338)
> fix: bug causing friend group invites to sometimes fail & improve logging

- other/docker/windows/Dockerfile
- other/docker/windows/build_toxcore.sh
This is a change to the build script of the docker container for cross compiling toxcore for windows. I use the same repository cloned dir when I am building for both windows and linux and what tends to happen is CMakeCache.txt and CMakeFiles dir get copied to the build directory inside the container image which results in an error when cmake runs:
`CMake Error: The current CMakeCache.txt directory /tmp/toxcore/CMakeCache.txt is different than the directory /root/Desktop/c-toxcore where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt`
To avoid having this problem I have added two `rm` commands to remove the files that cause the issue.
---
This change is [<img …
> fix: Remove cmake cache files after copying to container build directory

- CMakeLists.txt
- appveyor.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Makefile.inc
- toxcore/announce.c
- toxcore/net_crypto.c
- toxcore/onion.c
- toxcore/onion.h
- toxcore/onion_announce.c
- toxcore/ping.c
- toxcore/shared_key_cache.c
- toxcore/shared_key_cache.h
This removes the old and badly documented/designed shared key cache from DHT.c and moves the implemenation to a separate file. This makes it more testable and allows a better overview of how many caches exist (currently 7, total ~0,5MB). Additionally I think this fixes several missed `crypto_memzero` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2317)
> Refactor: Extract shared key cache into separate file

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_common.h
Instead of announcing a group whenever our connection status changes, including when we gain or lose a TCP relay connection, we now only announce when our UDP status changes, or if our previously announced TCP relay has gone offline. We also refresh our announcement every 20 minutes regardless of any connection changes (this is to rotate the TCP relay in case the chosen one is somehow broken).
This change should vastly reduce the amount of unnecessary DHT traffic related to group announcements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2348)
> refactor: Make some improvements to how often/when we announce a group

- testing/fuzzing/bootstrap_harness.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2362)
> test: enable tcp relay for bootstrap fuzzing

- appveyor.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_common.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/tox.c
If there are more connections waiting to be accepted than MAX_INCOMING_CONNECTIONS existing accepted connections are overwritten.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2364)
> fix: potential endless loop under extremely high load

- testing/CMakeLists.txt
not sure if this works as intended, but i saw a [.patch](https://src.fedoraproject.org/rpms/toxcore/blob/rawhide/f/toxcore-0.2.12-install_libmisc.patch) file in the fedora pkg source and was displeased.
an alternative would be to use a cmake OBJECT library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2341)
> fix: #1144 by forcing misc_tools to be a static lib

- testing/fuzzing/fuzz_support.cc
Enabling the TCP code fuzzing lead to hitting some assertions in the fuzzer support code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2367)
> fix: fuzz support for TCP server

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.h
- toxcore/tox.c
fixes #2358 
potential security issue, if the DNS server can cause this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2361)
> fix: resolve_bootstrap_node() not checking net_getipport() returned count correctly

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.c
The function that tells us if we're connected to a group now behaves according to the documentation and returns true if we're attempting to connect to a group, rather than only returning true if we've connected with other peers.
The original purpose of this function was to inform us if we've manually disconnected from a group. In all other instances, we are effectively "connected" in the sense that we're actively searching for the group in the DHT, if not outright connected to other peers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2370)
> fix: behaviour of group api function

- appveyor.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_common.h
- toxcore/tox.h
The max message length was reduced by 4 bytes to account for the pseudo message ID, which had unintended effects on clients. It makes more sense to increase the raw packet length by four and keep the max group message length the same as the max message length for friend chats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2351)
> fix: Increase max group message length by four bytes

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/fuzzing/e2e_fuzz_test.cc
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
Also flip some callback asserts, because they can be reached by fuzzing eventually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2388)
> chore: Add missing module dependencies.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.h
- toxcore/tox_api.c
- toxcore/tox_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2383)
> fix: add missing ngc constants getter declarations and definitions

- .github/scripts/cmake-android
* Bump the targeted API on armeabi and x86 to 19
- Starting with the r24 NDK, Jelly Bean (APIs 16, 17, and 18) is no longer supported.
* Build libsodium w/ --disable-pie
- Workaround for `ld: error: relocation R_386_PC32 cannot be used against symbol 'crypto_auth_hmacsha512_init'; recompile with -fPIC`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2390)
> chore: Fix the Android CI job

- docs/Doxyfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxav/toxav_old.c
- toxcore/DHT.c
- toxcore/crypto_core.h
Doxygen doesn't like these. We should probably remove all redundant comments, but this was the set of comments doxygen complained about.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2391)
> docs: Fix doxygen config and remove some redundant comments.

- .clang-tidy
- auto_tests/conference_av_test.c
- auto_tests/crypto_test.c
- auto_tests/onion_test.c
- auto_tests/tox_many_tcp_test.c
- other/DHT_bootstrap.c
- other/analysis/run-clang-tidy
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/docker/cimplefmt/Dockerfile
- other/docker/tokstyle/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2405)
> cleanup: Fix a few more clang-tidy warnings.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- testing/fuzzing/bootstrap_harness.cc
- toxcore/group_chats.c
- toxcore/network.c
So we can deallocate stuff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2408)
> fix: Ensure we have allocators available for the error paths.

- .cirrus.yml
- testing/fuzzing/fuzz_support.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2413)
> cleanup: Fix GCC compatibility.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
This was causing pings to be sent every 1-2 seconds rather than the expected interval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2414)
> fix: inversed return values

- .circleci/bazel-test
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/fuzzing/BUILD.bazel
- toxcore/Messenger.c
- toxcore/group.c
- toxcore/state.c
Better error messages than "something went wrong in type 20".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2416)
> chore: Add more logging to loading conferences from savedata.

- .circleci/bazel-test
- .circleci/config.yml
- auto_tests/BUILD.bazel
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/conference_peer_name.c
- toxcore/events/conference_title.c
- toxcore/events/file_chunk_request.c
- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/events/file_recv_control.c
- toxcore/events/friend_connection_status.c
- toxcore/events/friend_lossless_packet.c
- toxcore/events/friend_lossy_packet.c
- toxcore/events/friend_message.c
- toxcore/events/friend_name.c
- toxcore/events/friend_read_receipt.c
- toxcore/events/friend_request.c
- toxcore/events/friend_status.c
- toxcore/events/friend_status_message.c
- toxcore/events/friend_typing.c
- toxcore/group_pack.c
- toxcore/network.c
These are statically allocated (e.g. `uint8_t[1024]`) arrays with variable length data inside them. Examples are group topics and nicknames.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2415)
> refactor: Add a `bin_unpack_bin_max` for max-length arrays.

- toxcore/DHT.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2311)
> cleanup: make it more clear that assert and uint32_t increment both only exist if NDEBUG is not defined

- auto_tests/dht_getnodes_api_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/tox_private.c
- toxcore/tox_private.h
number of total and how many >= 0.2.18 peers you are connected with.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2357)
> feat: get the number of close dht nodes with announce/store support

- other/BUILD.bazel
- other/DHT_bootstrap.c
The current implementation does not allow responding to bootstrap node packets which results in some of the nodes in nodes.tox.chat to not have a version. This also means that we do not know which of those nodes are actually up-to-date and which are not, making things complicated when it comes to contacting the server owners.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2354)
> fix: DHTBootstrap should always respond to version packets with toxcore version

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.c
- toxcore/tox.h
Returning a valid tox instance when loading a corrupt savefile is probably not desired behaviour
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/1944)
> chore: tox_new() should return null when savedata loading fails

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2424)
> fix: Fix memory leak in the error path of loading savedata.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_common.h
- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2380)
> feat: allow for larger incoming NGC packets

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/mono_time.c
- toxcore/mono_time.h
Conversion to seconds happens in `mono_time_get`, and a new function
`mono_time_get_ms` allows code to retrieve monotonic time in
milliseconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2203)
> refactor: Store time in Mono_Time in milliseconds.

- .github/workflows/ci.yml
- other/docker/tcc/Dockerfile
Instead of repeating the instructions in github actions configs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2427)
> cleanup: Use tcc docker image for CI.

- .github/workflows/ci.yml
- other/docker/compcert/Dockerfile
- other/docker/compcert/run
Useful for local runs. Does the same as CI, so if it fails on CI, this can be used to test locally, avoiding slow CI round trips.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2428)
> chore: Add a compcert docker run script.

- .dockerignore
- .github/scripts/cmake-alpine-s390x
- .github/scripts/cmake-freebsd
- .github/scripts/flags.sh
- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/StrictAbi.cmake
- other/analysis/run-clang-tidy
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/alpine-s390x/Dockerfile
- other/docker/alpine-s390x/run
- other/docker/autotools/run
- other/docker/cimplefmt/run
- other/docker/circleci/run
- other/docker/compcert/run
- other/docker/coverage/run
- other/docker/doxygen/run
- other/docker/freebsd/Dockerfile
- other/docker/freebsd/run
- other/docker/perf/run
- other/docker/tcc/run
- other/docker/tokstyle/run
- toxcore/network.c
It doesn't work at all, because we're missing something in the net code to do with endian conversions. I haven't investigated, yet, but at least now we have a failing test that can be investigated.
Also moved to cmake 3.5 at minimum. CMake will stop supporting lower versions than that, soon.
Also moved to C11 from C99 to get `static_assert`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2429)
> test: Add an s390x build (on alpine) for CI.

- CMakeLists.txt
The windows sdk has buggy headers in C11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2432)
> chore: Use C99 on MSVC instead of C11.

- .cirrus.yml
- .github/scripts/cmake-freebsd
- .github/workflows/ci.yml
- auto_tests/crypto_test.c
- toxcore/crypto_core_test.cc
Also, use `cmake --build` instead of manually calling `gmake`. This allows us to maybe later use `ninja` instead of `gmake` without changing this build invocation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2430)
> chore: Retry freebsd tests 2 times.

- auto_tests/dht_getnodes_api_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2436)
> fix: Add missing `htons` call when adding configured TCP relay.

- BUILD.bazel
- auto_tests/BUILD.bazel
- other/BUILD.bazel
- other/bootstrap_daemon/BUILD.bazel
- other/bootstrap_daemon/websocket/websockify/BUILD.bazel
- other/fun/BUILD.bazel
- other/proxy/BUILD.bazel
- super_donators/BUILD.bazel
- testing/BUILD.bazel
- testing/fuzzing/BUILD.bazel
- third_party/BUILD.bazel
- toxav/BUILD.bazel
- toxcore/BUILD.bazel
- toxencryptsave/BUILD.bazel
It's default in .bazelrc now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2438)
> cleanup: Remove explicit layering_check feature.

- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/docker/update-sha256
Docker is defaulting to using BuildKit for building images since version
23.0 (2023-02-01), which is not compatible with this script. The script
was fishing the hash of the intermediate build container in which the
build has failed, in order to run the sha256sum in that image, however
with BuildKit there are no longer any intermediate build containers,
which breaks the script.
The legacy builder is supposedly getting removed in a future version of
Docker, which is why we embrace BuildKit instead of reverting to the
legacy builder via DOCKER_BUILDKIT=0:
$ DOCKER_BUILDKIT=0 docker build ...
DEPRECATED: The legacy builder is deprecated and will be removed in a
future release. BuildKit is currently disabled; enable it
by removing the DOCKER_BUILDKIT=0 environment-variable.
While …
> fix: Docker tox-bootstrapd hash update failing when using BuildKit

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2448)
> feat: group connection queries now return our own connection type

- .cirrus.yml
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/DHT_fuzz_test.cc
- toxcore/Messenger.c
- toxcore/bin_pack.c
- toxcore/bin_pack.h
- toxcore/tox_events.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2420)
> refactor: Use Bin_Pack for packing Node_format.

- other/analysis/run-clang-tidy
Since we have now switched to C11 for all compilers but MSVC.
(tox-bootstrapd is Unix-only while MSVC is Windows-only, so MSVC using C99 is not an issue as it never builds tox-bootstrapd).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2451)
> cleanup: clarify disabling of static assert checks

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/config_defaults.h
That way we don't have to rely on a human to remember to keep `DEFAULT_TCP_RELAY_PORTS_COUNT` in sync with `DEFAULT_TCP_RELAY_PORTS`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2452)
> refactor: replace DEFAULT_TCP_RELAY_PORTS_COUNT with a compile-time calculation

- BUILD.bazel
- CMakeLists.txt
- toxcore/BUILD.bazel
This allows client developers to use the private API without needing to manually specify the header path in the source code, which may vary from system to system.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2453)
> refactor: Install header for private/experimental API functions

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/fun/save-generator.c
- toxcore/group_connection.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2454)
> fix: memory leaks

- .circleci/cmake-ubsan
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/Messenger.c
- toxcore/attributes.h
- toxcore/crypto_core_test.cc
- toxcore/group_announce_test.cc
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_pack.c
- toxcore/group_pack.h
- toxcore/tox_unpack.c
Otherwise the nullability annotations are compiled out in attributes.h.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2459)
> fix: Enable debug flag for ubsan.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
memset() treats the passed buffer as a char* array, assigning to every 1-byte of the array the value. So for a single 4-byte int32_t element, it is assigning bytes 0, 1, 2 and 3 of it to -1. It happens that -1 is 0xFF, so in the end the uint32_t is set to 0xFFFFFFFF, which is -1 in the two's complement, so the memset() actually produces the correct result in the end, assuming the platform uses two's complement integers.
Assigning it in the loop is less error-prone, as using memset() on non-1-byte wide arrays with a non-zero value is fishy, and it is more portable as we don't have to assume the use of two's complement.
~~On IRC, @robinlinden has pointed out that two's complement is the only integer format in C23 so perhaps we shouldn't be as concerned with the portability, but @iphy said …
> refactor: replace memset with a loop

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_common.h
- toxcore/group_pack.c
Rather than aborting the process on invalid group save data we either try to continue if possible, or abort the saving/loading instead of the entire process. This addresses https://github.com/TokTok/c-toxcore/issues/2426
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2466)
> cleanup: Make group saving/loading more forgiving with data errors

- testing/BUILD.bazel
- third_party/BUILD.bazel
Makes iterating on both check-c and the toxcore code easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2470)
> test: Add check-c run to bazel build.

- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
Not all sanitizers are enabled, but the cheap ones are, making the bootstrap node quite a bit more secure at a small runtime cost.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2472)
> feat: Enable ubsan on bootstrap nodes.

- toxcore/mono_time_test.cc
I am having troubles with the windows builds making mono_time a random number generator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2477)
> test: add real timeout test

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.h
- toxcore/tox_api.c
Generated by tokstyle: https://github.com/TokTok/hs-tokstyle/pull/214
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2479)
> feat: Add `to_string` functions for all public enums.

- auto_tests/group_general_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
- toxcore/tox_api.c
- toxcore/tox_private.c
- toxcore/tox_private.h
This function will return an IP address string associated with a peer.
If the peer is not accepting direct connections a placeholder value
will be returned, indicating that their real IP address is unknown.
We do not return TCP relay IP addresses because a TCP connection
with a peer may use multiple relays simultaneously.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2446)
> feat: Add groupchat API function that returns an IP address string for a peer

- auto_tests/tox_dispatch_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/BUILD.bazel
- toxcore/Messenger.c
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/file_recv_control.c
- toxcore/events/friend_connection_status.c
- toxcore/events/friend_message.c
- toxcore/events/friend_status.c
- toxcore/events/self_connection_status.c
- toxcore/group_chats.c
- toxcore/group_pack.c
- toxcore/group_pack.h
- toxcore/tox_events.c
- toxcore/tox_unpack.c
- toxcore/tox_unpack.h
These functions are a bit clearer and don't need to change if enum values change.
See https://github.com/TokTok/hs-tokstyle/pull/212 for the relevant linter implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2475)
> refactor: Give `enum-from-int` functions the ability to report errors.

- other/docker/tcc/Dockerfile
- other/make_single_file
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2484)
> chore: Fix make_single_file to support core-only.

- toxcore/TCP_client.c
- toxcore/net_crypto.h
The only one I'm not so sure about is `Tcp_Socks5_Proxy_Hs`, which has repeats. Should we ignore repeats?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2487)
> refactor: Change all enum-like `#define` sequences into enums.

- testing/BUILD.bazel
This way we can do bazel build //... when cross-compiling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2493)
> chore: Disable targets for cross-compilation.

- other/event_tooling/generate_event_c.cpp
the same changes are also in https://github.com/TokTok/c-toxcore/pull/2392 , but this makes the tool in master correct for master and helps me bring ngc_events up-to-date.
the changes where introduced in 4e603bb61391b55eb3a41a042bd2b635bcc78854
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2494)
> fix: unpack enum function names in event impl generator

- .circleci/config.yml
- .clang-tidy
- .github/workflows/ci.yml
- other/DHT_bootstrap.c
- other/analysis/run-clang-tidy
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/bootstrap_daemon/src/command_line_arguments.c
- other/bootstrap_daemon/src/command_line_arguments.h
- other/bootstrap_daemon/src/tox-bootstrapd.c
- other/docker/autotools/Dockerfile
- other/docker/clang-tidy/Dockerfile
- other/docker/clang-tidy/run
- other/docker/misra/Dockerfile
- other/docker/tokstyle/Dockerfile
- testing/BUILD.bazel
- toxcore/events/friend_status.c
- toxcore/list.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2503)
> cleanup: Upgrade to clang-tidy-17 and fix some warnings.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/ccompat.c
- toxcore/network.c
It's not really bad, unless all connections fail. This is currently erroring on FreeBSD tests, making them fail needlessly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2506)
> cleanup: Make TCP connection failures a warning instead of error.

- other/docker/cppcheck/toxcore.cfg
This helps ensure strerrors are cleaned up everywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2508)
> chore: Add `net_(new|kill)_strerror` to cppcheck's allocators.

- auto_tests/auto_test_support.c
- toxcore/group_announce_test.cc
- toxcore/mono_time.c
- toxcore/mono_time_test.cc
This fixes time resolution issues and simplifies the code a bit. QPC can in theory jump forward in time, but in practice not by enough to matter in our use case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2509)
> fix: Use QueryPerformanceCounter on windows for monotonic time.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/coverage/Dockerfile
- toxav/audio.c
- toxav/bwcontroller.c
- toxav/groupav.c
- toxav/msi.c
- toxav/video.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_connection.c
- toxcore/friend_connection.c
- toxcore/tox.c
- toxcore/tox_events.c
These casts are effectively part of the function type, so it makes sense to have them at the beginning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2512)
> cleanup: Move all vptr-to-ptr casts to the beginning of a function.

- .github/scripts/tox-bootstrapd-docker
- other/bootstrap_daemon/docker/Dockerfile
- other/bootstrap_daemon/docker/fetch-sha256
This fetches it from github, so we don't need to build it locally.
Not super ideal, because devs are supposed to build it locally to prove reproducibility, but we can keep that diligence on the dev to do once when actually merging the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2513)
> chore: Add fetch-sha256 script to update bootstrap node hash.

- toxcore/tox.c
- toxcore/tox.h
These make it clearer which kinds of `uint32_t` can fit in which functions. It also makes it easier to generate higher level bindings without doing a lot of inference/heuristics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2518)
> cleanup: Add typedefs for public API int identifiers.

- toxav/toxav.h
Similar to the toxcore PR. It's clearer and helps apigen understand what the API means.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2521)
> cleanup: Make array params in toxav `[]` instead of `*`.

- toxcore/tox.h
This makes it clearer what is actually a pointer (i.e. the `this` pointer or the `error` pointer) vs. what is an array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2520)
> cleanup: Mark arrays in the tox API as `[]` instead of `*`.

- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
Also renamed the setter parameters to match the property being set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2522)
> cleanup: Make setters take non-const `Tox *`.

- auto_tests/group_message_test.c
- auto_tests/group_moderation_test.c
- auto_tests/group_tcp_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox.c
- toxcore/tox.h
None of the others use out parameters. Also no toxcore function uses out parameters for anything other than arrays and errors. This would be a first, for no good reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2519)
> refactor: Align group message sending with other send functions.

- auto_tests/tox_dispatch_test.c
- testing/fuzzing/protodump_reduce.cc
- toxcore/tox.h
- toxcore/tox_private.h
It's not released, yet, and this function is a pain. We don't want it going forward.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2523)
> cleanup: Move `tox_get_system` out of the public API.

- toxcore/tox.h
In preparation for it becoming private in 0.3.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2526)
> cleanup: Make Tox_Options a typedef.

- toxav/toxav.h
ToxAV does not comply with naming standards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2527)
> cleanup: Add Toxav alias for ToxAV.

- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
Also mark arrays as `[]` instead of `*`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2524)
> cleanup: Add explicit array sizes to toxencryptsave.

- toxav/toxav.h
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2525)
> cleanup: Add dynamically derived array sizes to the API.

- .circleci/config.yml
- .github/scripts/coverage-linux
- CMakeLists.txt
- other/analysis/gen-file.sh
- other/analysis/run-clang
- other/analysis/run-clang-analyze
- other/analysis/run-cppcheck
- other/analysis/run-gcc
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/circleci/Dockerfile
- other/docker/coverage/Dockerfile
- other/docker/doxygen/Dockerfile
- sonar-project.properties
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/DHT_test.cc
- toxcore/DHT_test_util.cc
- toxcore/DHT_test_util.hh
- toxcore/crypto_core_test.cc
- toxcore/crypto_core_test_util.cc
- toxcore/crypto_core_test_util.hh
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
- toxcore/test_util.cc
- toxcore/test_util.hh
- toxcore/test_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2531)
> test: Add more unit tests for `add_to_list`.

- testing/fuzzing/e2e_fuzz_test.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/fuzz_tox.h
- testing/fuzzing/protodump_reduce.cc
- toxcore/BUILD.bazel
- toxcore/DHT_test.cc
- toxcore/DHT_test_util.hh
- toxcore/forwarding_fuzz_test.cc
- toxcore/network_test_util.hh
- toxcore/test_util.hh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2536)
> cleanup: Some more test cleanups, removing overly smart code.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
This garbage data was never looked at due to passing a zero length along with it, but it's still undesirable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2541)
> fix: don't pass garbage data buffer to packet send functions

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/TCP_server.c
Avoiding passing down the entire DHT struct pointer to the inner functions makes it possible in the future to write unit tests without having to construct a full DHT object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2539)
> refactor: Minor refactoring of get_close_nodes functions.

- other/docker/windows/Dockerfile
- other/docker/windows/build_dependencies.sh
- toxcore/DHT_test_util.cc
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
It has padding bytes, so memcmp isn't necessarily safe. It is definitely unsafe for fuzzed node formats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2545)
> refactor: Use `operator==` for equality tests of `Node_format`.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
We now return an error if our broadcast packets fail to send for every peer in the group.
This introduces an API change via an additional error case for custom group packets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2542)
> refactor: packet broadcast functions now return errors

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_connection.c
We always assumed that create_array_entry() would only be called with an empty array entry and wouldn't modify entries on error. We now explicitly require both conditions, and also give an error in the case of a non-null data pointer with a zero length field, as this indicates a logic error.
Checks for an empty array entry that precede a call to create_array_entry() are now redundant. It should be noted that a non-empty entry doesn't necessarily indicate an error. This condition can be triggered if packets are being sent or received faster than they can be processed/acknowledged, which is common when spamming messages on poor connections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> cleanup: Make group packet entry creation less error-prone

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
commit 5b9c420c introduced some undesirable behaviour with packet send functions returning error when they shouldn't. We now only return an error if the packet fails to be added to the send queue or cannot be wrapped/encrypted. We no longer error if we fail to send the packet over the wire, because toxcore will keep trying to re-send the packet until the connection times out.
Additionally, we now make sure that our packet broadcast functions aren't returning an error when failing to send packets to peers that we have not successfully handshaked with yet, since this is expected behaviour.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2549)
> fix: issues with packet broadcast error reporting

- testing/fuzzing/bootstrap_harness.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- toxcore/DHT_fuzz_test.cc
- toxcore/forwarding_fuzz_test.cc
- toxcore/group_announce_fuzz_test.cc
- toxcore/group_moderation_fuzz_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2552)
> fix: Make sure there's enough space for CONSUME1 in fuzzers.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_connection.c
We allow non-null data pointers to be passed to functions alongside 0-length data. For example when creating a data buffer that has room for the entire packet, including ignored header data.
This error broke a rare but legitimate case where we miss packets during a handshake attempt and need to store empty handshake packets in the packet array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2555)
> fix: Remove fatal error for non-erroneous case

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/util.c
- toxcore/util.h
Only applied in one place, but perhaps later we can implement a pattern in tokstyle to find more opportunities for using memdup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2538)
> refactor: Factor out malloc+memcpy into memdup.

- .clusterfuzzlite/build.sh
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- testing/coverage_live.sh
- testing/distill_corpus.sh
- testing/fuzzing/BUILD.bazel
- testing/fuzzing/CMakeLists.txt
- testing/fuzzing/bootstrap_fuzz_test.cc
- testing/fuzzing/e2e_fuzz_test.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.h
- testing/fuzzing/protodump.cc
- testing/fuzzing/protodump_reduce.cc
- testing/fuzzing/rebuild_protodump
- testing/fuzzing/toxsave_fuzz_test.cc
- testing/run_afl.sh
- toxcore/DHT_fuzz_test.cc
- toxcore/crypto_core.c
- toxcore/forwarding_fuzz_test.cc
- toxcore/group_announce_fuzz_test.cc
- toxcore/group_moderation_fuzz_test.cc
- toxcore/mono_time.c
- toxcore/test_util.hh
- toxcore/tox_events_fuzz_test.cc
fuzz_select_target wasn't selecting anything, so fuzzers using that function either did nothing or would only ever select one of the functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2554)
> fix: Make all the fuzzers work again, and add a test for protodump.

- auto_tests/auto_test_support.c
- auto_tests/file_streaming_test.c
- auto_tests/file_transfer_test.c
- auto_tests/save_load_test.c
- auto_tests/tox_many_tcp_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
- toxcore/tox.c
fixes: https://github.com/TokTok/c-toxcore/issues/2335
It also fixes resolving to ipv6 addresses when its disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2468)
> fix(test): tests use ipv6 by default, even with USE_IPV6 set to 0

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox_event.c
Preparation for it being generated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2565)
> refactor: Factor out union pack switch from event packer.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_common.h
This fixes an issue with events where we try to make queries on peers that no longer exist internally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2573)
> cleanup: skip a do_gc iteration before removing peers marked for deletion

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/bin_pack.c
- toxcore/bin_pack.h
- toxcore/bin_pack_test.cc
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/events/events_alloc.h
- toxcore/tox_events.c
- toxcore/tox_events.h
We should only ever use `bin_pack_obj` and friends, which stack-allocate the packer and pass it to callbacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2572)
> cleanup: Remove `bin_pack_{new,free}`.

- auto_tests/group_moderation_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- We no longer assert peer roles in the mod event callback because this causes an issue with the new events implementation, which triggers the events after all the packets from the current tox_iterate() are processed, rather than as the packets are received. These checks were superfluous and shouldn't reduce code coverage.
- A moderator now sets the topic before the founder kicks him in order to increase internal code coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2576)
> cleanup: make some improvements to group moderation test

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/event_tooling/generate_event_c.cpp
- toxcore/events/conference_invite.c
- toxcore/events/conference_message.c
- toxcore/events/conference_peer_name.c
- toxcore/events/conference_title.c
- toxcore/events/file_recv.c
- toxcore/events/file_recv_chunk.c
- toxcore/events/friend_lossless_packet.c
- toxcore/events/friend_lossy_packet.c
- toxcore/events/friend_message.c
- toxcore/events/friend_name.c
- toxcore/events/friend_status_message.c
- toxcore/events/group_custom_packet.c
- toxcore/events/group_custom_private_packet.c
- toxcore/events/group_invite.c
- toxcore/events/group_message.c
- toxcore/events/group_password.c
- toxcore/events/group_peer_exit.c
- toxcore/events/group_peer_name.c
- toxcore/events/group_private_message.c
- toxcore/events/group_topic.c
Some events, notably the file chunk recv one, can give NULL pointers to the client. Not sure they should, but that's what happens, so we support it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2578)
> refactor: Allow NULL pointers for byte arrays in events.

- auto_tests/group_general_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2583)
> test: Fix comment I broke in the events test PR.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/network.c
We really don't support it. I tried for half an hour to get some kind of plan9 cross compilation to work, but it's not working. If anyone wants to bring it back, they are welcome to send a PR including a CI check for it. Until then, these 5 lines of unused code are gone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2588)
> cleanup: Remove plan9 support.

- toxcore/tox_api.c
Macros should be avoided as much as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2591)
> cleanup: Expand the `Tox_Options` accessor macros.

- toxcore/net_crypto.c
- toxcore/net_crypto.h
Calling it a packet ID is a lie, and we'd rather "memzero" than memset with some named value that happens to be 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2593)
> cleanup: Use explicit 0 instead of `PACKET_ID_PADDING`.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/compcert/.gitignore
- other/docker/compcert/Dockerfile
- other/docker/compcert/Makefile
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/LAN_discovery.c
- toxcore/Messenger.c
- toxcore/TCP_server.c
- toxcore/crypto_core.c
- toxcore/friend_connection.c
- toxcore/group_chats.c
- toxcore/group_moderation.c
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/onion.c
- toxcore/tox.c
- toxcore/util.c
- toxcore/util.h
It's clearer and doesn't risk having a non-zero filler value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2594)
> cleanup: Use `memzero(x, s)` instead of `memset(x, 0, s)`.

- .github/workflows/ci.yml
- other/docker/goblint/BUILD.bazel
- other/docker/goblint/Dockerfile
- other/docker/goblint/analysis.json
- other/docker/goblint/run
- other/docker/goblint/sodium.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2597)
> test: Add goblint static analyser.

- auto_tests/TCP_test.c
- auto_tests/save_friend_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/misra/Makefile
- toxav/rtp.c
- toxav/toxav.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_common.c
- toxcore/TCP_server.c
- toxcore/ccompat.h
- toxcore/friend_connection.c
- toxcore/friend_requests.c
- toxcore/group.c
- toxcore/net_crypto.c
- toxcore/onion.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/timed_auth.c
This is step 1 towards removing VLAs altogether.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2592)
> cleanup: Remove all uses of `SIZEOF_VLA`.

- auto_tests/group_moderation_test.c
- auto_tests/group_state_test.c
Since we're nul terminating these buffers they need one extra byte
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2601)
> fix: a few off by one errors in group autotests

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/tox_event.c
- toxcore/tox_events.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2580)
> cleanup: Minor cleanup of event unpack code.

- auto_tests/group_general_test.c
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/group_chats.c
- toxcore/group_common.h
When a peer leaves a group, they send a packet to the group indicating that they're leaving. However if this packet is sent via TCP, it gets put in a packet queue, which is then destroyed on the rest of the group cleanup process before ever being able to send.
This pr allows do_gc() to finish an iteration before cleaning the group up, which allows the TCP packet queue to be emptied. However this bug still exists on a tox_kill() event because we don't have a chance to do another do_gc() iteration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2609)
> fix: partially fix a bug that prevented group part messages from sending

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/TCP_server.c
- toxcore/group.c
- toxcore/list.c
- toxcore/list.h
- toxcore/list_test.cc
- toxcore/net_crypto.c
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test.cc
- toxcore/util.c
- toxcore/util.h
- toxcore/util_test.cc
`memcmp` compares padding bytes as well, which may be arbitrary or uninitialised.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2605)
> fix: Don't use `memcmp` to compare `IP_Port`s.

- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/TCP_client.c
- toxcore/TCP_server.c
- toxcore/network.c
- toxcore/network.h
It's misplaced in DHT, since the data structures are located in network.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2612)
> refactor: Move pack/unpack `IP_Port` from DHT into network module.

- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/log_backend_syslog.c
- other/bootstrap_node_packets.c
- toxcore/DHT.c
- toxcore/Messenger.c
- toxcore/TCP_client.c
- toxcore/TCP_connection.c
- toxcore/TCP_server.c
- toxcore/group.c
- toxcore/group_chats.c
- toxcore/net_crypto.c
- toxcore/network.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2622)
> cleanup: Add more `const` where possible.

- .github/scripts/tox-bootstrapd-docker
- .github/workflows/docker.yml
- other/bootstrap_daemon/docker/Dockerfile
It's pure toil until then. It's only interesting as part of the release checklist, not in regular PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2620)
> chore: Only check the bootstrap daemon checksum on release.

- CMakeLists.txt
We used to assume gtest installation includes gmock, but some users may have only gtest and not gmock.
Fixes #2636.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2637)
> chore: Check that both gtest and gmock exist for tests.

- .clang-tidy
- other/analysis/run-clang-tidy
This enables a bunch more useful checks (and a whole lot of useless ones we then explicitly disable). In particular, misc-const-correctness now works and may make `-Wconst` in tokstyle obsolete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2642)
> chore: Use C++ mode for clang-tidy.

- auto_tests/conference_av_test.c
- auto_tests/conference_double_invite_test.c
- auto_tests/conference_invite_merge_test.c
- auto_tests/conference_peer_nick_test.c
- auto_tests/conference_simple_test.c
- auto_tests/conference_test.c
- auto_tests/dht_getnodes_api_test.c
- auto_tests/file_transfer_test.c
- auto_tests/friend_request_spam_test.c
- auto_tests/friend_request_test.c
- auto_tests/group_general_test.c
- auto_tests/group_message_test.c
- auto_tests/group_moderation_test.c
- auto_tests/group_save_test.c
- auto_tests/group_state_test.c
- auto_tests/group_tcp_test.c
- auto_tests/group_topic_test.c
- auto_tests/save_load_test.c
- auto_tests/tox_many_tcp_test.c
- auto_tests/tox_many_test.c
This frees up the dispatcher from having to know that `Tox *` exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2644)
> refactor: Don't rely on tox_dispatch passing tox in tests.

- docs/Doxyfile
- other/docker/doxygen/dockerignore
- other/docker/doxygen/doxygen.Dockerfile
- other/docker/doxygen/doxygen.Dockerfile.dockerignore
- other/docker/doxygen/run
- other/docker/sources/run.sh
No longer using :sources, since that fails on render.com.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2647)
> docs: Fix up doxyfile.

- toxcore/crypto_core.c
- toxcore/tox.c
- toxcore/tox.h
Instead, unlock it before entering client callback code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2652)
> refactor: Make tox mutex non-recursive.

- other/docker/sources/run.sh
- toxcore/group_chats.c
It correctly warns about potentially dereferencing NULL chat in a log statement. However, chat can semantically never be NULL in that call, and it's just a defensive check. Still good to fix for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2657)
> fix: Fix some false positive from PVS Studio.

- .clang-tidy
- .github/workflows/ci.yml
- other/docker/sparse/.gitignore
- other/docker/sparse/Makefile
- other/docker/sparse/local.mk
- other/docker/sparse/run
- other/docker/sparse/sparse.Dockerfile
- testing/fuzzing/fuzz_support.cc
- toxcore/LAN_discovery.c
- toxcore/TCP_server.c
- toxcore/attributes.h
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
Sparse checks it. This is neater than using a struct, which has some
slightly weird syntax at times. This also reduces the risk of someone adding
another struct member.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2640)
> refactor: Use strong `typedef` instead of `struct` for `Socket`.

- toxcore/group_chats.c
Issue found by iphydf (no tools for this, yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2661)
> fix: Zero out stack-allocated secret key before return.

- toxcore/group_chats.c
Issue found by PVS Studio. It also found another one, but that's a false positive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2660)
> fix: Add missing memunlock of local variable when it goes out of scope.

- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/log_backend_syslog.c
Found by PVS Studio.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2662)
> fix: Correct a few potential null derefs in bootstrap daemon.

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_common.h
- toxcore/tox.c
- toxcore/tox_private.c
This makes me wonder (again) whether we should somehow share types between the public API and the internal ones. All these casts (including the enum casts we already do) are not very nice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2643)
> refactor: Use strong typedef for NGC peer id.

- toxcore/group_moderation.c
It's equivalent, but MISRA requires the latter form. It helps readability in some cases where the type of the overloaded `operator+` is unclear.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2675)
> cleanup: Replace pointer arithmetic with explicit `&arr[i]`.

- auto_tests/group_save_test.c
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This way, clients can decide whether they want to depend on unstable functionality while we change the NGC save format. We can release with experimental functionality disabled by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2678)
> chore: Disable NGC saving by default, enable through Tox_Options.

- toxcore/announce.c
- toxcore/group_connection.c
- toxcore/group_moderation.c
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2666)
> cleanup: Small improvements found by PVS Studio.

- other/docker/goblint/sodium.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/crypto_core_test.cc
- toxcore/group_chats.c
- toxcore/group_moderation_test.cc
Fixes #2649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2671)
> refactor: Use tox rng to seed the keypair generation.

- toxcore/bin_pack.c
- toxcore/bin_unpack.c
It cannot be type-checked easily, so we avoid void pointers entirely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2682)
> cleanup: Never pass `void*` directly to `memcpy`.

- toxcore/group_announce.c
The types were incompatible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2683)
> fix: Pass array, not array pointer, to `memcmp`.

- toxcore/network.c
We can memcpy integral types and array types. There's no need to directly memcpy into or from struct types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2684)
> cleanup: Don't use `memcpy` to cast arbitrary `struct`s to `uint8_t[]`.

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2685)
> cleanup: correct a few nullable annotations

- other/docker/compcert/Makefile
- other/docker/compcert/compcert.Dockerfile
This ensures that we're able to generate a guaranteed semantically correct binary with all of toxcore and libsodium. We don't currently compile libvpx and opus with compcert. Probably not worth the effort.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2686)
> chore: Compile libsodium reference implementation with compcert.

- CMakeLists.txt
- toxcore/BUILD.bazel
- toxcore/Makefile.inc
- toxcore/Messenger.c
- toxcore/crypto_core.c
- toxcore/crypto_core.h
- toxcore/crypto_core_pack.c
- toxcore/crypto_core_pack.h
- toxcore/crypto_core_test.cc
- toxcore/group_chats.c
- toxcore/group_common.h
- toxcore/group_connection.c
- toxcore/group_moderation_test.cc
- toxcore/group_pack.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2672)
> refactor: Use `structs` for extended public/secret keys.

- toxcore/group_chats.c
It happens to work, but isn't clean, and static analysers found this (SonarCloud and Coverity both detected this).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2689)
> fix: Correctly pass extended public keys to group moderation code.

- CMakeLists.txt
- toxcore/Makefile.inc
Unfortunately, events and dispatch are already installed in .18, so we can't stop, but for .19, let's not add this private header if there's the possibility of moving it to a different location (https://github.com/TokTok/c-toxcore/pull/2599). Installing it makes it a chore for package maintainers (debian, pkgsrc).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2698)
> chore: Only install tox_private.h on request.

- .github/workflows/ci.yml
- other/docker/pkgsrc/pkgsrc.Dockerfile
- other/docker/pkgsrc/pkgsrc.Dockerfile.dockerignore
- other/docker/pkgsrc/run
Used by NetBSD, but we build on Alpine Linux for speed. Separately, we will build on NetBSD without pkgsrc, to see whether it compiles and runs there. That VM build is more expensive and harder to debug, so we keep the pkgsrc Linux build for development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2699)
> test: Add pkgsrc build.

- auto_tests/group_general_test.c
- auto_tests/group_invite_test.c
- auto_tests/group_moderation_test.c
- auto_tests/group_save_test.c
- auto_tests/group_state_test.c
- auto_tests/group_sync_test.c
- auto_tests/group_topic_test.c
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2709)
> refactor: Remove "mod" and "founder" from group API naming scheme

- CMakeLists.txt
- INSTALL.md
- Sorted
- Added missing FLAT_OUTPUT_STRUCTURE
- Added missing PROXY_TEST
- Removed no longer existing EXECUTION_TRACE
- Updated some option descriptions and made them match CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2710)
> docs: Update the list of CMake options

- other/docker/slimcc/creduce.sh
- other/docker/slimcc/slimcc.Dockerfile
https://github.com/fuhsnn/slimcc/commit/7b7c98604ab3eb85e68d7b3ae7f884d5537638c8 broke it.
Filed https://github.com/fuhsnn/slimcc/issues/69 with repro.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2718)
> chore: Use a specific non-broken slimcc version.

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
The Observer role was intended to prevent peers from being disruptive and/or interacting with other peers in the group. It wasn't intended to cripple custom protocols running on-top of the groups such as file sharing and message syncing.
In cases where it might be undesirable for observers to use custom packets (e.g. starting a file transfer) the client will still have the ability to decide whether or not to allow it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2728)
> refactor: Observers/ignored peers can now send and receive custom packets

- auto_tests/group_message_test.c
- other/event_tooling/generate_event_c.cpp
- toxcore/events/group_private_message.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/group_common.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_events.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2727)
> feat: add message IDs to private group messages

- auto_tests/group_message_test.c
- toxcore/tox.c
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2729)
> cleanup: use typedef for private message ID's in callback

- auto_tests/TCP_test.c
UPDATE: I am not pretty sure that the fail occurs when the creation of tcp sockets takes a while, because other processes need to run first. In my case its the firewall (eg `opensnitch`) which needs to check and allow the connection first.
Adding a sleep of 50ms after every tcp connection creation fixes the test case, but it might still point to real error, because waiting longer after the actions and before the asserts does not make it recover.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/c-toxcore/2369)
> fix: flaky tcp test

- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2731)
> cleanup: align group send err enum order

- testing/BUILD.bazel
- toxcore/Messenger.c
- toxcore/group_pack.c
- toxcore/group_pack.h
- toxcore/tox_event.c
- toxcore/tox_unpack.c
In preparation for supporting `out` as a type qualifier in parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2726)
> refactor: Rename `out` parameters to `out_$something`.

- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2736)
> cleanup: A more descriptive error for group invite accept function

- testing/fuzzing/bootstrap_fuzz_test.cc
- testing/fuzzing/e2e_fuzz_test.cc
- testing/fuzzing/fuzz_support.hh
- testing/fuzzing/protodump.cc
- testing/fuzzing/protodump_reduce.cc
- testing/fuzzing/toxsave_fuzz_test.cc
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
- toxcore/tox_events.h
- toxcore/tox_private.h
It makes no sense to include it in the public API as clients can't make any meaningful use of it via public API, it can only be used if one also includes other internal/private headers that we don't install.
It's used only in the testing code, which has access to the internal headers.
Fixes #2739, at least to some degree. I decided against moving things to a separate `tox_testing.h` and leaving only things in `tox_private.h` that we are fine with clients using, as otherwise `tox_lock()` / `tox_unlock()` would have to be moved out of `tox_private.h` to somewhere else, but `tox_private.h` actually sounds like the right place for them, naming-wise. So perhaps it's fine if we have things in `tox_private.h` that we don't want clients to use.
- - -
This change is [<img …
> refactor: Don't expose Tox_System in the public API

- .cirrus.yml
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2744)
> docs: Document that group topic lock is default on.

- CMakeLists.txt
- INSTALL.md
Fixes #2734.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2742)
> chore: Add cmake flag to disable unit tests.

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
- other/docker/pkgsrc/pkgsrc.Dockerfile
- so.version
- toxcore/tox.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2691)
> chore: Release 0.2.19

- .github/workflows/ci.yml
actions/github-script@v6 is a Node.js 16 action, and Node.js 16 actions have been deprecated.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2745)
> chore: Fix GitHub actions deprecation warnings

- toxcore/Messenger.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2717)
> cleanup: Remove useless if clause

- other/bootstrap_daemon/src/config.c
[Found by `clang-analyze`](https://app.circleci.com/pipelines/github/TokTok/c-toxcore/7318/workflows/1459b40e-eb05-4a37-89d3-593016088728/jobs/61053?invite=true#step-104-10510_130).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2747)
> fix: Memory leak in the bootstrap daemon

- .circleci/config.yml
- .github/scripts/flags-clang.sh
- other/analysis/run-clang
- toxcore/bin_pack_test.cc
Circle CI's image got updated to use Ubuntu 24.04 (Noble Numbat), which:
- Changed a bit how clang is packaged -- `libclang_rt.ubsan_standalone-x86_64.a` is no longer getting installed
- Includes a newer clang with more enabled warnings in one the umbrella flags like -Weverything, -Wall, etc., like `-Wswitch-default` and `-Wunsafe-buffer-usage`:
- We actually do not want a default in our switches, we want to explicitly handle every case and get warned when we don't, so `-Wswitch-default` should be disables
- `-Wunsafe-buffer-usage` seems to be broken, it warns on things that are perfectly ok, like doing `foo[1] = 0;` where `uint32_t foo[4];`, e.g.
warning:
```bash
/root/work/toxcore/network.c:966:9: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
966 |         ip6.uint32[1] = …
```
> chore: Fix Circle CI build failing

- .github/scripts/cmake-android
see #2390 for a previous update
ndk mentioning the removal of 19+20: https://github.com/android/ndk/releases/tag/r26
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2769)
> chore(ci): new minimum for all android versions is 21

- toxav/rtp.c
and cast from 32bit to 16bit, causing a overflow and making the allocated size too small
supersedes #2766 
fixes #2767 
info copied from #2767 :
> rdata_size here is 16bit, which gets cast from 32bit length, which can be much larger than the max representable of 16bit. BUT, rdata never contains more than a single packet, so why even try to allocate so much...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2768)
> fix: toxav rtp temp buffer allocation size was too large

- toxav/audio.c
VBR is susceptible to a transcription attack, where words can be
deducted from bandwidth fluctuations, even despite the audio being
encrypted. Toxcore does add padding, but it's just 0-7 bytes, to pad to
a 8 byte boundary, which might not be enough. CBR is safe from this
attack, it is the industry recommendation to use CBR: "Applications
conveying highly sensitive unstructured information SHOULD NOT use
codecs in VBR mode."[1], and is what other secure messengers use too,
e.g. Signal.
Here are some papers on this topic:
- A. M. White, A. R. Matthews, K. Z. Snow and F. Monrose, "Phonotactic  
Reconstruction of Encrypted VoIP Conversations: Hookt on Fon-iks," 
2011 IEEE Symposium on Security and Privacy, Oakland, CA, USA, 2011,
pp. 3-18, doi: 10.1109/SP.2011.34.
- L. A. Khan, M. S. Baig, …
> fix: Use Opus in the CBR mode

- other/bootstrap_daemon/src/config.c
- other/bootstrap_daemon/src/config.h
- other/bootstrap_daemon/src/config_defaults.h
- other/bootstrap_daemon/src/tox-bootstrapd.c
A continuation of the cleanup done in https://github.com/TokTok/c-toxcore/pull/2621.
tox-bootrstrapd historically had used ints for boolean values, as it was initially written in C89 which has no `stdbool.h`. Since then it has modernized and moved on to using C11, but the usage of the int type to represent boolean values, "boolean ints", remained. Recently, driven by a desire to eliminate implicit int-to-bool conversion, @iphydf did a cleanup in b7404f24f63054c00c26abab4bd0b9dc58f96efb, changing some of the boolean ints to bools and doing manual int-to-bool conversion on the remaining boolean ints. This left the codebase in an inconsistent state of both ints and bools now being used to represent boolean values, not to mention that the explicit int-to-bool conversions are a bit ugly. The …
> refactor: Make tox-bootstrapd use bool instead of int

- CMakeLists.txt
- auto_tests/toxav_many_test.c
- other/analysis/run-cppcheck
- toxav/BUILD.bazel
- toxav/Makefile.inc
- toxav/audio.c
- toxav/bwcontroller.c
- toxav/bwcontroller.h
- toxav/msi.c
- toxav/msi.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
- toxav/toxav.h
- toxav/toxav_hacks.h
- toxav/video.c
- toxav/video.h
- toxcore/BUILD.bazel
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/tox.c
- toxcore/tox.h
closes #1431
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2651)
> refactor: Make ToxAV independent of toxcore internals.

- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2783)
> fix: Return an error instead of crashing on nullptr args in NGC.

- .cirrus.yml
The default is 1h.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2784)
> chore: lower cirrus ci timeout drastically

- toxcore/friend_connection.c
clean up when it only contains connections in the NONE state.
rare in practice, found by fuzzing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2772)
> fix: friend_connections leak on allocation failure.

- toxav/toxav.h
- fix units to be better readable (`Kb/sec` -> `kbit/sec`)
- use `width` before `height` consistently
- video -> audio typo
---
for another pr: fix video being actually `Mbit/sec` https://github.com/TokTok/c-toxcore/pull/2782
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2754)
> docs(toxav):  fix docs of toxav.h

- toxav/toxav.c
Previously we unintentionally made it Mbit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2782)
> fix(toxav): pass video bit rate as kbit

- auto_tests/TCP_test.c
- auto_tests/announce_test.c
- auto_tests/forwarding_test.c
- auto_tests/onion_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/BUILD.bazel
- toxcore/DHT_fuzz_test.cc
- toxcore/DHT_test.cc
- toxcore/Messenger.c
- toxcore/forwarding_fuzz_test.cc
- toxcore/group_announce_fuzz_test.cc
- toxcore/group_announce_test.cc
- toxcore/group_moderation_test.cc
- toxcore/logger.c
- toxcore/logger.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2789)
> cleanup: Allocate logger using tox memory allocator.

- auto_tests/network_test.c
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/config.c
- testing/Messenger_test.c
- toxcore/DHT.c
- toxcore/DHT.h
- toxcore/Messenger.h
- toxcore/network.c
- toxcore/network.h
- toxcore/tox.c
- toxcore/tox.h
- toxcore/tox_api.c
- toxcore/tox_private.c
Allows clients to prevent leaking IP addresses through DNS lookups. This option, together with disabling Tox UDP, entirely prevents any UDP packets being sent by toxcore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2694)
> feat: Add option to disable DNS lookups in toxcore.

- auto_tests/friend_request_test.c
- toxcore/friend_connection.c
- toxcore/friend_requests.h
- toxcore/onion_client.h
- toxcore/tox.h
This is a band-aid solution that prevents friend requests with long messages from being dropped. However it doesn't solve the underlying problem, described here: https://github.com/TokTok/c-toxcore/issues/2719
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2720)
> fix: friend requests with very long messages are no longer dropped

- auto_tests/network_test.c
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/network.c
- toxcore/network.h
- toxcore/network_test_util.cc
- toxcore/network_test_util.hh
- toxcore/tox.c
- toxcore/tox_private.c
---
---
This pr finally allows us to implement a regression test for https://github.com/TokTok/c-toxcore/pull/2361
Also allows fuzzing returned results from DNS.
---
~This pr implements a different approach to disabling DNS, compared to https://github.com/TokTok/c-toxcore/pull/2694, here we can simply replace the functions pointers in the network object with dummies/stubs.~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2773)
> feat(net): implement the address resolution network struct functions

- auto_tests/crypto_test.c
msan caught this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2804)
> test: Fix crypto_test to initialise its plain text buffer.

- .circleci/config.yml
- CMakeLists.txt
- other/analysis/gen-file.sh
- other/docker/modules/check
- other/docker/modules/modules.Dockerfile
- toxcore/BUILD.bazel
- toxcore/DHT.c
- toxcore/Makefile.inc
- toxcore/crypto_core_test.cc
- toxcore/group.c
- toxcore/onion_announce.c
- toxcore/onion_client.c
- toxcore/sort.c
- toxcore/sort.h
- toxcore/sort_bench.cc
- toxcore/sort_test.cc
- toxcore/sort_test_util.cc
- toxcore/sort_test_util.hh
- toxcore/util.c
- toxcore/util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2638)
> refactor: Use `merge_sort` instead of `qsort` for sorting.

- .circleci/config.yml
- .github/workflows/ci.yml
- other/docker/circleci/Dockerfile
- other/docker/circleci/entrypoint.sh
- other/docker/circleci/run
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2805)
> chore: Fix tsan build by moving it to github ci.

- toxcore/group_common.h
Significantly reduced the memory usage of groups since all message slots are preallocated for every peer for send and receive buffers of buffer size (hundreds of MiB **peak** when save contained a lot of peers to try to connect to)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2801)
> fix: reduce memory usage in group chats by 75%

- auto_tests/group_general_test.c
- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.c
- toxcore/tox.h
This commit deprecates the tox_group_reconnect groupchat API function and modifies the tox_group_join function to automatically reconnect to groups when it's called with a chat_id that designates a group that it's already a member of.
This allows clients to implement group rejoin functionality that lets peers rejoin/reconnect to groups with a passed password argument, which may be necessary if the group password changes while a peer is offline. This fixes the bug described in #2806.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2807)
> fix: Allow peers to reconnect to group chats using a password

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2811)
> cleanup: Remove redundant code for checking if group exists

- .cirrus.yml
- toxav/rtp.c
"tox error: 7" is less useful than "tox error:
TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2812)
> docs: Output the error code string instead of int in toxav logging

- .circleci/config.yml
- .cirrus.yml
- toxcore/group.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2815)
> refactor: Use tox Memory for group allocations.

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2818)
> refactor: Use tox memory in group chats allocations.

- .cirrus.yml
- toxcore/group_moderation.c
- toxcore/group_onion_announce.c
- toxcore/group_pack.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2816)
> refactor: Use tox memory for group moderation/pack allocations.

- auto_tests/save_compatibility_test.c
- toxcore/tox.c
- toxcore/tox.h
Compiling with that flag will make tox compile roughly as if it were v0.3.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2821)
> cleanup: Add a `TOX_HIDE_DEPRECATED` check to hide deprecated symbols.

- auto_tests/TCP_test.c
- auto_tests/save_compatibility_test.c
This is currently only detectable in tests, because the main code uses VLAs where stack frame size is unknown at compile time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2823)
> cleanup: Reduce stack frame sizes to below 4096 bytes.

- toxcore/group_chats.c
- toxcore/group_chats.h
- toxcore/tox.h
The docs now reflect the changes made in commit fc06506. The getfriend_id check was also removed as it no longer serves a purpose. It previously would indicate that the group already existed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2808)
> docs: Update the docs for group join functions

- testing/BUILD.bazel
- testing/decrypt_save.c
- toxencryptsave/toxencryptsave.c
- toxencryptsave/toxencryptsave.h
Also added a tox save decryption tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2824)
> feat: Add `to_string` functions for toxencryptsave errors.

- .circleci/config.yml
- .cirrus.yml
- auto_tests/auto_test_support.c
- auto_tests/auto_test_support.h
- other/DHT_bootstrap.c
- other/bootstrap_daemon/src/tox-bootstrapd.c
- toxcore/logger.c
- toxcore/logger.h
- toxcore/tox.c
We use `uint32_t` everywhere now. It's easier that way, and line numbers are never negative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2820)
> cleanup: Align internal logger with external on type of source line.

- .cirrus.yml
- toxcore/group_chats.c
- toxcore/group_connection.c
- toxcore/group_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2817)
> refactor: Use tox memory in group connection allocations.

- toxcore/onion_announce.c
- toxcore/onion_client.c
Although it is only ever read back on the machine it originated from, it's bad practice and we should not make our protocol have system-specific undefined padding bytes in it.
Found by https://github.com/TokTok/hs-tokstyle/pull/252
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2687)
> fix: Avoid `memcpy`-ing structs into onion ping id data.

- toxcore/onion_announce.c
- toxcore/onion_client.c
If it doesn't work for some reason, right now it would cause trouble (e.g. buffer overrun).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2830)
> cleanup: Check that onion IP/Port packing worked.

- auto_tests/proxy_test.c
- toxav/audio.c
- toxav/audio.h
- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
- toxav/video.c
- toxav/video.h
- toxcore/Messenger.c
- toxcore/group.c
- toxcore/group.h
- toxcore/group_chats.c
- toxcore/group_moderation.c
- toxcore/group_onion_announce.h
- toxcore/list.c
- toxcore/logger.c
- toxcore/mem.c
- toxcore/mem.h
- toxcore/mono_time.c
- toxcore/mono_time.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/tox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2831)
> cleanup: Some random cleanups, mostly related to mem.

- toxcore/LAN_discovery.c
Closes #2749 
Thanks @zoff99 for the idea
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2760)
> fix: Fake broadcast address for 127.x.x.x

- auto_tests/TCP_test.c
- auto_tests/network_test.c
- toxav/rtp.c
- toxav/rtp.h
- toxav/toxav.c
- toxcore/BUILD.bazel
- toxcore/Messenger.c
- toxcore/TCP_common.c
- toxcore/TCP_server.c
- toxcore/bin_pack_test.cc
- toxcore/bin_unpack.c
- toxcore/bin_unpack.h
- toxcore/network.c
- toxcore/network.h
- toxcore/tox_events.c
Some of the last places where we use malloc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2833)
> cleanup: Use tox memory for bin_unpack and net_strerror.

- toxcore/bin_unpack.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2834)
> fix: Don't crash on malloc failures in bin_unpack.

- auto_tests/file_saving_test.c
Silences some warnings from static analysis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2835)
> test: Add some more asserts for I/O and alloc to succeed.

- auto_tests/file_saving_test.c
- toxcore/tox.h
- toxcore/tox_api.c
This way, client code can immediately free their data after the options setter returns true.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2819)
> refactor: Make Tox_Options own the passed proxy host and savedata.

- testing/fuzzing/bootstrap_fuzz_test.cc
- testing/fuzzing/e2e_fuzz_test.cc
- testing/fuzzing/fuzz_support.cc
- testing/fuzzing/fuzz_support.hh
- testing/fuzzing/protodump.cc
- testing/fuzzing/protodump_reduce.cc
Some systems define this, breaking our test code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2836)
> cleanup: Avoid clashing with global define `DEBUG`.

- .circleci/config.yml
- .cirrus.yml
Cirrus is very expensive now. We need to make our builds cheaper before we can use it more. For now, only the build that can't move out will stay, i.e. the FreeBSD VM one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2838)
> chore: Move most cirrus jobs to circleci.

- CMakeLists.txt
- other/docker/pkgsrc/pkgsrc.patch
We're already installing these, but they have been experimental all this time. We should not install them until we're really done with them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2842)
> cleanup: Mark events/dispatch headers as experimental.

- toxcore/group_chats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2738)
> cleanup: remove kicked peers from saved peers list

- .cirrus.yml
- .github/workflows/ci.yml
- auto_tests/CMakeLists.txt
- auto_tests/dht_nodes_response_api_test.c
- toxav/toxav.c
- toxcore/events/dht_nodes_response.c
- toxcore/tox.c
- toxcore/tox_events.c
- toxcore/tox_private.c
- toxcore/tox_private.h
- toxcore/tox_struct.h
Saves us a strlen and is slightly safer. Also, changed the event length to not include the terminating NUL byte. Adding it is just confusing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2861)
> refactor: Use IP string length from ip_ntoa instead of strlen.

- .cirrus.yml
- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- .github/scripts/flags-clang.sh
- .github/workflows/cflite_cron.yml
- .github/workflows/cflite_pr.yml
- testing/fuzzing/CMakeLists.txt
- testing/fuzzing/toxsave_fuzz_test.cc
- toxcore/forwarding_fuzz_test.cc
So we can run them daily and get coverage info from them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2864)
> chore: Add remaining fuzz tests to cflite.

- .github/workflows/cflite_batch.yml
This allows us to test things with less than 1 hour of waiting time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2865)
> chore: Add time option to manual fuzz trigger.

- .github/workflows/ci.yml
- .github/workflows/post-submit.yml
This one takes a long time and never fails because we ignore test failures (of which it has many). The other 2 freebsd builds actually check for test failures so are more valuable. We keep this one for now because it's our own freebsd image build, so we at least want to keep it building in case the other 2 freebsd builds break (e.g. Cirrus shuts down or the freebsd vm workflow goes away).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2875)
> chore: Move one of the 3 freebsd builds to post-submit.

- .github/workflows/deploy.yml
We already put them into an xcframework. There's no strong reason to keep them as separate assets as well.
Also removed the Makefile for single-file uploads, because it individually appears in the release assets. The .c files are intentionally separate asset uploads, but the Makefile is always the same so can be fetched directly from the repo if needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2876)
> chore: Don't upload ios/macos variants in deploy workflows.

- .github/workflows/deploy.yml
This builds the autotools files (configure, etc.) so people can build the code without needing to install autotools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2877)
> chore: Add a source tarball deploy workflow.

- other/version-sync
Fixes #2884
```
robin@u:~/code/c-toxcore$ ./tools/update-versions.sh 0.2.21
+ VERSION=0.2.21
++ git rev-parse --show-toplevel
+ GIT_ROOT=/home/robin/code/c-toxcore
+ cd /home/robin/code/c-toxcore
+ VERSION=0.2.21
+ IFS=.
+ read -ra version_parts
+ other/version-sync /home/robin/code/c-toxcore 0 2 21
5c5
< AC_INIT([tox], [0.2.20])
---
> AC_INIT([tox], [0.2.21])
157c157
< #define TOX_VERSION_PATCH              20
---
> #define TOX_VERSION_PATCH              21
47c47
< set(PROJECT_VERSION_PATCH "20")
---
> set(PROJECT_VERSION_PATCH "21")
14c14
< CURRENT=22
---
> CURRENT=23
16c16
< AGE=20
---
> AGE=21
robin@u:~/code/c-toxcore$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 71b1f333..337ad716 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -44,7 +44,7 @@ …
```
> chore: Update the version-sync script to work in a post-tox.api.h world

- other/version-sync
```
robin@0:~/code/c-toxcore$ ./tools/update-versions.sh 0.2.22
+ VERSION=0.2.22
++ git rev-parse --show-toplevel
+ GIT_ROOT=/home/robin/code/c-toxcore
+ cd /home/robin/code/c-toxcore
+ VERSION=0.2.22
+ IFS=.
+ read -ra version_parts
+ other/version-sync /home/robin/code/c-toxcore 0 2 22
5c5
< AC_INIT([tox], [0.2.20])
---
> AC_INIT([tox], [0.2.22])
157c157
< #define TOX_VERSION_PATCH              20
---
> #define TOX_VERSION_PATCH              22
47c47
< set(PROJECT_VERSION_PATCH "20")
---
> set(PROJECT_VERSION_PATCH "22")
4c4
< COPY . /work/c-toxcore-0.2.20
---
> COPY . /work/c-toxcore-0.2.22
5c5
< RUN ["tar", "zcf", "c-toxcore.tar.gz", "c-toxcore-0.2.20"]
---
> RUN ["tar", "zcf", "c-toxcore.tar.gz", "c-toxcore-0.2.22"]
9c9
< +DISTNAME=    toxcore-0.2.20
---
> +DISTNAME= …
```
> chore: Update the pkgsrc versions in the update-versions tool

- toxcore/events/dht_nodes_response.c
- toxcore/tox_dispatch.c
- toxcore/tox_event.c
- toxcore/tox_events.h
see https://github.com/TokTok/c-toxcore/pull/2860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2890)
> fix: forgot an enum in the nodes request rename

- auto_tests/TCP_test.c
- auto_tests/forwarding_test.c
- auto_tests/onion_test.c
- toxcore/BUILD.bazel
- toxcore/Messenger.c
- toxcore/Messenger.h
- toxcore/TCP_connection.c
- toxcore/TCP_connection.h
- toxcore/group_chats.c
- toxcore/group_common.h
- toxcore/net_crypto.c
- toxcore/net_crypto.h
- toxcore/net_crypto_fuzz_test.cc
- toxcore/net_profile.h
- toxcore/tox_private.c
This allows us to have a single netprof object for all TCP client connections, which makes it easier to query and keep track of TCP network data for groupchats. Previously we were not properly querying groupchat TCP network data via the netprof API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2893)
> refactor: TCP connection netprof objects are now owned by Messenger

- toxcore/group_chats.c
- toxcore/group_common.h
- toxcore/group_connection.c
- toxcore/group_connection.h
but we and the other peer would support direct.
Recreation of #2894 , since the ci is acting funny there.
---
All hail the network profiler.
(missing returning udp traffic)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2905)
> fix(ngc): dont double every message, if we are not directly connected

- CHANGELOG.md
- other/bootstrap_daemon/docker/tox-bootstrapd.sha256
This release brings 2 great featues. First, the abillty to disable DNS lookups, which has been a long requested security feature, which we plan to default to in an upcoming version.
Second, there is an network profiler, which tallies up sent and received network packets.
Beside these features we also have fixes like a 75% memory usage reduction for NGCs and connecting to NGC with a password if we are already joined, which might be necessary if a password was set or changed while you where away.
Furthermore, we now have better localhost discovery, which means that nodes on the same system find each other.
---
If you have not yet upgraded to the previous release (0.2.20), you absolutely should, as it fixes a security issue. All releases before 0.2.20 used VBR opus encoding, which is …
> chore: Release v0.2.21

- toxav/toxav.c
to the same as the vp8 encoder internally checks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2897)
> chore(toxav): tighten the video bitrate

- toxav/toxav.c
- toxav/video.c
and remove a non-existant reference in a comment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2887)
> chore(toxav): increase the idle iterate interval to 1 second
